var songlists18 = [

  "Aerial Fortress [ MXM 18 ]",
  "ARROW RAIN [ MXM 18 ]",
  "Atropa bella-donna [ MXM 18 ]",
  "Aurolla [ MXM 18 ]",
  "Barbatos [ MXM 18 ]",
  "Barbless Ego [ GRV 18 ]",
  "Believe In Yourself [ GRV 18 ]",
  "Black Lotus [ MXM 18 ]",
  "Butterfly Twist [ MXM 18 ]",
  "Call of the World [ MXM 18 ]",
  "Cloud Crasher [ GRV 18 ]",
  "Cynical Joker [ MXM 18 ]",
  "Dogeza Stairs [ MXM 18 ]",
  "eighth-slave [ MXM 18 ]",
  "Elemental Creation (kamome sano Remix) [ MXM 18 ]",
  "Enchante [ MXM 18 ]",
  "FIRST：DREAMS [ MXM 18 ]",
  "GALAXY BURST [ MXM 18 ]",
  "GaLaXyEggPlanT [ MXM 18 ]",
  "Glorious Journey [ MXM 18 ]",
  "Jack-the-Ripper◆ [ MXM 18 ]",
  "Jacob’s Elevator [ MXM 18 ]",
  "JǛPITΨR ♃ GЯÃVITÝ [ MXM 18 ]",
  "Katharsis [ MXM 18 ]",
  "LECTORIA [ MXM 18 ]",
  "lEyl [ MXM 18 ]",
  "Liar rain [ GRV 18 ]",
  "mqlo [ MXM 18 ]",
  "Nhelv [ MXM 18 ]",
  "On take SUN [ MXM 18 ]",
  "Over The Top [ VVD 18 ]",
  "ΩVERFLOW [ MXM 18 ]",
  "OZONE [ GRV 18 ]",
  "PARTY TIME! [ MXM 18 ]",
  "petits fours [ MXM 18 ]",
  "pique [ MXM 18 ]",
  "Pulsar [ MXM 18 ]",
  "rE:Voltagers [ GRV 18 ]",
  "SAMURAI TIGER [ MXM 18 ]",
  "SociuS [ MXM 18 ]",
  "Sudden Visitor [ MXM 18 ]",
  "Teufel [ MXM 18 ]",
  "To:BrandNewDeadline [ MXM 18 ]",
  "Turn the story [ MXM 18 ]",
  "Typhoon Craaash!! [ GRV 18 ]",
  "Übertreffen [ MXM 18 ]",
  "V Sen5eS [ MXM 18 ]",
  "Valanga(polysha Remix) [ MXM 18 ]",
  "Vividly Impromptu [ MXM 18 ]",
  "World of Iris [ VVD 18 ]",
  "Xicholauncher [ MXM 18 ]",
  "ZEИITH [ MXM 18 ]",
  "アオアラシ [ MXM 18 ]",
  "タイムトラベル [ GRV 18 ]",
  "ツマミ戦隊 タテレンジャー [ MXM 18 ]",
  "トマヨイ [ VVD 18 ]",
  "ねこみみ(=ФωФ=)ぱんでみみっく [ GRV 18 ]",
  "び [ MXM 18 ]",
  "ミッドナイト☆WAR [ MXM 18 ]",
  "ランカーキラーガール [ MXM 18 ]",
  "怪盗Fの台本～消えたダイヤの謎～ [ MXM 18 ]",
  "蛇神 [ MXM 18 ]",
  "最小三倍完全数 [ MXM 18 ]",
  "消失(Hommarju Remix) [ MXM 18 ]",
  "翠雨の祷 [ MXM 18 ]",
  "諏訪大信仰 [ MXM 18 ]",
  "星の透る夏空に願う [ MXM 18 ]",
  "無魎大数 [ MXM 18 ]",

  "666 [ EXH 18 ]",
  "ΣgO [ EXH 18 ]",
  "Erm, could it be a Spatiotemporal ShockWAVE Syndrome...? [ EXH 18 ]",

  "Akzeriyyuth [ MXM 18 ]",
  "ALTONA [ GRV 18 ]",
  "Be a Hero! [ MXM 18 ]",
  "BEAST BASS BOMB [ MXM 18 ]",
  "Beyond the BLUE [ MXM 18 ]",
  "Black night [ MXM 18 ]",
  "BLAZING_LAZER [ MXM 18 ]",
  "BlueMoon Princess [ MXM 18 ]",
  "Boss Rush [ MXM 18 ]",
  "Breakin' Asia [ MXM 18 ]",
  "Catch Our Fire! [ MXM 18 ]",
  "Cepheus [ MXM 18 ]",
  "CHERNOBOG [ MXM 18 ]",
  "Cloud 9 [ MXM 18 ]",
  "Concertino in Blue [ MXM 18 ]",
  "crossing blue [ MXM 18 ]",
  "Destiny [ MXM 18 ]",
  "Divine's:Bugscript [ MXM 18 ]",
  "Divine's or Deal [ MXM 18 ]",
  "Doppelganger [ MXM 18 ]",
  "Dreadnought [ MXM 18 ]",
  "DropZ-Line- [ MXM 18 ]",
  "ECHIDNA [ MXM 18 ]",
  "Evans [ MXM 18 ]",
  "FIRE IN MY HEART [ MXM 18 ]",
  "FLOOR INFECTION Medley from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "GAIA [ MXM 18 ]",
  "Gamerz FestivaL [ MXM 18 ]",
  "Gate of Atlantis [ MXM 18 ]",
  "GERBERA [ MXM 18 ]",
  "Ghost Trigger [ MXM 18 ]",
  "Glitter Flatter Scatter [ MXM 18 ]",
  "Goddess Bless you [ MXM 18 ]",
  "Gorgetech [ MXM 18 ]",
  "Grand-Guignol [ MXM 18 ]",
  "HP:1 [ MXM 18 ]",
  "Hug!! Vs. Hug!! [ MXM 18 ]",
  "НУМЛ [ MXM 18 ]",
  "Juggler's Maddness [ MXM 18 ]",
  "JUNKIE FLAVOR [ MXM 18 ]",
  "Khionos TiARA [ MXM 18 ]",
  "KIMIDORI Streak!! [ MXM 18 ]",
  "LastΩmegA [ MXM 18 ]",
  "Legendary Road [ MXM 18 ]",
  "Levier'n NābYss [ MXM 18 ]",
  "Lowermost revolt [ MXM 18 ]",
  "Lunatic Sprinter [ MXM 18 ]",
  "Make Magic [ MXM 18 ]",
  "MeteorGlow Aftermath [ MXM 18 ]",
  "Midnight City Warfare [ MXM 18 ]",
  "Mirrorwall [ MXM 18 ]",
  "MODEL FT4 [ MXM 18 ]",
  "MONOLITH [ MXM 18 ]",
  "New Leaf [ MXM 18 ]",
  "Nexta [ GRV 18 ]",
  "Night Rockin' Bird [ MXM 18 ]",
  "Noisy Minority [ MXM 18 ]",
  "Nostalgic Blood of the Strife [ MXM 18 ]",
  "OPEN MY GATE [ MXM 18 ]",
  "ouroboros -twin stroke of the end- [ MXM 18 ]",
  "ΩVERSOUL [ MXM 18 ]",
  "POLICY BREAK Medley from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "Prey [ MXM 18 ]",
  "PROVOES*PROPOSE <<el fine>> [ GRV 18 ]",
  "Puberty Dysthymia [ MXM 18 ]",
  "PUPA [ MXM 18 ]",
  "Re:End of a Dream [ MXM 18 ]",
  "Яe's NoVE [ MXM 18 ]",
  "Rebellio [ MXM 18 ]",
  "Reb∞t [ GRV 18 ]",
  "REDO the NIGHT [ GRV 18 ]",
  "Redshift [ MXM 18 ]",
  "RHYZING BEAT [ MXM 18 ]",
  "Sacrifice and Faith [ MXM 18 ]",
  "SACRIFICE feat.ayame [ MXM 18 ]",
  "SAtAN [ MXM 18 ]",
  "Scarlet Lance [ MXM 18 ]",
  "She Turns Me On [ GRV 18 ]",
  "Sky High [ MXM 18 ]",
  "#SpeedyCats [ MXM 18 ]",
  "Spirit of the Beast [ MXM 18 ]",
  "STULTI [ MXM 18 ]",
  "SUPER SUMMER SALE [ MXM 18 ]",
  "Sweet Requiem [ MXM 18 ]",
  "Taiko Drum Monster [ MXM 18 ]",
  "The Formula [ MXM 18 ]",
  "The Golden Era [ MXM 18 ]",
  "THE HEAVEN [ MXM 18 ]",
  "Theme of Ricerca [ MXM 18 ]",
  "Touch My Body [ MXM 18 ]",
  "TRICKL4SH 220 [ MXM 18 ]",
  "ULTiMATE INFLATiON [ MXM 18 ]",
  "ULTRAVELOCITY [ MXM 18 ]",
  "V [ MXM 18 ]",
  "Venomous Firefly [ MXM 18 ]",
  "Victim of Nights [ MXM 18 ]",
  "We Go Down [ MXM 18 ]",
  "Wings of Glory [ MXM 18 ]",
  "Xevel [ MXM 18 ]",
  "Yum Yum Sweetie [ MXM 18 ]",
  "お米の美味しい炊き方、そしてお米を食べることによるその効果。 [ MXM 18 ]",
  "オニユリ [ MXM 18 ]",
  "キュリオシティ [ MXM 18 ]",
  "サイコパスラビット [ MXM 18 ]",
  "スラッシュシスターズ [ MXM 18 ]",
  "セイクリッド ルイン [ MXM 18 ]",
  "そして黄金郷へ [ MXM 18 ]",
  "ドリームエンド・サバイバー [ MXM 18 ]",
  "のぼれ八坂坂！ [ MXM 18 ]",
  "びいすと！ [ MXM 18 ]",
  "ファイナルレター [ MXM 18 ]",
  "ホワイトパレード [ MXM 18 ]",
  "まじかる生主＠りすなちゃん [ GRV 18 ]",
  "メイビ～初恋！？ビスケット☆大作戦 [ MXM 18 ]",
  "ワールズエンド・ダンスホール [ MXM 18 ]",
  "怒槌 [ MXM 18 ]",
  "永遠に幸せになる方法、見つけました。 [ MXM 18 ]",
  "壊Rave*it!! 壊Rave*it!! [ MXM 18 ]",
  "神獄烙桜 [ MXM 18 ]",
  "恋歌疾風！かるたクイーンいろは [ MXM 18 ]",
  "業焔繚乱 [ GRV 18 ]",
  "極彩天奏 [ MXM 18 ]",
  "祝福の色彩は想い結ぶ君たち迄 [ MXM 18 ]",
  "準備運動 [ MXM 18 ]",
  "神話に芽吹く [ MXM 18 ]",
  "水簾ノ調 [ MXM 18 ]",
  "誰が為に兎は舞う＝狂速狂騒曲＝ [ MXM 18 ]",
  "超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで [ MXM 18 ]",
  "†渚の小悪魔ラヴリィ～レイディオ† [ MXM 18 ]",
  "光射す澪のユズリハ [ MXM 18 ]",
  "真っ白な靴 [ GRV 18 ]",
  "雷鼓サンダービート [ MXM 18 ]",

  "ΣmbryO [ EXH 18 ]",
  "Feels Seasickness...* [ EXH 18 ]",
  "FIN4LE ～終止線の彼方へ～ [ EXH 18 ]",
  "Fin.ArcDeaR [ EXH 18 ]",
  "I [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Empress Side [ EXH 18 ]",
  "WHITEOUT [ EXH 18 ]",
  "Xronier [ EXH 18 ]",

  "Garakuta Doll Play [ HVN 18 ]",
  "Angelic Jelly [ GRV 18 ]",
  "Celestial stinger [ GRV 18 ]",
  "Completeness Under Incompleteness [ GRV 18 ]",
  "HAELE III ~Angel Worlds~ [ GRV 18 ]",
  "KAC 2012 ULTIMATE MEDLEY [ GRV 18 ]",
  "NEO TREASON [ GRV 18 ]",
  "Ok!! Hug Me [ GRV 18 ]",
  "Opium and Purple haze [ GRV 18 ]",
  "Renegade Fruits [ GRV 18 ]",
  "Triple Counter [ GRV 18 ]",
  "XROSS THE XOUL [ GRV 18 ]",
  "↓↓↓ [ EXH 18 ]",
  "ΑΩ [ EXH 18 ]",
  "Angels And Demons [ EXH 18 ]",
  "Blastix Riotz [ EXH 18 ]",
  "Demise Quartet [ EXH 18 ]",
  "EMPIRE OF FLAME [ EXH 18 ]",
  "#Endroll [ EXH 18 ]",
  "End to end [ EXH 18 ]",
  "Endless GRAVITY [ EXH 18 ]",
  "FLügeL《Λrp:ΣggyØ》 [ EXH 18 ]",
  "Firestorm [ EXH 18 ]",
  "FLOWER [ EXH 18 ]",
  "Fox4-Raize- [ EXH 18 ]",
  "GEOMETRIA [ EXH 18 ]",
  "gigadelic (かめりあ's The TERA RMX) [ EXH 18 ]",
  "HAVOX [ EXH 18 ]",
  "IKAROS DYNAMITE!!!! [ EXH 18 ]",
  "INF-B《L-aste-R》 [ EXH 18 ]",
  "Invitation from Mr.C [ EXH 18 ]",
  "JEHANNEDARC [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Emperor Side [ EXH 18 ]",
  "Lachryma《Re:Queen'M》 [ EXH 18 ]",
  "LegenD. [ EXH 18 ]",
  "MG277 [ EXH 18 ]",
  "NEO GRAVITY [ EXH 18 ]",
  "Ops:Code-Rapture- [ EXH 18 ]",
  "Pon-Pon-Pompoko Dai-Sen-Saw! [ EXH 18 ]",
  "Prayer [ EXH 18 ]",
  "Preserved Valkyria [ EXH 18 ]",
  "Quaint Echo [ EXH 18 ]",
  "REVOLVER [ EXH 18 ]",
  "Sayonara Planet Wars [ EXH 18 ]",
  "Seraphim [ EXH 18 ]",
  "Solar Storm [ EXH 18 ]",
  "tricky trick [ EXH 18 ]",
  "Ultimate Ascension [ EXH 18 ]",
  "UnivEarth [ EXH 18 ]",
  "veRtrageS [ EXH 18 ]",
  "Warriors Aboot [ EXH 18 ]",
  "World's end [ EXH 18 ]",
  "XHAOS JUDGE [ EXH 18 ]",
  "XyHATTE [ EXH 18 ]",
  "アルティメットトゥルース -Phantasm- [ EXH 18 ]",
  "きたさいたま2000 [ EXH 18 ]",
  "ドーパミン [ EXH 18 ]",
  "マサカリブレイド [ EXH 18 ]",
  "ムラサキグルマ [ EXH 18 ]",
  "極圏 [ EXH 18 ]",
  "月光乱舞 [ EXH 18 ]",
  "混乱少女♥そふらんちゃん!! [ EXH 18 ]",
  "侍 Annihilate!! [ EXH 18 ]",
  "灼熱Beach Side Bunny [ EXH 18 ]",
  "消失 [ EXH 18 ]",
  "絶対零度 [ EXH 18 ]",
  "到達してしまった僕らと夢と希望の最之果 [ EXH 18 ]",
  "東方妖々夢 ULTIMATE MEDLEY [ EXH 18 ]",
  "伐折羅-vajra- [ EXH 18 ]",
  "冥天・ヘメカリス [ EXH 18 ]",

  "#Fairy_dancing_in_lake [ VVD 18 ]",
  "Joyeuse [ VVD 18 ]",
  "Sakura Reflection (P*Light Slayer Remix) [ VVD 18 ]",
  "She is my wife すーぱーアイドル [ VVD 18 ]",
  "Unicorn tail Dustboxxxx RMX [ VVD 18 ]",
  "おお われら喜び讃うべし、主よ [ VVD 18 ]",
  "こちら、幸福安心委員会です。 [ VVD 18 ]",
  "ムーニャポヨポヨスッポコニャーゴ [ VVD 18 ]",
  "上海紅茶館～ Chinese Tea Orchid Remix [ VVD 18 ]",
  "C18H27NO3 [ HVN 18 ]",
  "Harpuia [ HVN 18 ]",
  "Idola [ HVN 18 ]",
  "Qubism [ HVN 18 ]",
  "超越してしまった彼女と其を生み落した理由 [ HVN 18 ]",
  "魔境堕天録サリエル [ HVN 18 ]",
  "CODE -CRiMSON- [ GRV 18 ]",
  "Crack Traxxxx [ GRV 18 ]",
  "Hellfire [ GRV 18 ]",
  "Last Concerto [ GRV 18 ]",
  "Wish upon Twin Stars [ GRV 18 ]",
  "最終鬼畜妹フランドール・S [ GRV 18 ]",
  "Bangin' Burst [ EXH 18 ]",
  "Black Emperor [ EXH 18 ]",
  "BLACK or WHITE? [ EXH 18 ]",
  "For UltraPlayers [ EXH 18 ]",
  "Growth Memories [ EXH 18 ]",
  "INSECTICIDE [ EXH 18 ]",
  "VALLIS-NERIA [ EXH 18 ]",
  "VILE CAT [ EXH 18 ]",
  "werewolf howls. [ EXH 18 ]",

  "Broken 8cmix [ HVN 18 ]",
  "Evans VolteX Pf arrange [ HVN 18 ]",
  "Onigo [ HVN 18 ]",
  "The world of sound [ HVN 18 ]",
  "V.I.P. [ HVN 18 ]",
  "金縛りの逢を [ HVN 18 ]",
  "腐れ外道とチョコレゐト [ HVN 18 ]",
  "幻想のサテライト [ HVN 18 ]",
  "孤独の番人 [ HVN 18 ]",
  "Absurd Gaff [ GRV 18 ]",
  "PANIC HOLIC [ GRV 18 ]",
  "Xepher Light and Darkness Dragon Remix [ GRV 18 ]",
  "魔理沙は大変なものを盗んでいきました [ GRV 18 ]",
  "croiX [ INF 18 ]",
  "FLOWER REDALiCE Remix [ INF 18 ]",
  "Max Burning!! [ INF 18 ]",
  "冥 Rockin' SWING REMIX [ INF 18 ]"

];

var songlists17 = [

  "120秒のエンドロール [ MXM 17 ]",
  "	50th Memorial Songs-The BEMANI History- [ VVD 17 ]",
  "ABSOLUTE (EUROBEAT REMIX) [ MXM 17 ]",
  "Adrenaline Rush [ MXM 17 ]",
  "Afterimage d'automne [ MXM 17 ]",
  "AXION [ MXM 17 ]",
  "Believe (y)our Wings {GRA5P WAVES} [ MXM 17 ]",
  "Believe (y)our Wings {V:IVID RAYS} [ MXM 17 ]",
  "bistro twins☆☆☆ [ MXM 17 ]",
  "BLACK JACKAL [ MXM 17 ]",
  "BLIZZARD BEAT [ MXM 17 ]",
  "Bye or not [ MXM 17 ]",
  "Chocolate Parade [ MXM 17 ]",
  "Circulator [ MXM 17 ]",
  "clear:wings [ MXM 17 ]",
  "CLOUDS FLYER -sdvx edit- [ MXM 17 ]",
  "Colorless feat.ももかみ [ MXM 17 ]",
  "D1g1t1ze b0dy [ MXM 17 ]",
  "DESIRE [ MXM 17 ]",
  "empty [ MXM 17 ]",
  "Enigma II [ MXM 17 ]",
  "Enjoy This Time [ MXM 17 ]",
  "Harmonia [ MXM 17 ]",
  "Historia of Velnoti [ VVD 17 ]",
  "Impress (bansou Remix) [ MXM 17 ]",
  "Into The Madness [ MXM 17 ]",
  "MARENOL [ MXM 17 ]",
  "MilK [ MXM 17 ]",
  "Mischievous theater [ MXM 17 ]",
  "ΩBIRD [ MXM 17 ]",
  "One In A Billion（Hedonist Remix) [ MXM 17 ]",
  "Paradisus-Paradoxum [ MXM 17 ]",
  "Pixelated Platform [ MXM 17 ]",
  "PIZZATIME [ MXM 17 ]",
  "Princess Lily [ MXM 17 ]",
  "Quark [ MXM 17 ]",
  "Record one's Dream [ MXM 17 ]",
  "ЯegreT of MemoRy [ MXM 17 ]",
  "Revolution [ MXM 17 ]",
  "Sacrifice Escape:不条理の模倣による感情と代償 [ MXM 17 ]",
  "scary night [ MXM 17 ]",
  "Sharkbait [ MXM 17 ]",
  "Six String Proof [ MXM 17 ]",
  "STYX HELIX（Digi-Rock Remix） [ MXM 17 ]",
  "Sunflower Vibes [ MXM 17 ]",
  "toy boxer [ MXM 17 ]",
  "Tribal Trial [ MXM 17 ]",
  "ULTRA B+K [ MXM 17 ]",
  "ultra turbo [ MXM 17 ]",
  "VIVID DEBUT! [ MXM 17 ]",
  "vivid landscape [ MXM 17 ]",
  "VIVIDWAVERS [ MXM 17 ]",
  "エンゲージ〆ント [ MXM 17 ]",
  "おーまい！らぶりー！すうぃーてぃ！だーりん！ [ MXM 17 ]",
  "ガヴリールドロップキック [ MXM 17 ]",
  "クレイジークレイジーダンサーズ [ MXM 17 ]",
  "シープドリーミン [ MXM 17 ]",
  "ストリーミングハート [ MXM 17 ]",
  "ハレ トキドキ メランコリック [ MXM 17 ]",
  "ハレ晴レユカイ [ MXM 17 ]",
  "ヒトリゴト [ MXM 17 ]",
  "ベビーステップ [ MXM 17 ]",
  "ぼくらの16bit戦争 [ MXM 17 ]",
  "もってけ！セーラーふく [ MXM 17 ]",
  "ゆりゆららららゆるゆり大事件 [ MXM 17 ]",
  "ようこそジャパリパークへ [ MXM 17 ]",
  "ロキ [ MXM 17 ]",
  "伊邪那美白山姫大神 [ MXM 17 ]",
  "悪戯センセーション [ MXM 17 ]",
  "雲海 [ MXM 17 ]",
  "革命パッショネイト [ MXM 17 ]",
  "君は Fantasista [ MXM 17 ]",
  "鏡面の波（ramble mix） [ MXM 17 ]",
  "近未来百鬼夜行譚 [ MXM 17 ]",
  "全力ハッピーライフ [ MXM 17 ]",
  "太陽曰く燃えよカオス（Sol oscuro !Nya! Mix） [ MXM 17 ]",
  "熱情のサパデアード [ MXM 17 ]",
  "祭囃子 [ MXM 17 ]",
  "真夏の海の修道女 [ MXM 17 ]",
  "真夏の蜜と唇 fm.希望の星は青霄に昇る [ MXM 17 ]",
  "夢見草奇譚 [ VVD 17 ]",
  "零次元エクスプレス [ MXM 17 ]",

  "9TH5IN [ EXH 17 ]",
  "ANGER of the GOD [ EXH 17 ]",
  "ENDYMION [ EXH 17 ]",
  "Ghost Family Living In Graveyard [ EXH 17 ]",
  "Lancelot ～Flame of the Rebellion～ [ EXH 17 ]",
  "OUTERHEΛVEN [ EXH 17 ]",
  "ЯeviveR [ EXH 17 ]",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY [ EXH 17 ]",
  "THE凸GENERATOR [ EXH 17 ]",
  "Trill auf G [ EXH 17 ]",
  "voltississimo [ EXH 17 ]",
  "θコトノハθカプセルθ [ EXH 17 ]",
  "色を喪った街 [ MXM 17 ]",

  "3y3s (JMBS FUNKOT RMX) [ MXM 17 ]",
  "405nm(Shu※mix) [ MXM 17 ]",
  "444 [ MXM 17 ]",
  "All Clear!! [ MXM 17 ]",
  "Altale [ MXM 17 ]",
  "Another Chapter [ MXM 17 ]",
  "Apocrypha [ MXM 17 ]",
  "Aragami [ MXM 17 ]",
  "Arcade Prison [ MXM 17 ]",
  "β [ MXM 17 ]",
  "Blue Stream [ MXM 17 ]",
  "BREAKNECK NY☆N! NY★N! [ MXM 17 ]",
  "CARNIVOROUS [ MXM 17 ]",
  "Carry Me Away [ MXM 17 ]",
  "Chaotic Romance [ MXM 17 ]",
  "Chocolate Planet [ MXM 17 ]",
  "cobalt [ MXM 17 ]",
  "Coldlapse [ MXM 17 ]",
  "CUTE-Reflection [ MXM 17 ]",
  "Cy-Bird [ MXM 17 ]",
  "Dark Matter [ MXM 17 ]",
  "Decoy [ MXM 17 ]",
  "Destruction & Qreation [ MXM 17 ]",
  "Dharma [ MXM 17 ]",
  "Dreaming feat.nomico [ MXM 17 ]",
  "Drizzly Venom [ MXM 17 ]",
  "EDEN of TRUTH [ MXM 17 ]",
  "Empathetic [ MXM 17 ]",
  "Fafnir [ MXM 17 ]",
  "Far Away [ MXM 17 ]",
  "Finale [ MXM 17 ]",
  "Fly far bounce [ MXM 17 ]",
  "Four Leaves [ MXM 17 ]",
  "Game Over [ MXM 17 ]",
  "Heavenly Adventure [ MXM 17 ]",
  "HEAVENLY SMILE [ MXM 17 ]",
  "If [ MXM 17 ]",
  "ILL-STARRED Diver [ MXM 17 ]",
  "infinite;youniverse [ MXM 17 ]",
  "Inscape [ MXM 17 ]",
  "Invisible Bullets [ MXM 17 ]",
  "Iridescent Clouds [ MXM 17 ]",
  "JUGGLE [ MXM 17 ]",
  "JULIAN [ MXM 17 ]",
  "Junk Mania [ MXM 17 ]",
  "Justitia Gladius [ MXM 17 ]",
  "Knights Assault [ MXM 17 ]",
  "Libera me [ MXM 17 ]",
  "Lievre -blanche- [ MXM 17 ]",
  "Life is beautiful [ MXM 17 ]",
  "Line 4 Ruin -kohumix- [ MXM 17 ]",
  "Lost Wing at.0 [ MXM 17 ]",
  "Made In Love [ MXM 17 ]",
  "MAXIVCORD [ MXM 17 ]",
  "Melty Sweets [ MXM 17 ]",
  "Musha Vibration [ MXM 17 ]",
  "NEON LOVE♥POTION!!! [ MXM 17 ]",
  "No way [ MXM 17 ]",
  "Oriens [ MXM 17 ]",
  "Phlox [ MXM 17 ]",
  "PIERROT KNIfE [ MXM 17 ]",
  "planetarium [ MXM 17 ]",
  "Poison AND÷OR Affection [ MXM 17 ]",
  "Poppin’Cats!! [ MXM 17 ]",
  "QUAKE [ MXM 17 ]",
  "Rebuilding of Paradise Lost [ MXM 17 ]",
  "Rejoin [ MXM 17 ]",
  "rhythmology study [ MXM 17 ]",
  "Royal Action [ MXM 17 ]",
  "Royal Judgement [ GRV 17 ]",
  "Sadistic Stabbing [ MXM 17 ]",
  "Sakura Mirage -Drum'n World- [ MXM 17 ]",
  "Secret Traveler -MeniRemix- [ MXM 17 ]",
  "sink into the dream [ MXM 17 ]",
  "Sleepless days [ MXM 17 ]",
  "Smoked Turkey Rag [ MXM 17 ]",
  "SPACE VILLAGE [ MXM 17 ]",
  "Sulk [ MXM 17 ]",
  "SUPER BUBBLE JOURNEY [ MXM 17 ]",
  "Synergy For Angels [ MXM 17 ]",
  "Technical Master [ MXM 17 ]",
  "Tic Exe [ MXM 17 ]",
  "Twilight ∞ nighT [ MXM 17 ]",
  "Vigor [ MXM 17 ]",
  "Voltage Higher [ MXM 17 ]",
  "VOLTEXES IV [ MXM 17 ]",
  "WONDER_WOBBLER [ MXM 17 ]",
  "Xibercannon [ MXM 17 ]",
  "Zelophilia [ MXM 17 ]",
  "アワデコノヨヲ [ MXM 17 ]",
  "アンハッピーリフレイン [ MXM 17 ]",
  "インビジブル [ MXM 17 ]",
  "おにいちゃんハイテック [ MXM 17 ]",
  "オンディーヌの泪 [ MXM 17 ]",
  "ケムマキ underground [ MXM 17 ]",
  "ゴーストルール [ MXM 17 ]",
  "コメット⇒スケイター [ MXM 17 ]",
  "すろぉもぉしょん [ MXM 17 ]",
  "セイシュンライナー [ MXM 17 ]",
  "それは花火のような恋 [ MXM 17 ]",
  "ツキアカリ [ MXM 17 ]",
  "デュアルメモリ [ MXM 17 ]",
  "ブチ上げ候！現代忍者三姉妹 [ MXM 17 ]",
  "プラネタジャーニー [ MXM 17 ]",
  "プレインエイジア(MRM REMIX) [ MXM 17 ]",
  "ペタ靴と憂夜リムーバー [ MXM 17 ]",
  "ボーイミーツ・ブルー [ MXM 17 ]",
  "メルヘン風紀委員会 [ MXM 17 ]",
  "ラキラキ [ MXM 17 ]",
  "ロプノールの商隊 [ MXM 17 ]",
  "炎夏の音 [ MXM 17 ]",
  "煙 [ MXM 17 ]",
  "獅子奮迅 [ MXM 17 ]",
  "失敗作少女 [ MXM 17 ]",
  "銃弾は解を撃ち抜いて [ MXM 17 ]",
  "少女綺想曲 -G.X.N. Remix- [ MXM 17 ]",
  "水槽のクジラ [ MXM 17 ]",
  "星座が恋した瞬間を。 [ MXM 17 ]",
  "零の位相 [ MXM 17 ]",
  "創世ノート [ MXM 17 ]",
  "廃獄ドリームランド [ MXM 17 ]",
  "片翼のディザイア [ MXM 17 ]",
  "蓬莱フェスティボー [ MXM 17 ]",
  "僕らの時間 [ MXM 17 ]",
  "焔 -MAGMA- [ MXM 17 ]",
  "見世物ライフ [ MXM 17 ]",
  "蟲の棲む処 [ MXM 17 ]",
  "物凄いスペースシャトルでこいしが物凄いうた [ MXM 17 ]",
  "幽玄の桜 [ MXM 17 ]",
  "闇夜に舞うは紅の華 [ MXM 17 ]",
  "羅生門 [ MXM 17 ]",
  "黎明スケッチブック [ MXM 17 ]",
  "分けるな危険！モモモモモモーイズム [ MXM 17 ]",

  "A Lasting Promise [ EXH 17 ]",
  "Absolute Domination [ EXH 17 ]",
  "Awakening [ EXH 17 ]",
  "BELOBOG [ EXH 17 ]",
  "Chrono Diver -PENDULUMs- [ EXH 17 ]",
  "Cross Fire [ EXH 17 ]",
  "Deadly force [ EXH 17 ]",
  "Dyscontrolled Galaxy [ EXH 17 ]",
  "Elemental Creation [ EXH 17 ]",
  "Failnaught [ EXH 17 ]",
  "FLOOR INFECTION Medley from SOUND VOLTEX×jubeat [ EXH 17 ]",
  "Fly Like You [ EXH 17 ]",
  "FREEDOM DiVE [ EXH 17 ]",
  "GERBERA -For Finalists- [ EXH 17 ]",
  "GODHEART [ EXH 17 ]",
  "HE4VEN ～天国へようこそ～ [ EXH 17 ]",
  "iLLness LiLin [ EXH 17 ]",
  "Last Re [ EXH 17 ]",
  "Rebellio [ EXH 17 ]",
  "Sailing Force [ EXH 17 ]",
  "Staring at star [ EXH 17 ]",
  "TWO-TORIAL [ EXH 17 ]",
  "Xeroa [ EXH 17 ]",
  "セイレーン ～悲壮の竪琴～ [ EXH 17 ]",
  "逆月 [ EXH 17 ]",
  "超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで [ EXH 17 ]",

  "バイナリスター [ VVD 17 ]",
  "ヒミツダイヤル [ VVD 17 ]",
  "Destroy [ GRV 17 ]",
  "Get back here [ GRV 17 ]",
  "Grand Chariot [ GRV 17 ]",
  "INDEPENDENT SKY [ GRV 17 ]",
  "Inixia [ GRV 17 ]",
  "Sephirot [ GRV 17 ]",
  "StrayedCatz [ GRV 17 ]",
  "ZEPHYRANTHES [ GRV 17 ]",
  "ウエンレラの氷華 [ GRV 17 ]",
  "キモチコネクト [ GRV 17 ]",
  "ポメグラネイト [ GRV 17 ]",
  "ロンロンへ　ライライライ！ [ GRV 17 ]",
  "０=Xerostrumental= [ EXH 17 ]",
  "2 MINUTES FIGHTERS [ EXH 17 ]",
  "akasha-assembly [ EXH 17 ]",
  "{albus} [ EXH 17 ]",
  "Aliquam [ EXH 17 ]",
  "ANTI THE∞HOLiC [ EXH 17 ]",
  "Apex of the World [ EXH 17 ]",
  "AYAKASHI [ EXH 17 ]",
  "B.B.K.K.B.K.K. [ EXH 17 ]",
  "Backflow [ EXH 17 ]",
  "BEAT-NEW-WORLD [ EXH 17 ]",
  "Borealis [ EXH 17 ]",
  "Candy Colored Hearts [ EXH 17 ]",
  "CENSORED!! [ EXH 17 ]",
  "Chant du Cygne [ EXH 17 ]",
  "Clash of swords [ EXH 17 ]",
  "conflict [ EXH 17 ]",
  "continew [ EXH 17 ]",
  "CRITICAL LINE [ EXH 17 ]",
  "cross the future [ EXH 17 ]",
  "CUTIE☆EX-DREAM [ EXH 17 ]",
  "Deadly Dolly Dance [ EXH 17 ]",
  "DIABLOSIS::Nāga [ EXH 17 ]",
  "Discloze [ EXH 17 ]",
  "Dualive [ EXH 17 ]",
  "EBONY & IVORY [ EXH 17 ]",
  "ΕΛΠΙΣ [ EXH 17 ]",
  "Emperor's Divide [ EXH 17 ]",
  "Enigma [ EXH 17 ]",
  "Everlasting Message [ EXH 17 ]",
  "F.K.S. [ EXH 17 ]",
  "False Cross [ EXH 17 ]",
  "FIRE FIRE(Kazmasa Remix) [ EXH 17 ]",
  "Follow Up [ EXH 17 ]",
  "Garakuta Doll Play [ EXH 17 ]",
  "gigadelic(m3rkAb4# R3m!x) [ EXH 17 ]",
  "Got more raves？ [ EXH 17 ]",
  "Halcyon [ EXH 17 ]",
  "Happy Sensation [ EXH 17 ]",
  "Help me, ERINNNNNN!! -Cranky remix- [ EXH 17 ]",
  "Innocent Floor [ EXH 17 ]",
  "JOMANDA [ EXH 17 ]",
  "KAC 2012 ULTIMATE MEDLEY [ EXH 17 ]",
  "Load=Crossight [ EXH 17 ]",
  "Lucky*Clover [ EXH 17 ]",
  "Mayohiga Spurt [ EXH 17 ]",
  "Metamorphobia [ EXH 17 ]",
  "NEON WORLD [ EXH 17 ]",
  "Never Fails [ EXH 17 ]",
  "Nofram [ EXH 17 ]",
  "Opium and Purple haze [ EXH 17 ]",
  "Paradission [ EXH 17 ]",
  "Parousia [ EXH 17 ]",
  "Pet Peeve [ EXH 17 ]",
  "Pieces of a Dream [ EXH 17 ]",
  "Pure Evil (Kobaryo FTN-Remix) [ EXH 17 ]",
  "REGALIA [ EXH 17 ]",
  "Rubeus [ EXH 17 ]",
  "S1CK_F41RY [ EXH 17 ]",
  "Shanghai Wu Long ～上海舞龍～ [ EXH 17 ]",
  "Stleq [ EXH 17 ]",
  "The End of War [ EXH 17 ]",
  "The Sampling Paradise (P*Light Remix) [ EXH 17 ]",
  "The setting sun [ EXH 17 ]",
  "The star in eclipse [ EXH 17 ]",
  "THUNDERCRACK [ EXH 17 ]",
  "TIEFSEE [ EXH 17 ]",
  "Time to Air -Fly High Remix- [ EXH 17 ]",
  "TOXIC VIBRATION [ EXH 17 ]",
  "Triple Counter [ EXH 17 ]",
  "Twin Rocket [ EXH 17 ]",
  "UROB&#216;ROS [ EXH 17 ]",
  "Vampire's Territory [ EXH 17 ]",
  "Virtual Bit [ EXH 17 ]",
  "Voynich:Manuscript [ EXH 17 ]",
  "Witch in Sweetsland [ EXH 17 ]",
  "Zero-Day Exploit [ EXH 17 ]",
  "アキネイション [ EXH 17 ]",
  "あれこれそれどれ [ EXH 17 ]",
  "イグジスタンス [ EXH 17 ]",
  "きらきらタイム☆ [ EXH 17 ]",
  "ゲキツイムラサ [ EXH 17 ]",
  "じゅーじゅー♥焼肉の火からフェニックス！？ ～再誕の†炭火焼き～ [ EXH 17 ]",
  "そして紫の幻想曲は全てを受け入れる [ EXH 17 ]",
  "チルノとまりおのパーフェクトさんすう教室 [ EXH 17 ]",
  "ネメシス SDVX Edit [ EXH 17 ]",
  "パ→ピ→プ→Yeah!- [ EXH 17 ]",
  "ほおずき程度には赤い頭髪 [ EXH 17 ]",
  "ホーンテッド★メイドランチ [ EXH 17 ]",
  "ぼくらしかしらない [ EXH 17 ]",
  "鬼天 [ EXH 17 ]",
  "感情の魔天楼 ～ Arr.Demetori [ EXH 17 ]",
  "雲の彼方 [ EXH 17 ]",
  "紅の剣舞 [ EXH 17 ]",
  "黒髪乱れし修羅となりて～凛 edition～ [ EXH 17 ]",
  "漆黒のスペシャルプリンセスサンデー [ EXH 17 ]",
  "雪月花 -さわわRemix- [ EXH 17 ]",
  "断罪は遍く人間の元に [ EXH 17 ]",
  "常夏！！クリスタライズ・シャーベット [ EXH 17 ]",
  "夏色DIARY -Summer Dazzlin' Vacation miX- [ EXH 17 ]",
  "人形裁判 -THIRD IMPACT- [ EXH 17 ]",
  "暴走 [ EXH 17 ]",
  "無気力クーデター [ EXH 17 ]",
  "無双 [ EXH 17 ]",
  "物凄い狂っとるフランちゃんが物凄いうた [ EXH 17 ]",
  "量子の海のリントヴルム- [ EXH 17 ]",

  "Hoshizora Illumination [ HVN 17 ]",
  "take a step forward [ HVN 17 ]",
  "幻想系世界修復少女 [ HVN 17 ]",
  "竹取飛翔 [ HVN 17 ]",
  "放課後ストライド [ HVN 17 ]",
  "Applique [ GRV 17 ]",
  "choux a la creme [ GRV 17 ]",
  "Double Universe [ GRV 17 ]",
  "Erlung [ GRV 17 ]",
  "INFINITY OVERDRIVE [ GRV 17 ]",
  "Last Battalion [ GRV 17 ]",
  "LittleGameStar [ GRV 17 ]",
  "odds and ends [ GRV 17 ]",
  "ウバワレ [ GRV 17 ]",
  "少年は空を辿る Prog Piano Remix [ GRV 17 ]",
  "雪女 [ GRV 17 ]",
  "御千手メディテーション [ INF 17 ]",
  "患部で止まってすぐ溶ける ～ 狂気の優曇華院 [ INF 17 ]",
  "打打打打打打打打打打 [ INF 17 ]",
  "BabeL ～Next Story～ [ EXH 17 ]",
  "Booths of Fighters [ EXH 17 ]",
  "CODE -CRiMSON- [ EXH 17 ]",
  "DEADLOCK XXX [ EXH 17 ]",
  "Decretum [ EXH 17 ]",
  "#FairyJoke #SDVX_Edit [ EXH 17 ]",
  "Fiat Lux [ EXH 17 ]",
  "FIRE FIRE -DARK BLAZE REMIX- [ EXH 17 ]",
  "FLYING OUT TO THE SKY [ EXH 17 ]",
  "gigadelic -stance xxxx- [ EXH 17 ]",
  "HAELEQUIN [ EXH 17 ]",
  "Harpuia [ EXH 17 ]",
  "Hellfire [ EXH 17 ]",
  "HYENA [ EXH 17 ]",
  "Idola [ EXH 17 ]",
  "Innocent Tempest [ EXH 17 ]",
  "IX [ EXH 17 ]",
  "Joyeuse [ EXH 17 ]",
  "KiLLeR MeRMaiD [ EXH 17 ]",
  "Last Concerto [ EXH 17 ]",
  "Little princess has no identity. [ EXH 17 ]",
  "Mist In Hell [ EXH 17 ]",
  "Our Faith (Faithful MTL Remix) [ EXH 17 ]",
  "Pure Evil [ EXH 17 ]",
  "Pure Evil-Aya2g Drm'n Tech Rmx- [ EXH 17 ]",
  "Quietus Ray [ EXH 17 ]",
  "Sakura Mirage [ EXH 17 ]",
  "snow storm -euphoria- [ EXH 17 ]",
  "True Blue [ EXH 17 ]",
  "U.N.オーエンは彼女なのか？haru_naba Remix [ EXH 17 ]",
  "Verse IV [ EXH 17 ]",
  "Wish upon Twin Stars [ EXH 17 ]",
  "XROSS INFECTION [ EXH 17 ]",
  "イゴモヨス＝オムルのテーマによる ブヨブヨ・スケッチの試み [ EXH 17 ]",
  "バンブーソード・ガール [ EXH 17 ]",
  "ボルテ体操第一 [ EXH 17 ]",
  "ムーニャポヨポヨスッポコニャーゴ [ EXH 17 ]",
  "朱と碧のランページ [ EXH 17 ]",
  "悪性ロリィタマキャヴェリズム [ EXH 17 ]",
  "音楽 -resolve- [ EXH 17 ]",
  "音楽 -壊音楽 mix- [ EXH 17 ]",
  "少女暴動 [ EXH 17 ]",
  "信仰は儚き人間の為に ～ Arr.Demetori [ EXH 17 ]",
  "超越してしまった彼女と其を生み落した理由 [ EXH 17 ]",
  "轟け！恋のビーンボール！！ [ EXH 17 ]",
  "柳の下のデュラハン hard chaos mix [ EXH 17 ]",

  "十面相 [ VVD 17 ]",
  "人生リセットボタン [ VVD 17 ]",
  ".59 -BOOTH BOOST REMIX- [ HVN 17 ]",
  "cloud [ HVN 17 ]",
  "Fire Strike [ HVN 17 ]",
  "Space Diver Tama [ HVN 17 ]",
  "Wheel [ HVN 17 ]",
  "イカサマライフゲイム [ HVN 17 ]",
  "ケロ⑨destiny [ HVN 17 ]",
  "サヨナラ・ヘヴン(かめりあ's NEKOMATAelectroRMX) [ HVN 17 ]",
  "セツナトリップ [ HVN 17 ]",
  "éclair au chocolat [ GRV 17 ]",
  "EGG [ GRV 17 ]",
  "freaky freak [ GRV 17 ]",
  "カミサマネジマキ [ GRV 17 ]",
  "香港功夫大旋風 [ GRV 17 ]",
  "AA BlackY mix [ INF 17 ]",
  "ALBIDA Powerless Mix [ INF 17 ]",
  "Distorted Floor [ INF 17 ]",
  "Dynasty [ INF 17 ]",
  "good high school [ INF 17 ]",
  "Gott [ INF 17 ]",
  "TYCOON [ INF 17 ]",
  "ナイト・オブ・ナイツ [ INF 17 ]",
  "天ノ弱 [ INF 17 ]",
  "過食性:アイドル症候群 [ INF 17 ]",
  "Ganymede kamome mix [ EXH 17 ]",
  "Max Burning!! [ EXH 17 ]",
  "The world of sound [ EXH 17 ]",
  "V.I.P. [ EXH 17 ]",
  "金縛りの逢を [ EXH 17 ]",
  "大宇宙ステージ [ EXH 17 ]"


];

var songlists1718 = new Array;
songlists1718 = songlists17.concat(songlists18);
xi = songlists1718.length; // 곡 갯수
xxi.innerHTML = "전체 곡 "+ xi +"곡";

function input() {
  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlists1718[Math.floor(Math.random()*(xi-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};
