        var songlists19 = [
          "2 Beasts Unchained (19)",
          "777 (19)",
          "Absurd Gaff (Metallize Remix) (19)",
          "All We Need is HAPPY END!!! (19)",
          "AμreoLe ~for Triumph~ (19)",
          "Avalanx (19)",
          "αzalea (19)",
          "Bad Elixir (19)",
          "BAYONEX (19)",
          "Breakneck Pursuit (19)",
          "Chronomia (19)",
          "CLAMARE (19)",
          "DEUX EX MĀXHINĀ (19)",
          "EncorE & cALL (19)",
          "Fαtα∠ Ent∠mEnt (19)",
          "Glory of Fighters (19)",
          "HALO (19)",
          "Holy Trail (19)",
          "[ ]DENTITY (19)",
          "LaμreLs ~the Angelus~ (19)",
          "MILITARY R04D (19)",
          "One More Lovely (19)",
          "onslaught -Retaliation of Bahamūt- (19)",
          "perditus†paradisus (19)",
          "QQ (19)",
          "Rapsodia d'amore (19)",
          "Reverenced Flower (19)",
          "Rhapsody ⚙f Triumph (19)",
          "Spectacular“V”Adventure! (19)",
          "The Clown of 24stairs (19)",
          "Undead Raving Scare (19)",
          "VALKYRIE ASSAULT (19)",
          "VΛZiLiSQ (19)",
          "VOLAQUAS (19)",
          "Xb10r (19)",
          "ZEUS (19)",
          "すべてが幻になった後で (19)",
          "ディスコルディア (19)",
          "ドゥサンコオデッセイ!! (19)",
          "ピアノ協奏曲第１番”蠍火” (19)",
          "ピアノ独奏無言歌 ”灰燼” (19)",
          "赫焉 (19)",
          "赫焉のヴァルキュリア -Ragnarok- (19)",
          "紫焔双穿 (19)",
          "十の試煉 (19)",
          "竹 (19)",
          "無意識レクイエム (cosmobsp rmx) (19)",
          "恋愛＝精度×認識力 (19)",
          "9TH5IN (19)",
          "ANGER of the GOD (19)",
          "Calamity Tempest (19)",
          "Daisycutter (19)",
          "ENDYMION (19)",
          "Ghost Family Living In Graveyard (19)",
          "Lancelot ～Flame of the Rebellion～ (19)",
          "Lisa-RICCIA (19)",
          "LubedeR (19)",
          "ΛΛemoria (19)",
          "†:OLPHEUX:† (19)",
          "OUTERHEΛVEN (19)",
          "Redshift 2nd Ignition (19)",
          "ЯeviveR (19)",
          "THE凸GENERATOR (19)",
          "Trill auf G (19)",
          "voltississimo (19)",
          "Xroniàl Xéro (19)",
          "θコトノハθカプセルθ (19)",
          "色を喪った街 (19)",
          "卑弥呼 (19)",
          "飄える翼追い掛けて (19)",
          "A Lasting Promise (19)",
          "Absolute Domination (19)",
          "Awakening (19)",
          "BELOBOG (19)",
          "Chrono Diver -PENDULUMs- (19)",
          "Cross Fire (19)",
          "Deadly force (19)",
          "Dyscontrolled Galaxy (19)",
          "Elemental Creation (19)",
          "Failnaught (19)",
          "Fin.ArcDeaR (19)",
          "Fly Like You (19)",
          "FREEDOM DiVE (19)",
          "GERBERA -For Finalists- (19)",
          "GODHEART (19)",
          "Immortal saga (19)",
          "Last Resort (19)",
          "Sailing Force (19)",
          "Staring at star (19)",
          "TWO-TORIAL (19)",
          "Xéroa (19)",
          "セイレーン ～悲壮の竪琴～ (19)",
          "逆月 (19)",
          "2 MINUTES FIGHTERS (19)",
          "EMPIRE OF FLAME (19)",
          "End to end (19)",
          "Invitation from Mr.C (19)",
          "LegenD. (19)",
          "veRtrageS (19)",
          "INF-B《L-aste-R》 (19)",
          "FLOWER (19)",
          "Got more raves？ (19)",
          "きたさいたま2000 (19)",
          "極圏 (19)",
          "ΑΩ (19)",
          "Blastix Riotz (19)",
          "DIABLOSIS::Nāga (19)",
          "Everlasting Message (19)",
          "FLügeL《Λrp:ΣggyØ》 (19)",
          "Lord=Crossight (19)",
          "Preserved Valkyria (19)",
          "XyHATTE (19)",
          "月光乱舞 (19)",
          "Fiat Lux (19)",
          "HYENA (19)",
          "Innocent Tempest (19)",
          "IX (19)",
          "ラクガキスト (19)",
          "音楽 -resolve- (19)",
          "Booths of Fighters (19)",
          "For UltraPlayers (19)",
          "INSECTICIDE (19)",
          "Quietus Ray (19)",
          "Verse IV (19)",
          "バンブーソード・ガール (19)",
          "Bangin' Burst (19)",
          "Black Emperor (19)",
          "BLACK or WHITE? (19)",
          "Growth Memories (19)",
          "snow storm -euphoria- (19)",
          "XROSS INFECTION (19)",
          "大宇宙ステージ (19)",
          "Ganymede kamome mix (19)"
      ];

      xi = songlists19.length; // 곡 갯수
      xxi.innerHTML = "전체 곡 "+ xi +"곡";

      function input() {
        $("ul").empty();
        var howmany = document.getElementById("select1").value;
          for(i=0;i<howmany;i++){
            var newDiv = document.createElement('div');
            newDiv.id = "result"+i
            var newContent = document.createTextNode(songlists19[Math.floor(Math.random()*(xi-1))]);
            newDiv.appendChild(newContent);
            document.getElementById("ul").appendChild(newDiv);
          }
        message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
        cc.innerHTML = "재추첨"

      };
