var songlists17 = [
  "[E] (17)",
  "↑↑↓↓←→←→BA (17)",
  "2094 (17)",
  "ABSOLUTE(ismK passionate remix) (17)",
  "ABSOLUTE (saminun mix) (17)",
  "Aerial Skydive (17)",
  "Aftermath (17)",
  "ASGORE / アズゴア (17)",
  "Awakening Wings (17)",
  "Berry Go!! (17)",
  "Black or Red? (17)",
  "Blue Forest(NightBounce Remix) (17)",
  "Chakra (17)",
  "charm♡you (17)",
  "Chewingood!!! (17)",
  "Chocolate Planet (いるちょこRemix) (17)",
  "Continuous Moment (17)",
  "CUDDLIE CUDDLIE (17)",
  "Dawn of Asia(Alkome Remix) (17)",
  "Death by Glamour / 華麗なる死闘 (17)",
  "Demetel (Erixa ”MYTH” Remix) (17)",
  "Devastated Territory (17)",
  "Element of SPADA (17)",
  "Empty Backdoor (17)",
  "Enter The Fire (17)",
  "eXtridia (17)",
  "fantastic dreamer (17)",
  "Flip Flap (17)",
  "Follow Tomorrow (17)",
  "Foolish Again (17)",
  "For.*tune (17)",
  "FUJIMORI -祭- FESTIVAL (17)",
  "Fun walk!! (17)",
  "GEROL (Yooh Remix) (17)",
  "Gimme dreamin' (17)",
  "Help me, ERINNNNNN!! #幻想郷ホロイズムver. (17)",
  "I Left for my Right (17)",
  "Impress(siqlo's Hi-Tech Veats) (17)",
  "Jailbreaker (17)",
  "- Jupiter - (17)",
  "LIKE A VAMPIRE (17)",
  "Lost Emotion feat. nomico (17)",
  "Love Love Scarlet (17)",
  "Lovesick Lovetune(brz_style) (17)",
  "LUCKY CAT (17)",
  "MA・TSU・RI (17)",
  "M-O-R-F-I-N-E (17)",
  "Μοῦσα (17)",
  "MOVE! (We Keep It Movin') (17)",
  "NIN-NIN-NIN!! (17)",
  "Pixelated Platform (Super Honey!) (17)",
  "PLANISPHERE (17)",
  "PRESERVED VAMPIRE (17)",
  "PRIDE of the FIREBALL (17)",
  "Re:call (17)",
  "Re:Rose Gun Shoooot! (17)",
  "Realize (17)",
  "Redo (17)",
  "Resonant Gear (17)",
  "Sakura Fubuki (17)",
  "Say!ファンファーレ! (17)",
  "Screaming!! (17)",
  "Second Game (17)",
  "SHION -sublimation mix- (17)",
  "sparky spark (17)",
  "Spear of Justice / 正義の槍 (17)",
  "Spider Dance / スパイダーダンス (17)",
  "Splash Underwater (17)",
  "Struggle for Revival (17)",
  "Verstarkt Killer (17)",
  "Virtual to LIVE (17)",
  "Whip☆Drip (17)",
  "WICKeD CRφSS (17)",
  "WILD FIRE (17)",
  "WWW (17)",
  "Xymatic Scope (17)",
  "アルファ・スカイ (17)",
  "いでぃおで結構！ (17)",
  "インドア系ならトラックメイカー (17)",
  "ヴァンパイア (17)",
  "おちゃめ機能 (17)",
  "おにけもだんす (17)",
  "おねがいダーリン (17)",
  "オリガミカル・スウィートラヴ (17)",
  "オルターエゴ (17)",
  "カシオペアノヒカリ (17)",
  "キャプテン・マリンのケツアンカー (17)",
  "キラメキ居残り大戦争 (17)",
  "キリカ (17)",
  "グッバイ宣言 (17)",
  "コントレイル (17)",
  "サクラノソバニ！ (17)",
  "シル・ヴ・プレジデント (17)",
  "スーパー戦湯ババンバーン (17)",
  "ステラ・イミグレーション (17)",
  "ステラレギア (17)",
  "スノウイコン (17)",
  "チェイスチェイスジョーカーズのうた (17)",
  "チクサクコールが懐かしい (17)",
  "デンデラパーティーナイト (17)",
  "トーキョーサマーナイト（華金Remix） (17)",
  "トランスダンスアナーキー (17)",
  "ハートシェイプ・スピカ (17)",
  "ヒトガタ (17)",
  "ヒバナ-Reloaded- (17)",
  "ぶいちゅっばの歌 (17)",
  "フェアリーテイル・ラヴァーズ (17)",
  "フォニイ (17)",
  "ポジティブ☆ダンスタイム (17)",
  "ポッピンキャンディ☆フィーバー！ (17)",
  "ポラリスノウタ (17)",
  "みたらしプラトニック (feat. nicamoq) (17)",
  "メテオライツ・プレリュード (17)",
  "メモリーズ (17)",
  "メンタンピンドラドラ (17)",
  "運命超過乃巡合 (17)",
  "朧 (17)",
  "神っぽいな (17)",
  "神にした彼女が示す世界線 (17)",
  "機械仕掛けの魔法使い (17)",
  "驪駒早鬼は馬並み☆プロテイン (17)",
  "穢れなきユーフォリア (17)",
  "月下の舞兎祭 (17)",
  "孤月群雲に沈む (17)",
  "木洩れ日に咲く (17)",
  "終点の先が在るとするならば。 (17)",
  "透明声彩 (17)",
  "泥の分際で私だけの大切を奪おうだなんて (17)",
  "叛逆のディスパレート (17)",
  "響く静寂 (17)",
  "無意識レクイエム (17)",
  "斑咲花 (17)",
  "門門しましょ (17)",
  "勇者の卒業式 (17)",
  "夢の終わり、世界のはじまり。 (17)",
  "凛として咲く花の如く (17)",
  "黎明の情 (17)",
  "恋獄対刃 (17)",
  "2 Beasts Unchained (17)",
  "777 (17)",
  "Absurd Gaff (Metallize Remix) (17)",
  "All We Need is HAPPY END!!! (17)",
  "AμreoLe ~for Triumph~ (17)",
  "and After the Merry BADEND (17)",
  "Avalanx (17)",
  "αzalea (17)",
  "BAYONEX (17)",
  "Breakneck Pursuit (17)",
  "Burst Λnd reBoost (17)",
  "Chronomia (17)",
  "Circuit Surfer (17)",
  "CLAMARE (17)",
  "DEUX EX MĀXHINĀ (17)",
  "EncorE & cALL (17)",
  "Fαtα∠ Ent∠mEnt (17)",
  "Glory of Fighters (17)",
  "HALO (17)",
  "[ ]DENTITY (17)",
  "LaμreLs ~the Angelus~ (17)",
  "MILITARY R04D (17)",
  "One More Lovely (17)",
  "onslaught -Retaliation of Bahamūt- (17)",
  "OVEЯ+TUЯE (17)",
  "perditus†paradisus (17)",
  "QQ (17)",
  "Rapsodia d'amore (17)",
  "Reverenced Flower (17)",
  "Rhapsody ⚙f Triumph (17)",
  "Spectacular“V”Adventure! (17)",
  "The Clown of 24stairs (17)",
  "Undead Raving Scare (17)",
  "VΛZiLiSQ (17)",
  "VOLAQUAS (17)",
  "Xb10r (17)",
  "ZEUS (17)",
  "すべてが幻になった後で (17)",
  "ディスコルディア (17)",
  "ドゥサンコオデッセイ!! (17)",
  "ピアノ協奏曲第１番”蠍火” (17)",
  "ピアノ独奏無言歌 ”灰燼” (17)",
  "赫焉 (17)",
  "赫焉のヴァルキュリア -Ragnarok- (17)",
  "紫焔双穿 (17)",
  "十の試煉 (17)",
  "竹 (17)",
  "恋愛＝精度×認識力 (17)",
  "120秒のエンドロール (17)",
  "50th Memorial Songs　-The BEMANI History- (17)",
  "ABSOLUTE (EUROBEAT REMIX) (17)",
  "Adrenaline Rush (17)",
  "Afterimage d'automne (17)",
  "AXION (17)",
  "Believe (y)our Wings {GRA5P WAVES} (17)",
  "Believe (y)our Wings {V:IVID RAYS} (17)",
  "Bioslaves (17)",
  "bistro twins☆☆☆ (17)",
  "BLACK JACKAL (17)",
  "BLAZE∞BREEZE (17)",
  "BLIZZARD BEAT (17)",
  "Blue Forest (Prog Keys Remix) (17)",
  "Bye or not (17)",
  "Chocolate Parade (17)",
  "Circulator (17)",
  "clear:wings (17)",
  "cloche(といぼっくすうぃんぐ　みっくす) (17)",
  "CLOUDS FLYER -sdvx edit- (17)",
  "Colorless feat.ももかみ (17)",
  "D1g1t1ze b0dy (17)",
  "DEEP PSYCHEDELIC STRIKER (17)",
  "DESIRE (17)",
  "DO-IT-AMA-SITE!!! (17)",
  "EGOISM -Rebuild- (17)",
  "empty (17)",
  "Enigma II (17)",
  "Enjoy This Time (17)",
  "floorkiller (17)",
  "Harmonia (17)",
  "Hexennacht (17)",
  "Historia of Velnoti (17)",
  "Holy Legacy (17)",
  "Impress (bansou Remix) (17)",
  "Into The Madness (17)",
  "Jetcoaster Windy (17)",
  "le coeur patissiere (17)",
  "MARENOL (17)",
  "Me:Tear (17)",
  "MICHIZURE (17)",
  "MilK (17)",
  "Mischievous theater (17)",
  "ΩBIRD (17)",
  "One In A Billion（Hedonist Remix） (17)",
  "Pixelated Platform (17)",
  "PIZZATIME (17)",
  "POSSESSION(Gowrock Remix) (17)",
  "Princess Lily (17)",
  "Quark (17)",
  "Record one's Dream (17)",
  "ЯegreT of MemoRy (17)",
  "Revolution (17)",
  "Sacrifice Escape:　不条理の模倣による感情と代償 (17)",
  "scary night (17)",
  "Sharkbait (17)",
  "Six String Proof (17)",
  "Sparkle Smilin' (17)",
  "Sparkling Laser Beam (17)",
  "Still Lonesome (17)",
  "STYX HELIX（Digi-Rock Remix） (17)",
  "Sunflower Vibes (17)",
  "The First Step (17)",
  "toy boxer (17)",
  "Tribal Trial (17)",
  "ULTRA B+K (17)",
  "ultra turbo (17)",
  "VIVID DEBUT! (17)",
  "vivid landscape (17)",
  "VIVIDWAVERS (17)",
  "who I am (17)",
  "うさぬこぬんぬんファンタジー！ (17)",
  "エンゲージ〆ント (17)",
  "おーまい！らぶりー！すうぃーてぃ！だーりん！ (17)",
  "おどりましょうよ！ドラゴンさん～転生したらゲーム曲でした～ (17)",
  "クレイジークレイジーダンサーズ (17)",
  "ここからよろしく大作戦143 (17)",
  "シープドリーミン (17)",
  "ストリーミングハート (17)",
  "ハレ トキドキ メランコリック (17)",
  "ふ・れ・ん・ど・し・た・い (WEREHEREMIX) (17)",
  "ベビーステップ (17)",
  "ぼくらの16bit戦争 (17)",
  "ゆりゆららららゆるゆり大事件（yuzen remix） (17)",
  "ラブキラ☆スプラッシュ (17)",
  "ロキ (17)",
  "伊邪那美白山姫大神 (17)",
  "悪戯センセーション (17)",
  "雲海 (17)",
  "御伽噺に幕切れを (17)",
  "革命パッショネイト (17)",
  "君は Fantasista (17)",
  "鏡面の波（ramble mix） (17)",
  "近未来百鬼夜行譚～死返之巻～ (17)",
  "逆さま♥シンデレラパレード (17)",
  "遷 (17)",
  "全力ハッピーライフ (17)",
  "太陽曰く燃えよカオス（Sol oscuro ¡Nya! Mix） (17)",
  "濁色踊るオートマタ (17)",
  "熱情のサパデアード (17)",
  "星の詩 (17)",
  "祭囃子 (17)",
  "真夏の海の修道女 (17)",
  "真夏の蜜と唇 fm. 希望の星は青霄に昇る (17)",
  "夢見草奇譚 (17)",
  "零次元エクスプレス (17)",
  "9TH5IN (17)",
  "ANGER of the GOD (17)",
  "Calamity Tempest (17)",
  "Daisycutter (17)",
  "ENDYMION (17)",
  "Ghost Family Living In Graveyard (17)",
  "Lancelot ～Flame of the Rebellion～ (17)",
  "Lisa-RICCIA (17)",
  "LubedeR (17)",
  "ΛΛemoria (17)",
  "†:OLPHEUX:† (17)",
  "OUTERHEΛVEN (17)",
  "Redshift 2nd Ignition (17)",
  "ЯeviveR (17)",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY (17)",
  "THE凸GENERATOR (17)",
  "Trill auf G (17)",
  "voltississimo (17)",
  "Xroniàl Xéro (17)",
  "θコトノハθカプセルθ (17)",
  "色を喪った街 (17)",
  "卑弥呼 (17)",
  "飄える翼追い掛けて (17)",
  "3y3s (JMBS FUNKOT RMX) (17)",
  "405nm(Shu※mix) (17)",
  "444 (17)",
  "All Clear!! (17)",
  "Altale (17)",
  "Another Chapter (17)",
  "Apocrypha (17)",
  "Aragami (17)",
  "Arcade Prison (17)",
  "β (17)",
  "Blue Stream (17)",
  "BREAKNECK NY☆N! NY★N! (17)",
  "CARNIVOROUS (17)",
  "Carry Me Away (17)",
  "Chaotic Romance (17)",
  "Chocolate Planet (17)",
  "cobalt (17)",
  "Coldlapse (17)",
  "CUTE-Reflection (17)",
  "Cy-Bird (17)",
  "Dark Matter (17)",
  "Decoy (17)",
  "Destruction & Qreation (17)",
  "Dharma (17)",
  "Dreaming feat.nomico (17)",
  "Drizzly Venom (17)",
  "EDEN of TRUTH (17)",
  "Empathetic (17)",
  "Fáfnir (17)",
  "Far Away (17)",
  "Finale (17)",
  "Fly far bounce (17)",
  "Four Leaves (17)",
  "Game Over (17)",
  "Heavenly Adventure (17)",
  "HEAVENLY SMILE (17)",
  "If (17)",
  "ILL-STARRED Diver (17)",
  "infinite:youniverse (17)",
  "Inscape (17)",
  "Invisible Bullets (17)",
  "Iridescent Clouds (17)",
  "JUGGLE (17)",
  "JULIAN (17)",
  "Junk Mania (17)",
  "Justitia Gladius (17)",
  "Knights Assault (17)",
  "Libera me (17)",
  "Liévre -blanche- (17)",
  "Life is beautiful (17)",
  "Line 4 Ruin -kohumix- (17)",
  "Lost Wing at.0 (17)",
  "Made In Love (17)",
  "MAXIVCORD (17)",
  "Melty Sweets (17)",
  "Musha Vibration (17)",
  "NEON LOVE♥POTION!!! (17)",
  "No way (17)",
  "Oriens (17)",
  "Phlox (17)",
  "PIERROT KNIfE (17)",
  "planetarium (17)",
  "Poison AND÷OR Affection (17)",
  "Poppin’Cats!! (17)",
  "QUAKE (17)",
  "Rebuilding of Paradise Lost (17)",
  "Rejoin (17)",
  "rhythmology study (17)",
  "Royal Action (17)",
  "Royal Judgement (17)",
  "Sadistic Stabbing (17)",
  "Sakura Mirage -Drum'n World- (17)",
  "Secret Traveler -MeniRemix- (17)",
  "sink into the dream (17)",
  "Sleepless days (17)",
  "Smoked Turkey Rag (17)",
  "SPACE VILLAGE (17)",
  "Sulk (17)",
  "SUPER BUBBLE JOURNEY (17)",
  "Synergy For Angels (17)",
  "Technical Master (17)",
  "Tic Exe (17)",
  "Twilight ∞ nighT (17)",
  "Vigor (17)",
  "Voltage Higher (17)",
  "VOLTEXES IV (17)",
  "WONDER_WOBBLER (17)",
  "Xibercannon (17)",
  "Zelophilia (17)",
  "アワデコノヨヲ (17)",
  "アンハッピーリフレイン (17)",
  "インビジブル (17)",
  "おにいちゃんハイテック (17)",
  "オンディーヌの泪 (17)",
  "ケムマキ underground (17)",
  "ゴーストルール (17)",
  "コメット⇒スケイター (17)",
  "すろぉもぉしょん (17)",
  "セイシュンライナー (17)",
  "それは花火のような恋 (17)",
  "ツキアカリ (17)",
  "デュアルメモリ (17)",
  "ブチ上げ候！現代忍者三姉妹 (17)",
  "プラネタジャーニー (17)",
  "プレインエイジア(MRM REMIX) (17)",
  "ペタ靴と憂夜リムーバー (17)",
  "ボーイミーツ・ブルー (17)",
  "メルヘン風紀委員会 (17)",
  "ラキラキ (17)",
  "ロプノールの商隊 (17)",
  "炎夏の音 (17)",
  "煙 (17)",
  "獅子奮迅 (17)",
  "失敗作少女 (17)",
  "銃弾は解を撃ち抜いて (17)",
  "少女綺想曲 -G.X.N. Remix- (17)",
  "水槽のクジラ (17)",
  "星座が恋した瞬間を。 (17)",
  "零の位相 (17)",
  "創世ノート (17)",
  "廃獄ドリームランド (17)",
  "片翼のディザイア (17)",
  "蓬莱フェスティボー (17)",
  "僕らの時間 (17)",
  "焔 -MAGMA- (17)",
  "見世物ライフ (17)",
  "蟲の棲む処 (17)",
  "物凄いスペースシャトルでこいしが物凄いうた (17)",
  "幽玄の桜 (17)",
  "闇夜に舞うは紅の華 (17)",
  "羅生門 (17)",
  "黎明スケッチブック (17)",
  "分けるな危険！モモモモモモーイズム (17)",
  "A Lasting Promise (17)",
  "Absolute Domination (17)",
  "Awakening (17)",
  "BELOBOG (17)",
  "Chrono Diver -PENDULUMs- (17)",
  "Cross Fire (17)",
  "Deadly force (17)",
  "Dyscontrolled Galaxy (17)",
  "Elemental Creation (17)",
  "Failnaught (17)",
  "FLOOR INFECTION Medley　from SOUND VOLTEX×jubeat (17)",
  "Fly Like You (17)",
  "FREEDOM DiVE (17)",
  "GERBERA -For Finalists- (17)",
  "GODHEART (17)",
  "HE4VEN ～天国へようこそ～ (17)",
  "iLLness LiLin (17)",
  "Last Resort (17)",
  "Rebellio (17)",
  "Sailing Force (17)",
  "Staring at star (17)",
  "TWO-TORIAL (17)",
  "Xéroa (17)",
  "セイレーン ～悲壮の竪琴～ (17)",
  "逆月 (17)",
  "超☆超☆光☆速☆出☆前☆最☆速!!!　スピード★スター★かなで (17)",
  "Din Don Dan (Fusion Remix) (17)",
  "バイナリスター (17)",
  "ヒミツダイヤル (17)",
  "Destroy (17)",
  "Get back here (17)",
  "Grand Chariot (17)",
  "INDEPENDENT SKY (17)",
  "Inixia (17)",
  "Sephirot (17)",
  "StrayedCatz (17)",
  "ZEPHYRANTHES (17)",
  "ウエンレラの氷華 (17)",
  "キモチコネクト (17)",
  "ポメグラネイト (17)",
  "ロンロンへ　ライライライ！ (17)",
  "０=Xerostrumental= (17)",
  "2 MINUTES FIGHTERS (17)",
  "akasha-assembly (17)",
  "{albus} (17)",
  "Aliquam (17)",
  "ANTI THE∞HOLiC (17)",
  "Apex of the World (17)",
  "AYAKASHI (17)",
  "B.B.K.K.B.K.K. (17)",
  "Backflow (17)",
  "BEAT-NEW-WORLD (17)",
  "Borealis (17)",
  "Candy Colored Hearts (17)",
  "CENSORED!! (17)",
  "Chant du Cygne (17)",
  "Clash of swords (17)",
  "conflict (17)",
  "continew (17)",
  "CRITICAL LINE (17)",
  "cross the future (17)",
  "CUTIE☆EX-DREAM (17)",
  "Deadly Dolly Dance (17)",
  "DIABLOSIS::Nāga (17)",
  "Discloze (17)",
  "Dualive (17)",
  "EBONY & IVORY (17)",
  "ΕΛΠΙΣ (17)",
  "Emperor's Divide (17)",
  "Enigma (17)",
  "Everlasting Message (17)",
  "F.K.S. (17)",
  "False Cross (17)",
  "FIRE FIRE(Kazmasa Remix) (17)",
  "Follow Up (17)",
  "Garakuta Doll Play (17)",
  "gigadelic(m3rkAb4# R3m!x) (17)",
  "Got more raves？ (17)",
  "Halcyon (17)",
  "Happy Sensation (17)",
  "Help me, ERINNNNNN!! -Cranky remix- (17)",
  "Innocent Floor (17)",
  "JOMANDA (17)",
  "KAC 2012 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- (17)",
  "Lord=Crossight (17)",
  "Lucky*Clover (17)",
  "Mayohiga Spurt (17)",
  "Metamorphobia (17)",
  "NEON WORLD (17)",
  "Never Fails (17)",
  "Nofram (17)",
  "Opium and Purple haze (17)",
  "Paradission (17)",
  "Parousia (17)",
  "Pet Peeve (17)",
  "Pieces of a Dream (17)",
  "Pure Evil (Kobaryo FTN-Remix) (17)",
  "REGALIA (17)",
  "Rubeus (17)",
  "S1CK_F41RY (17)",
  "Shanghai Wu Long ～上海舞龍～ (17)",
  "Stleq (17)",
  "The End of War (17)",
  "The Sampling Paradise (P*Light Remix) (17)",
  "The setting sun (17)",
  "The star in eclipse (17)",
  "THUNDERCRACK (17)",
  "TIEFSEE (17)",
  "Time to Air -Fly High Remix- (17)",
  "TOXIC VIBRATION (17)",
  "Triple Counter (17)",
  "Twin Rocket (17)",
  "UROBØROS (17)",
  "Vampire's Territory (17)",
  "Virtual Bit (17)",
  "Voynich:Manuscript (17)",
  "Witch in Sweetsland (17)",
  "Zero-Day Exploit (17)",
  "アキネイション (17)",
  "あれこれそれどれ (17)",
  "イグジスタンス (17)",
  "きらきらタイム☆ (17)",
  "ゲキツイムラサ (17)",
  "じゅーじゅー♥焼肉の火からフェニックス！？　～再誕の†炭火焼き～ (17)",
  "そして紫の幻想曲は全てを受け入れる (17)",
  "チルノとまりおのパーフェクトさんすう教室 (17)",
  "ネメシス SDVX Edit (17)",
  "パ→ピ→プ→Yeah! (17)",
  "ほおずき程度には赤い頭髪 (17)",
  "ホーンテッド★メイドランチ (17)",
  "ぼくらしかしらない (17)",
  "鬼天 (17)",
  "感情の魔天楼 ～ Arr.Demetori (17)",
  "雲の彼方 (17)",
  "紅の剣舞 (17)",
  "黒髪乱れし修羅となりて～凛 edition～ (17)",
  "漆黒のスペシャルプリンセスサンデー (17)",
  "雪月花 -さわわRemix- (17)",
  "断罪は遍く人間の元に (17)",
  "常夏！！クリスタライズ・シャーベット (17)",
  "夏色DIARY -Summer Dazzlin' Vacation miX- (17)",
  "人形裁判 -THIRD IMPACT- (17)",
  "暴走 (17)",
  "無気力クーデター (17)",
  "無双 (17)",
  "物凄い狂っとるフランちゃんが物凄いうた (17)",
  "量子の海のリントヴルム (17)",
  "ネトゲ廃人シュプレヒコール (17)",
  "マネマネサイコトロピック (17)",
  "Hoshizora Illumination (17)",
  "take a step forward (17)",
  "幻想系世界修復少女 (17)",
  "竹取飛翔 (17)",
  "放課後ストライド (17)",
  "Appliqué (17)",
  "choux à la crème (17)",
  "Double Universe (17)",
  "Erlung (17)",
  "INFINITY OVERDRIVE (17)",
  "Last Battalion (17)",
  "LittleGameStar (17)",
  "odds and ends (17)",
  "ウバワレ (17)",
  "少年は空を辿る Prog Piano Remix (17)",
  "雪女 (17)",
  "御千手メディテーション (17)",
  "患部で止まってすぐ溶ける ～ 狂気の優曇華院 (17)",
  "打打打打打打打打打打 (17)",
  "BabeL ～Next Story～ (17)",
  "Booths of Fighters (17)",
  "CODE -CRiMSON- (17)",
  "DEADLOCK XXX (17)",
  "Decretum (17)",
  "#FairyJoke #SDVX_Edit (17)",
  "Fiat Lux (17)",
  "FIRE FIRE -DARK BLAZE REMIX- (17)",
  "FLYING OUT TO THE SKY (17)",
  "gigadelic -stance xxxx- (17)",
  "HAELEQUIN (17)",
  "Harpuia (17)",
  "Hellfire (17)",
  "HYENA (17)",
  "Idola (17)",
  "Innocent Tempest (17)",
  "IX (17)",
  "Joyeuse (17)",
  "KiLLeR MeRMaiD (17)",
  "Last Concerto (17)",
  "Little princess has no identity. (17)",
  "Mist In Hell (17)",
  "Our Faith (Faithful MTL Remix) (17)",
  "Pure Evil (17)",
  "Pure Evil-Aya2g Drm'n Tech Rmx- (17)",
  "Quietus Ray (17)",
  "Sakura Mirage (17)",
  "snow storm -euphoria- (17)",
  "True Blue (17)",
  "U.N.オーエンは彼女なのか？haru_naba Remix (17)",
  "Verse IV (17)",
  "Wish upon Twin Stars (17)",
  "XROSS INFECTION (17)",
  "イゴモヨス＝オムルのテーマによる　ブヨブヨ・スケッチの試み (17)",
  "バンブーソード・ガール (17)",
  "ボルテ体操第一 (17)",
  "ムーニャポヨポヨスッポコニャーゴ (17)",
  "朱と碧のランページ (17)",
  "悪性ロリィタマキャヴェリズム (17)",
  "音楽 -resolve- (17)",
  "音楽 -壊音楽 mix- (17)",
  "少女暴動 (17)",
  "信仰は儚き人間の為に ～ Arr.Demetori (17)",
  "超越してしまった彼女と其を生み落した理由 (17)",
  "轟け！恋のビーンボール！！ (17)",
  "柳の下のデュラハン hard chaos mix (17)",
  "Grip & Break down !! - SDVX Edit. - (17)",
  "Hello world! (17)",
  "smooooch・∀・ KN mix (17)",
  "SOUL EXPLOSION (17)",
  "色は匂へど散りぬるを (17)",
  "地球最後の告白を (17)",
  "十面相 (17)",
  "人生リセットボタン (17)",
  ".59 -BOOTH BOOST REMIX- (17)",
  "cloud (17)",
  "Fire Strike (17)",
  "Space Diver Tama (17)",
  "Wheel (17)",
  "イカサマライフゲイム (17)",
  "ケロ⑨destiny (17)",
  "サヨナラ・ヘヴン　(かめりあ's NEKOMATAelectroRMX) (17)",
  "セツナトリップ (17)",
  "éclair au chocolat (17)",
  "EGG (17)",
  "freaky freak (17)",
  "カミサマネジマキ (17)",
  "香港功夫大旋風 (17)",
  "AA BlackY mix (17)",
  "ALBIDA Powerless Mix (17)",
  "Distorted Floor (17)",
  "Dynasty (17)",
  "good high school (17)",
  "Gott (17)",
  "TYCOON (17)",
  "ナイト・オブ・ナイツ (17)",
  "天ノ弱 (17)",
  "過食性:アイドル症候群 (17)",
  "Ganymede kamome mix (17)",
  "Max Burning!! (17)",
  "The world of sound (17)",
  "V.I.P. (17)",
  "金縛りの逢を (17)",
  "大宇宙ステージ (17)"
];

var songlists18 = [
  "Across the Starlight (18)",
  "AIM HIGHER (18)",
  "Air (18)",
  "All for One (18)",
  "Amazing Mirage (18)",
  "Archangelio (18)",
  "Battle Against a True Hero / 本物のヒーローとの戦い (18)",
  "Bigbang Faker (18)",
  "birth (18)",
  "BLISS (18)",
  "Blossom (18)",
  "Brave Power Leader 《 = Voltage = 》 (18)",
  "c2Theater (18)",
  "CadenzaMaiden (18)",
  "Cappuccino Hearts (18)",
  "Chat perché (18)",
  "€omet popcorn (18)",
  "Corrupting Wonderland (18)",
  "Crystalia (18)",
  "D.I.X. (18)",
  "DATAERR0R (18)",
  "Decadence Mission (18)",
  "Destined Marionette (18)",
  "Destr0yer (18)",
  "Distorted Floor -Boosted- (18)",
  "EGOISM 440 (Ange;art remix) (18)",
  "Elemental Creation -xiRemix- (18)",
  "EMERALDAS (Yuta Imai Remix) (18)",
  "ΣMERGENCY CODΣ (18)",
  "#EmoCloche (18)",
  "End of Guilty (18)",
  "ENDGAME (18)",
  "ENERGY SYNERGY MATRIX (18)",
  "Enter The Rave (18)",
  "FAR GONE (18)",
  "FEEL THE FORCE (18)",
  "Fegrix (18)",
  "Finale / フィナーレ (18)",
  "Fl0ating: (18)",
  "G4ME OVEЯ (18)",
  "Garland (18)",
  "Going My Future! (18)",
  "GOODTEK (18)",
  "graduation (18)",
  "Grandeur (18)",
  "Halloween Is Chaos (18)",
  "Hello, Hologram (18)",
  "Hurt me plenty (18)",
  "Hydroblast (18)",
  "Ice Fortress (18)",
  "Imperator (18)",
  "Initiating League (18)",
  "Innocent Azure (18)",
  "Juωpscare!! (18)",
  "KAMAITACHI (18)",
  "KINGWORLD (18)",
  "Kontrol Line (18)",
  "Lost Parliament (18)",
  "Macuilxochitl (Latin Jazz Mix) (18)",
  "Marielle (18)",
  "MEGALOVANIA (18)",
  "Memory Flow (18)",
  "Metagame Matador (18)",
  "MURASAME (18)",
  "ИADIR (18)",
  "#Namescapes (18)",
  "Never Ending Future (18)",
  "=∴NOMADE∵OTION= (18)",
  "nostos -ark remix- (18)",
  "NOT YOUR IDOL (18)",
  "ØƵ (18)",
  "Paradigm Shift (18)",
  "party:stage (18)",
  "Perfect Ultimate Celebration!! (18)",
  "Petit espoir (18)",
  "PHOTON BLAXT (18)",
  "Please Welcome Mr.C (18)",
  "POSSESSION (Aoi Q.E.D. RMX) (18)",
  "Prayer (18)",
  "PSYCHO+HEROES (18)",
  "Puni Puni Parade (18)",
  "Pure Ruby (18)",
  "quaver♪ (18)",
  "R.I.P.ゴシップの海 (18)",
  "Red＋White＝Kawaii (18)",
  "refluxio (18)",
  "Refrain (18)",
  "Restless Waitress (18)",
  "Revvable Engine (18)",
  "ROZELCIA (18)",
  "SAVE the World (18)",
  "Sayonara Planet Wars (Sot-C Remix) (18)",
  "Scars of FAUNA(ろひ Remix) (18)",
  "Scat Jazz Dance (18)",
  "SHARK ATTACK (18)",
  "SHARK IMPACT (18)",
  "Shera (18)",
  "SHOCKER BREAKER (18)",
  "Snowmelt (18)",
  "Souhait bleu (18)",
  "SPECIAL SUMMER CAMPAIGN! (18)",
  "Stairway to the sun (18)",
  "Star☆Beat (18)",
  "S(TAR)²☆pistol (18)",
  "STEEL NEEDLE (18)",
  "stellar rain (18)",
  "STIGMA (18)",
  "Stylus (18)",
  "SuperMiracleEnsemble (18)",
  "suspicions (18)",
  "Test Flight (18)",
  "The EXworld of sound (18)",
  "The King Of Red (18)",
  "THE PEERLESS UNDER HEAVEN (18)",
  "THE WORLD REVOLVING (18)",
  "Thousand Triggers (18)",
  "Tickled Pink (18)",
  "TOKAKU=ALMiRAJ (18)",
  "trea→journey (18)",
  "Triple Cross (18)",
  "Twinkle Rookie (18)",
  "Unleashed Redness (18)",
  "Vallasotiena (18)",
  "Vanishing Eidos (18)",
  "Verflucht (18)",
  "Voice 7 Voice!!!!!!! (18)",
  "WARNING×WARNING×WARNING (18)",
  "Welcome to the Mosh Pit (18)",
  "White Stream (18)",
  "Wings to fly high (18)",
  "WINNING ROAD (18)",
  "XXanadu#climaXX (18)",
  "Your SOUL Is Mine (18)",
  "Zero-Day Exploit(One-Day Fusion Mix) (18)",
  "あいあむなんばーわんパトラちゃん様 (18)",
  "アガット (18)",
  "アンチグラビティ・ガール (18)",
  "イグノアザーズ (18)",
  "うぇるかむ -||祭みっくす||- (18)",
  "ゔぉるみっくす!!!! (18)",
  "カジノファイヤーことみちゃん (18)",
  "スカーレット警察のゲットーパトロール24時 (18)",
  "ちくわパフェだよ☆ＣＫＰ (Yvya Remix) (18)",
  "ドリームエンド・サバイバー(Hidra-Xjeil Remix) (18)",
  "ナミカレ (18)",
  "パーフェクトイーター (18)",
  "ハッピーエンド (18)",
  "ばらんが!!!! (18)",
  "プナイプナイたいそう (18)",
  "フリコドウル (18)",
  "ホイホイ☆幻想ホロイズム (18)",
  "ませまてぃっく♡ま＋ま＝まじっく！～徹夜の追込みエナジーまっくす！～ (18)",
  "マツヨイナイトバグ (18)",
  "まみむめ🍄まるっと🍄まっしゅるーむ🍄🍄 (18)",
  "めうめうぺったんたん！！ (ZAQUVA Remix) (18)",
  "ユメブキ (18)",
  "ラヴ♡チャンス!! (18)",
  "りむむむむむむ (18)",
  "リュミレイラ (18)",
  "リリーゼと炎龍レーヴァテイン (18)",
  "レインボウ・フレーバー (18)",
  "藍の華 (18)",
  "過去に囚われている (18)",
  "過去を喰らう (18)",
  "随神 (18)",
  "光風霽月 (18)",
  "極夜、暁を望んで (18)",
  "劇場版ムーニャポヨポヨスッポコニャーゴ~侵略だいず帝国！ドラマティック宇宙大戦争~ (18)",
  "限界突破リザレクション (18)",
  "～仔羊のナヴァラン・クリシェを添えて～ (18)",
  "最果ての勇者にラブソングを (18)",
  "十三不塔 (18)",
  "灼ナル刃、破カヰ譜 (18)",
  "少年リップルズ (18)",
  "蝕 (18)",
  "神罰 (18)",
  "天弓天華オトハナビ (18)",
  "天穹のアルカナビット (18)",
  "涙の女神と無形のエトワル (18)",
  "二分間の世界 (18)",
  "儚キ戀ノ幻想譚 (18)",
  "爆烈歓迎♪エクストリーム飲茶旋風脚ッ!! (18)",
  "緋色月下、狂咲ノ絶 (nayuta 2017 ver) (18)",
  "火狐之舞 (18)",
  "禊 (18)",
  "夢幻泡影 (18)",
  "累乗のカルマ (18)",
  "零天視 (18)",
  "恋愛♡悪戯！？まじかる☆ぱふゅ～む！！ (18)",
  "忘れないように、失くさないように (18)",
  "Λkasha (18)",
  "APØCALYPSE RAY (18)",
  "Bl∞min' (18)",
  "HeaveИ's Rain (18)",
  "MixxioN (18)",
  "《Re:miniscence》 (18)",
  "SuddeИDeath (18)",
  "XHRONOXAPSULΞ (18)",
  "You Are My Best RivaL!! (18)",
  "いまきみに (18)",
  "Φnd:you (18)",
  "Aerial Fortress (18)",
  "apo:llioth (18)",
  "ARROW RAIN (18)",
  "Atropa bella-donna (18)",
  "Aurolla (18)",
  "Barbatos (18)",
  "Barbless Ego (18)",
  "Believe In Yourself (18)",
  "Black Lotus (18)",
  "Blessing Bouquet (18)",
  "Bolérrot (18)",
  "Butterfly Twist (18)",
  "Call of the World (18)",
  "Cloud Crasher (18)",
  "Cynical Joker (18)",
  "Defining Future (18)",
  "Dogeza Stairs (18)",
  "eighth-slave (18)",
  "Electric Injury (18)",
  "Elemental Creation (kamome sano Remix) (18)",
  "Enchanté (18)",
  "eternite (18)",
  "Ethereal Lotus (18)",
  "FIRST：DREAMS (18)",
  "GALAXY BURST (18)",
  "GaLaXyEggPlanT (18)",
  "GEMINI LA2ER (18)",
  "Glorious Journey (18)",
  "Ichi-Go! DX Pancake! (18)",
  "Innocent (18)",
  "Jack-the-Ripper◆ (18)",
  "Jacob’s Elevator (18)",
  "JǛPITΨR ♃ GЯÃVITÝ (18)",
  "Katharsis (18)",
  "L9 (18)",
  "Lazurite (18)",
  "LECTORIA (18)",
  "Leviathan (18)",
  "lEyl (18)",
  "Liar rain (18)",
  "m1dy Deluxe (18)",
  "memento mori -intro- (18)",
  "METATRON (18)",
  "MeteorA (18)",
  "mqlo (18)",
  "Mynarco(Nagomu 2Step Remix) (18)",
  "Nebulas (18)",
  "New Decade (18)",
  "Nhelv (18)",
  "On take SUN (18)",
  "Our Love (18)",
  "Over The Top (18)",
  "ΩVERFLOW (18)",
  "OZONE (18)",
  "PARTY TIME! (18)",
  "petits fours (18)",
  "pique (18)",
  "Pulsar (18)",
  "Re：Elemental Creation (18)",
  "Яe:son D'être (18)",
  "rE:Voltagers (18)",
  "Ring!Run!Nyan!! (18)",
  "SAMURAI TIGER (18)",
  "SLEEPWALKER (18)",
  "SociuS (18)",
  "Sudden Visitor (18)",
  "Symphonic Tear (18)",
  "Teufel (18)",
  "Thank you for your playing music (18)",
  "To:BrandNewDeadline (18)",
  "Turn the story (18)",
  "Typhoon Craaash!! (18)",
  "Übertreffen (18)",
  "V Sen5eS (18)",
  "Valanga(polysha Remix) (18)",
  "Valkyrja ~Aldrlag~ (18)",
  "Vividly Impromptu (18)",
  "With It This Heaven? (18)",
  "World of Iris (18)",
  "Xicholauncher (18)",
  "ZEИITH (18)",
  "αρχη (18)",
  "アオアラシ (18)",
  "おはようからおやすみまでかまってポメポメ (18)",
  "タイムトラベル (18)",
  "ツマミ戦隊 タテレンジャー (18)",
  "トマヨイ (18)",
  "ねこみみ(=ФωФ=)ぱんでみみっく (18)",
  "び (18)",
  "プログレなぞなぞクイズのテーマ (18)",
  "ミッドナイト☆WAR (18)",
  "ミュージックプレイヤー (18)",
  "ランカーキラーガール (18)",
  "怪盗Ｆの台本～消えたダイヤの謎～ (18)",
  "蛇神 (18)",
  "月々紅花 (18)",
  "狂水一華 (18)",
  "最小三倍完全数 (18)",
  "消失(Hommarju Remix) (18)",
  "翠雨の祷 (18)",
  "諏訪大信仰 (18)",
  "世界の果てに約束の凱歌を -VOLTEX Mix- (18)",
  "春告胡蝶 (18)",
  "星の透る夏空に願う (18)",
  "無魎大数 (18)",
  "666 (18)",
  "ΣgØ (18)",
  "* Erm, could it be a Spatiotemporal　ShockWAVE Syndrome...? (18)",
  "MAYHEM (18)",
  "VVelcome!! (18)",
  "Akzeriyyuth (18)",
  "ALTONA (18)",
  "Be a Hero! (18)",
  "BEAST BASS BOMB (18)",
  "Beyond the BLUE (18)",
  "Black night (18)",
  "BLAZING_LAZER (18)",
  "BlueMoon Princess (18)",
  "Boss Rush (18)",
  "Breakin' Asia (18)",
  "Catch Our Fire! (18)",
  "Cepheus (18)",
  "CHERNOBOG (18)",
  "Cloud 9 (18)",
  "Concertino in Blue (18)",
  "crossing blue (18)",
  "Destiny (18)",
  "Divine's:Bugscript (18)",
  "Divine's or Deal (18)",
  "Doppelganger (18)",
  "Dreadnought (18)",
  "DropZ-Line- (18)",
  "ECHIDNA (18)",
  "Evans (18)",
  "FIRE IN MY HEART (18)",
  "FLOOR INFECTION Medley　from SOUND VOLTEX×jubeat (18)",
  "GAIA (18)",
  "Gamerz FestivaL (18)",
  "Gate of Atlantis (18)",
  "GERBERA (18)",
  "Ghost Trigger (18)",
  "Glitter Flatter Scatter (18)",
  "Goddess Bless you (18)",
  "Gorgetech (18)",
  "Grand-Guignol (18)",
  "HP:1 (18)",
  "Hug!! Vs. Hug!! (18)",
  "ΗУМЛ (18)",
  "Juggler's Maddness (18)",
  "JUNKIE FLAVOR (18)",
  "Khionos TiARA (18)",
  "KIMIDORI Streak!! (18)",
  "LastΩmegA (18)",
  "Legendary Road (18)",
  "Levier'n NābYss (18)",
  "Lowermost revolt (18)",
  "Lunatic Sprinter (18)",
  "Make Magic (18)",
  "MeteorGlow Aftermath (18)",
  "Midnight City Warfare (18)",
  "Mirrorwall (18)",
  "MODEL FT4 (18)",
  "MONOLITH (18)",
  "New Leaf (18)",
  "Nexta (18)",
  "Night Rockin' Bird (18)",
  "Noisy Minority (18)",
  "Nostalgic Blood of the Strife (18)",
  "OPEN MY GATE (18)",
  "ouroboros -twin stroke of the end- (18)",
  "ΩVERSOUL (18)",
  "POLICY BREAK Medley　from SOUND VOLTEX×jubeat (18)",
  "Prey (18)",
  "PROVOES*PROPOSE <<êl fine>> (18)",
  "Puberty Dysthymia (18)",
  "PUPA (18)",
  "Re:End of a Dream (18)",
  "Яe's NoVǢ (18)",
  "Rebellio (18)",
  "Reb∞t (18)",
  "REDO the NIGHT (18)",
  "Redshift (18)",
  "RHYZING BEAT (18)",
  "Sacrifice and Faith (18)",
  "SACRIFICE feat.ayame (18)",
  "SAtAN (18)",
  "Scarlet Lance (18)",
  "She Turns Me On (18)",
  "Sky High (18)",
  "#SpeedyCats (18)",
  "Spirit of the Beast (18)",
  "STULTI (18)",
  "SUPER SUMMER SALE (18)",
  "Sweet Requiem (18)",
  "Taiko Drum Monster (18)",
  "The Formula (18)",
  "The Golden Era (18)",
  "THE HEAVEN (18)",
  "Theme of Ricerca (18)",
  "Touch My Body (18)",
  "TRICKL4SH 220 (18)",
  "ULTiMATE INFLATiON (18)",
  "ULTRAVELOCITY (18)",
  "V (18)",
  "Venomous Firefly (18)",
  "Victim of Nights (18)",
  "We Go Down (18)",
  "Wings of Glory (18)",
  "Xevel (18)",
  "Yum Yum Sweetie (18)",
  "お米の美味しい炊き方、　そしてお米を食べることによるその効果。 (18)",
  "オニユリ (18)",
  "キュリオシティ (18)",
  "サイコパスラビット (18)",
  "スラッシュ//シスターズ (18)",
  "セイクリッド ルイン (18)",
  "そして黄金郷へ (18)",
  "ドリームエンド・サバイバー (18)",
  "のぼれ八坂坂！ (18)",
  "びいすと！ (18)",
  "ファイナルレター (18)",
  "ホワイトパレード (18)",
  "まじかる生主＠りすなちゃん (18)",
  "メイビ～初恋！？ビスケット☆大作戦 (18)",
  "ワールズエンド・ダンスホール (18)",
  "怒槌 (18)",
  "永遠に幸せになる方法、見つけました。 (18)",
  "壊Rave*it!! 壊Rave*it!! (18)",
  "神獄烙桜 (18)",
  "恋歌疾風！かるたクイーンいろは (18)",
  "業焔繚乱 (18)",
  "極彩天奏 (18)",
  "祝福の色彩は想い結ぶ君たち迄 (18)",
  "準備運動 (18)",
  "神話に芽吹く (18)",
  "水簾ノ調 (18)",
  "誰が為に兎は舞う＝狂速狂騒曲＝ (18)",
  "超☆超☆光☆速☆出☆前☆最☆速!!!　スピード★スター★かなで (18)",
  "†渚の小悪魔ラヴリィ～レイディオ† (18)",
  "光射す澪のユズリハ (18)",
  "真っ白な靴 (18)",
  "雷鼓サンダービート (18)",
  "ΣmbryØ (18)",
  "*Feels Seasickness...* (18)",
  "FIN4LE ～終止線の彼方へ～ (18)",
  "Fin.ArcDeaR (18)",
  "I (18)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Empress Side (18)",
  "WHITEOUT (18)",
  "Xronièr (18)",
  "B.B.K.K.B.K.K. (18)",
  "Candy Colored Hearts (18)",
  "Le Fruit Défendu (18)",
  "NEO GRAVITY (18)",
  "The Sampling Paradise (P*Light Remix) (18)",
  "The star in eclipse (18)",
  "ちくわパフェだよ☆ＣＫＰ (18)",
  "雲の彼方 (18)",
  "Garakuta Doll Play (18)",
  "Angelic Jelly (18)",
  "Celestial stinger (18)",
  "Completeness Under Incompleteness (18)",
  "HAELE III ~Angel Worlds~ (18)",
  "KAC 2012 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- (18)",
  "NEO TREASON (18)",
  "Ok!! Hug Me (18)",
  "Opium and Purple haze (18)",
  "Renegade Fruits (18)",
  "Triple Counter (18)",
  "XROSS THE XOUL (18)",
  "↓↓↓ (18)",
  "ΑΩ (18)",
  "Angels And Demons (18)",
  "Blastix Riotz (18)",
  "Demise Quartet (18)",
  "EMPIRE OF FLAME (18)",
  "#Endroll (18)",
  "End to end (18)",
  "Endless GRAVITY (18)",
  "Firestorm (18)",
  "FLOWER (18)",
  "FLügeL《Λrp:ΣggyØ》 (18)",
  "Fox4-Raize- (18)",
  "GEOMETRIA (18)",
  "gigadelic (かめりあ's ''The TERA'' RMX) (18)",
  "HAVOX (18)",
  "IKAROS DYNAMITE!!!! (18)",
  "INF-B《L-aste-R》 (18)",
  "Invitation from Mr.C (18)",
  "JEHANNEDARC (18)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side (18)",
  "Lachryma《Re:Queen'M》 (18)",
  "LegenD. (18)",
  "MG277 (18)",
  "NEO GRAVITY (18)",
  "Ops:Code-Rapture- (18)",
  "Pon-Pon-Pompoko Dai-Sen-Saw! (18)",
  "Prayer (18)",
  "Preserved Valkyria (18)",
  "Quaint Echo (18)",
  "REVOLVER (18)",
  "Sayonara Planet Wars (18)",
  "Seraphim (18)",
  "Solar Storm (18)",
  "tricky trick (18)",
  "Ultimate Ascension (18)",
  "UnivEarth (18)",
  "veRtrageS (18)",
  "Warriors Aboot (18)",
  "World's end (18)",
  "XHAOS JUDGE (18)",
  "XyHATTE (18)",
  "アルティメットトゥルース -Phantasm- (18)",
  "きたさいたま2000 (18)",
  "ドーパミン (18)",
  "マサカリブレイド (18)",
  "ムラサキグルマ (18)",
  "極圏 (18)",
  "月光乱舞 (18)",
  "混乱少女♥そふらんちゃん!! (18)",
  "侍Annihilate!! (18)",
  "灼熱Beach Side Bunny (18)",
  "消失 (18)",
  "絶対零度 (18)",
  "到達してしまった僕らと夢と希望の最之果 (18)",
  "東方妖々夢 ULTIMATE MEDLEY (18)",
  "伐折羅-vajra- (18)",
  "冥天・ヘメロカリス (18)",
  "crazy cinema story (18)",
  "Foolish Hero (18)",
  "Lieselotte (18)",
  "ボルテ体操第一 (18)",
  "轟け！恋のビーンボール！！ (18)",
  "#Fairy_dancing_in_lake (18)",
  "Joyeuse (18)",
  "Sakura Reflection (P*Light Slayer Remix) (18)",
  "She is my wife　すーぱーアイドル☆ミツル子Remixちゃん (18)",
  "Unicorn tail Dustboxxxx RMX (18)",
  "おお われら喜び讃うべし、主よ (18)",
  "こちら、幸福安心委員会です。 (18)",
  "ムーニャポヨポヨスッポコニャーゴ (18)",
  "上海紅茶館～ Chinese Tea Orchid Remix (18)",
  "C18H27NO3 (18)",
  "Harpuia (18)",
  "Idola (18)",
  "Qubism (18)",
  "超越してしまった彼女と其を生み落した理由 (18)",
  "魔境堕天録サリエル (18)",
  "CODE -CRiMSON- (18)",
  "Crack Traxxxx (18)",
  "Hellfire (18)",
  "Last Concerto (18)",
  "Wish upon Twin Stars (18)",
  "最終鬼畜妹フランドール・S (18)",
  "Bangin' Burst (18)",
  "Black Emperor (18)",
  "BLACK or WHITE? (18)",
  "For UltraPlayers (18)",
  "Growth Memories (18)",
  "INSECTICIDE (18)",
  "VALLIS-NERIA (18)",
  "VILE CAT (18)",
  "werewolf howls. (18)",
  "neu BSP style (18)",
  "物凄い勢いでけーねが物凄いうた (18)",
  "Broken 8cmix (18)",
  "Evans VolteX Pf arrange (18)",
  "Onigo (18)",
  "The world of sound (18)",
  "V.I.P. (18)",
  "金縛りの逢を (18)",
  "腐れ外道とチョコレゐト (18)",
  "幻想のサテライト (18)",
  "孤独の番人 (18)",
  "Absurd Gaff (18)",
  "PANIC HOLIC (18)",
  "Xepher Light and Darkness Dragon REMIX (18)",
  "魔理沙は大変なものを盗んでいきました (18)",
  "croiX (18)",
  "FLOWER REDALiCE Remix (18)",
  "Max Burning!! (18)",
  "冥 Rockin' SWING REMIX (18)"
];

var songlists19 = [
  "2 Beasts Unchained (19)",
  "777 (19)",
  "Absurd Gaff (Metallize Remix) (19)",
  "All We Need is HAPPY END!!! (19)",
  "AμreoLe ~for Triumph~ (19)",
  "and After the Merry BADEND (19)",
  "Avalanx (19)",
  "αzalea (19)",
  "Bad Elixir (19)",
  "BAYONEX (19)",
  "Breakneck Pursuit (19)",
  "Burst Λnd reBoost (19)",
  "Chronomia (19)",
  "Circuit Surfer (19)",
  "CLAMARE (19)",
  "DEUX EX MĀXHINĀ (19)",
  "EncorE & cALL (19)",
  "Fαtα∠ Ent∠mEnt (19)",
  "Glory of Fighters (19)",
  "HALO (19)",
  "Holy Trail (19)",
  "[ ]DENTITY (19)",
  "LaμreLs ~the Angelus~ (19)",
  "MILITARY R04D (19)",
  "One More Lovely (19)",
  "onslaught -Retaliation of Bahamūt- (19)",
  "OVEЯ+TUЯE (19)",
  "perditus†paradisus (19)",
  "QQ (19)",
  "Rapsodia d'amore (19)",
  "Reverenced Flower (19)",
  "Rhapsody ⚙f Triumph (19)",
  "Spectacular“V”Adventure! (19)",
  "The Clown of 24stairs (19)",
  "Undead Raving Scare (19)",
  "VALKYRIE ASSAULT (19)",
  "VΛZiLiSQ (19)",
  "VOLAQUAS (19)",
  "Xb10r (19)",
  "ZEUS (19)",
  "すべてが幻になった後で (19)",
  "ディスコルディア (19)",
  "ドゥサンコオデッセイ!! (19)",
  "ピアノ協奏曲第１番”蠍火” (19)",
  "ピアノ独奏無言歌 ”灰燼” (19)",
  "赫焉 (19)",
  "赫焉のヴァルキュリア -Ragnarok- (19)",
  "紫焔双穿 (19)",
  "十の試煉 (19)",
  "竹 (19)",
  "無意識レクイエム (cosmobsp rmx) (19)",
  "恋愛＝精度×認識力 (19)",
  "9TH5IN (19)",
  "ANGER of the GOD (19)",
  "Calamity Tempest (19)",
  "Daisycutter (19)",
  "ENDYMION (19)",
  "Ghost Family Living In Graveyard (19)",
  "Lancelot ～Flame of the Rebellion～ (19)",
  "Lisa-RICCIA (19)",
  "LubedeR (19)",
  "ΛΛemoria (19)",
  "†:OLPHEUX:† (19)",
  "OUTERHEΛVEN (19)",
  "Redshift 2nd Ignition (19)",
  "ЯeviveR (19)",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY (19)",
  "THE凸GENERATOR (19)",
  "Trill auf G (19)",
  "voltississimo (19)",
  "Xroniàl Xéro (19)",
  "θコトノハθカプセルθ (19)",
  "色を喪った街 (19)",
  "卑弥呼 (19)",
  "飄える翼追い掛けて (19)",
  "A Lasting Promise (19)",
  "Absolute Domination (19)",
  "Awakening (19)",
  "BELOBOG (19)",
  "Chrono Diver -PENDULUMs- (19)",
  "Cross Fire (19)",
  "Deadly force (19)",
  "Dyscontrolled Galaxy (19)",
  "Elemental Creation (19)",
  "Failnaught (19)",
  "Fin.ArcDeaR (19)",
  "Fly Like You (19)",
  "FREEDOM DiVE (19)",
  "GERBERA -For Finalists- (19)",
  "GODHEART (19)",
  "Immortal saga (19)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Empress Side (19)",
  "Last Resort (19)",
  "Sailing Force (19)",
  "Staring at star (19)",
  "TWO-TORIAL (19)",
  "Xéroa (19)",
  "セイレーン ～悲壮の竪琴～ (19)",
  "逆月 (19)",
  "2 MINUTES FIGHTERS (19)",
  "EMPIRE OF FLAME (19)",
  "End to end (19)",
  "Invitation from Mr.C (19)",
  "LegenD. (19)",
  "veRtrageS (19)",
  "INF-B《L-aste-R》 (19)",
  "FLOWER (19)",
  "Got more raves？ (19)",
  "きたさいたま2000 (19)",
  "極圏 (19)",
  "ΑΩ (19)",
  "Blastix Riotz (19)",
  "DIABLOSIS::Nāga (19)",
  "Everlasting Message (19)",
  "FLügeL《Λrp:ΣggyØ》 (19)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side (19)",
  "Lord=Crossight (19)",
  "Preserved Valkyria (19)",
  "XyHATTE (19)",
  "月光乱舞 (19)",
  "Fiat Lux (19)",
  "HYENA (19)",
  "U.N.オーエンは彼女なのか？haru_naba Remix (19)",
  "Innocent Tempest (19)",
  "IX (19)",
  "ラクガキスト (19)",
  "音楽 -resolve- (19)",
  "Booths of Fighters (19)",
  "For UltraPlayers (19)",
  "INSECTICIDE (19)",
  "Quietus Ray (19)",
  "Verse IV (19)",
  "バンブーソード・ガール (19)",
  "Bangin' Burst (19)",
  "Black Emperor (19)",
  "BLACK or WHITE? (19)",
  "Growth Memories (19)",
  "snow storm -euphoria- (19)",
  "XROSS INFECTION (19)",
  "大宇宙ステージ (19)",
  "Ganymede kamome mix (19)"
];

var songlists20 = [
  "Λkasha (20)",
  "APØCALYPSE RAY (20)",
  "Bl∞min' (20)",
  "HeaveИ's Rain (20)",
  "MixxioN (20)",
  "《Re:miniscence》 (20)",
  "SuddeИDeath (20)",
  "XHRONOXAPSULΞ (20)",
  "You Are My Best RivaL!! (20)",
  "いまきみに (20)",
  "666 (20)",
  "ΣgØ (20)",
  "* Erm, could it be a Spatiotemporal　ShockWAVE Syndrome...? (20)",
  "MAYHEM (20)",
  "VVelcome!! (20)",
  "ΣmbryØ (20)",
  "*Feels Seasickness...* (20)",
  "FIN4LE ～終止線の彼方へ～ (20)",
  "HE4VEN ～天国へようこそ～ (20)",
  "I (20)",
  "iLLness LiLin (20)",
  "WHITEOUT (20)",
  "Xronièr (20)",
  "Lachryma《Re:Queen'M》 (20)"
];

var songliststotal = new Array;
songliststotal = songlists18.concat(songlists19).concat(songlists17).concat(songlists20);
xi = songliststotal.length; // 곡 갯수
xxi.innerHTML = "전체 곡 수: "+ xi +"곡";

function input() {
  const songlistcheck = [];
      if (document.getElementById("checkbox1").checked) {
        songlistcheck.push(...songlists17);
    }

    if (document.getElementById("checkbox2").checked) {
        songlistcheck.push(...songlists18);
    }

    if (document.getElementById("checkbox3").checked) {
        songlistcheck.push(...songlists19);
    }

    if (document.getElementById("checkbox4").checked) {
        songlistcheck.push(...songlists20);
    }

  sival = songlistcheck.length

  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    if (sival === 0) {
      document.getElementById("ul").innerHTML = "Dyscontrolled galaxy!!";
    } else {
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlistcheck[Math.floor(Math.random()*(sival-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};

document.getElementById('copy-btn').addEventListener('click', function() {
  html2canvas(document.getElementById('ul')).then(canvas => {
    canvas.toBlob(function(blob) {
      navigator.clipboard.write([
        new ClipboardItem({'image/png': blob})
      ]);
    });
  });
});

document.getElementById('copyButton').addEventListener('click', function() {
  const ulContent = document.getElementById('ul').innerText;
  navigator.clipboard.writeText(ulContent).then(() => {
      alert('클립보드에 복사되었습니다!');
  }).catch(err => {
      console.error('복사 실패:', err);
  });
});