var songlists17 = [
  "[E] (17)",
  "↑↑↓↓←→←→BA (17)",
  "2094 (17)",
  "ABSOLUTE(ismK passionate remix) (17)",
  "ABSOLUTE (saminun mix) (17)",
  "Aerial Skydive (17)",
  "Aftermath (17)",
  "ASGORE / アズゴア (17)",
  "Awakening Wings (17)",
  "Berry Go!! (17)",
  "Black or Red? (17)",
  "Blue Forest(NightBounce Remix) (17)",
  "Chakra (17)",
  "charm♡you (17)",
  "Chewingood!!! (17)",
  "Chocolate Planet (いるちょこRemix) (17)",
  "Continuous Moment (17)",
  "CUDDLIE CUDDLIE (17)",
  "Dawn of Asia(Alkome Remix) (17)",
  "Death by Glamour / 華麗なる死闘 (17)",
  "Demetel (Erixa ”MYTH” Remix) (17)",
  "Element of SPADA (17)",
  "Empty Backdoor (17)",
  "Enter The Fire (17)",
  "eXtridia (17)",
  "fantastic dreamer (17)",
  "Flip Flap (17)",
  "Follow Tomorrow (17)",
  "Foolish Again (17)",
  "For.*tune (17)",
  "FUJIMORI -祭- FESTIVAL (17)",
  "Fun walk!! (17)",
  "Help me, ERINNNNNN!! #幻想郷ホロイズムver. (17)",
  "I Left for my Right (17)",
  "Impress(siqlo's Hi-Tech Veats) (17)",
  "Jailbreaker (17)",
  "- Jupiter - (17)",
  "LIKE A VAMPIRE (17)",
  "Lost Emotion feat. nomico (17)",
  "Love Love Scarlet (17)",
  "LUCKY CAT (17)",
  "MA・TSU・RI (17)",
  "M-O-R-F-I-N-E (17)",
  "Μοῦσα (17)",
  "MOVE! (We Keep It Movin') (17)",
  "NIN-NIN-NIN!! (17)",
  "Pixelated Platform (Super Honey!) (17)",
  "PLANISPHERE (17)",
  "PRESERVED VAMPIRE (17)",
  "PRIDE of the FIREBALL (17)",
  "Re:call (17)",
  "Re:Rose Gun Shoooot! (17)",
  "Realize (17)",
  "Redo (17)",
  "Resonant Gear (17)",
  "Sakura Fubuki (17)",
  "Second Game (17)",
  "SHION -sublimation mix- (17)",
  "sparky spark (17)",
  "Spear of Justice / 正義の槍 (17)",
  "Spider Dance / スパイダーダンス (17)",
  "Splash Underwater (17)",
  "Struggle for Revival (17)",
  "Verstarkt Killer (17)",
  "Whip☆Drip (17)",
  "WICKeD CRφSS (17)",
  "WILD FIRE (17)",
  "WWW (17)",
  "Xymatic Scope (17)",
  "アルファ・スカイ (17)",
  "いでぃおで結構！ (17)",
  "インドア系ならトラックメイカー (17)",
  "ヴァンパイア (17)",
  "おちゃめ機能 (17)",
  "おねがいダーリン (17)",
  "オリガミカル・スウィートラヴ (17)",
  "オルターエゴ (17)",
  "カシオペアノヒカリ (17)",
  "キャプテン・マリンのケツアンカー (17)",
  "キラメキ居残り大戦争 (17)",
  "キリカ (17)",
  "グッバイ宣言 (17)",
  "サクラノソバニ！ (17)",
  "シル・ヴ・プレジデント (17)",
  "スーパー戦湯ババンバーン (17)",
  "ステラ・イミグレーション (17)",
  "ステラレギア (17)",
  "スノウイコン (17)",
  "チェイスチェイスジョーカーズのうた (17)",
  "チクサクコールが懐かしい (17)",
  "デンデラパーティーナイト (17)",
  "トーキョーサマーナイト（華金Remix） (17)",
  "トランスダンスアナーキー (17)",
  "ハートシェイプ・スピカ (17)",
  "ヒトガタ (17)",
  "ヒバナ-Reloaded- (17)",
  "ぶいちゅっばの歌 (17)",
  "フェアリーテイル・ラヴァーズ (17)",
  "フォニイ (17)",
  "みたらしプラトニック (feat. nicamoq) (17)",
  "メテオライツ・プレリュード (17)",
  "メモリーズ (17)",
  "メンタンピンドラドラ (17)",
  "運命超過乃巡合 (17)",
  "神っぽいな (17)",
  "神にした彼女が示す世界線 (17)",
  "機械仕掛けの魔法使い (17)",
  "驪駒早鬼は馬並み☆プロテイン (17)",
  "穢れなきユーフォリア (17)",
  "月下の舞兎祭 (17)",
  "木洩れ日に咲く (17)",
  "終点の先が在るとするならば。 (17)",
  "透明声彩 (17)",
  "泥の分際で私だけの大切を奪おうだなんて (17)",
  "叛逆のディスパレート (17)",
  "響く静寂 (17)",
  "無意識レクイエム (17)",
  "斑咲花 (17)",
  "門門しましょ (17)",
  "勇者の卒業式 (17)",
  "夢の終わり、世界のはじまり。 (17)",
  "凛として咲く花の如く (17)",
  "黎明の情 (17)",
  "恋獄対刃 (17)",
  "2 Beasts Unchained (17)",
  "777 (17)",
  "Absurd Gaff (Metallize Remix) (17)",
  "All We Need is HAPPY END!!! (17)",
  "AμreoLe ~for Triumph~ (17)",
  "and After the Merry BADEND (17)",
  "Avalanx (17)",
  "αzalea (17)",
  "BAYONEX (17)",
  "Breakneck Pursuit (17)",
  "Chronomia (17)",
  "CLAMARE (17)",
  "DEUX EX MĀXHINĀ (17)",
  "EncorE & cALL (17)",
  "Fαtα∠ Ent∠mEnt (17)",
  "Glory of Fighters (17)",
  "HALO (17)",
  "[ ]DENTITY (17)",
  "LaμreLs ~the Angelus~ (17)",
  "MILITARY R04D (17)",
  "One More Lovely (17)",
  "onslaught -Retaliation of Bahamūt- (17)",
  "perditus†paradisus (17)",
  "QQ (17)",
  "Rapsodia d'amore (17)",
  "Reverenced Flower (17)",
  "Rhapsody ⚙f Triumph (17)",
  "Spectacular“V”Adventure! (17)",
  "The Clown of 24stairs (17)",
  "Undead Raving Scare (17)",
  "VΛZiLiSQ (17)",
  "VOLAQUAS (17)",
  "Xb10r (17)",
  "ZEUS (17)",
  "すべてが幻になった後で (17)",
  "ディスコルディア (17)",
  "ドゥサンコオデッセイ!! (17)",
  "ピアノ協奏曲第１番”蠍火” (17)",
  "ピアノ独奏無言歌 ”灰燼” (17)",
  "赫焉 (17)",
  "赫焉のヴァルキュリア -Ragnarok- (17)",
  "紫焔双穿 (17)",
  "十の試煉 (17)",
  "竹 (17)",
  "恋愛＝精度×認識力 (17)",
  "120秒のエンドロール (17)",
  "ABSOLUTE (EUROBEAT REMIX) (17)",
  "Adrenaline Rush (17)",
  "Afterimage d'automne (17)",
  "AXION (17)",
  "Believe (y)our Wings {GRA5P WAVES} (17)",
  "Believe (y)our Wings {V:IVID RAYS} (17)",
  "Bioslaves (17)",
  "bistro twins☆☆☆ (17)",
  "BLACK JACKAL (17)",
  "BLAZE∞BREEZE (17)",
  "BLIZZARD BEAT (17)",
  "Blue Forest (Prog Keys Remix) (17)",
  "Bye or not (17)",
  "Chocolate Parade (17)",
  "Circulator (17)",
  "clear:wings (17)",
  "cloche(といぼっくすうぃんぐ　みっくす) (17)",
  "CLOUDS FLYER -sdvx edit- (17)",
  "Colorless feat.ももかみ (17)",
  "D1g1t1ze b0dy (17)",
  "DEEP PSYCHEDELIC STRIKER (17)",
  "DESIRE (17)",
  "EGOISM -Rebuild- (17)",
  "empty (17)",
  "Enigma II (17)",
  "Enjoy This Time (17)",
  "Harmonia (17)",
  "Impress (bansou Remix) (17)",
  "Into The Madness (17)",
  "Jetcoaster Windy (17)",
  "le coeur patissiere (17)",
  "MARENOL (17)",
  "Me:Tear (17)",
  "MICHIZURE (17)",
  "MilK (17)",
  "Mischievous theater (17)",
  "ΩBIRD (17)",
  "One In A Billion（Hedonist Remix） (17)",
  "Pixelated Platform (17)",
  "PIZZATIME (17)",
  "POSSESSION(Gowrock Remix) (17)",
  "Princess Lily (17)",
  "Quark (17)",
  "Record one's Dream (17)",
  "ЯegreT of MemoRy (17)",
  "Revolution (17)",
  "Sacrifice Escape:　不条理の模倣による感情と代償 (17)",
  "scary night (17)",
  "Sharkbait (17)",
  "Six String Proof (17)",
  "Sparkle Smilin' (17)",
  "Still Lonesome (17)",
  "STYX HELIX（Digi-Rock Remix） (17)",
  "Sunflower Vibes (17)",
  "The First Step (17)",
  "toy boxer (17)",
  "Tribal Trial (17)",
  "ULTRA B+K (17)",
  "ultra turbo (17)",
  "VIVID DEBUT! (17)",
  "vivid landscape (17)",
  "VIVIDWAVERS (17)",
  "who I am (17)",
  "うさぬこぬんぬんファンタジー！ (17)",
  "エンゲージ〆ント (17)",
  "おーまい！らぶりー！すうぃーてぃ！だーりん！ (17)",
  "おどりましょうよ！ドラゴンさん～転生したらゲーム曲でした～ (17)",
  "クレイジークレイジーダンサーズ (17)",
  "ここからよろしく大作戦143 (17)",
  "シープドリーミン (17)",
  "ストリーミングハート (17)",
  "ハレ トキドキ メランコリック (17)",
  "ふ・れ・ん・ど・し・た・い (WEREHEREMIX) (17)",
  "ベビーステップ (17)",
  "ぼくらの16bit戦争 (17)",
  "ゆりゆららららゆるゆり大事件（yuzen remix） (17)",
  "ラブキラ☆スプラッシュ (17)",
  "ロキ (17)",
  "伊邪那美白山姫大神 (17)",
  "悪戯センセーション (17)",
  "雲海 (17)",
  "御伽噺に幕切れを (17)",
  "革命パッショネイト (17)",
  "君は Fantasista (17)",
  "鏡面の波（ramble mix） (17)",
  "近未来百鬼夜行譚～死返之巻～ (17)",
  "逆さま♥シンデレラパレード (17)",
  "全力ハッピーライフ (17)",
  "太陽曰く燃えよカオス（Sol oscuro ¡Nya! Mix） (17)",
  "濁色踊るオートマタ (17)",
  "熱情のサパデアード (17)",
  "星の詩 (17)",
  "祭囃子 (17)",
  "真夏の海の修道女 (17)",
  "真夏の蜜と唇 fm. 希望の星は青霄に昇る (17)",
  "零次元エクスプレス (17)",
  "9TH5IN (17)",
  "ANGER of the GOD (17)",
  "Calamity Tempest (17)",
  "Daisycutter (17)",
  "ENDYMION (17)",
  "Ghost Family Living In Graveyard (17)",
  "Lancelot ～Flame of the Rebellion～ (17)",
  "Lisa-RICCIA (17)",
  "LubedeR (17)",
  "ΛΛemoria (17)",
  "†:OLPHEUX:† (17)",
  "OUTERHEΛVEN (17)",
  "Redshift 2nd Ignition (17)",
  "ЯeviveR (17)",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY (17)",
  "THE凸GENERATOR (17)",
  "Trill auf G (17)",
  "voltississimo (17)",
  "Xroniàl Xéro (17)",
  "θコトノハθカプセルθ (17)",
  "色を喪った街 (17)",
  "卑弥呼 (17)",
  "飄える翼追い掛けて (17)",
  "3y3s (JMBS FUNKOT RMX) (17)",
  "405nm(Shu※mix) (17)",
  "444 (17)",
  "All Clear!! (17)",
  "Altale (17)",
  "Another Chapter (17)",
  "Apocrypha (17)",
  "Aragami (17)",
  "Arcade Prison (17)",
  "β (17)",
  "Blue Stream (17)",
  "BREAKNECK NY☆N! NY★N! (17)",
  "CARNIVOROUS (17)",
  "Carry Me Away (17)",
  "Chaotic Romance (17)",
  "Chocolate Planet (17)",
  "cobalt (17)",
  "Coldlapse (17)",
  "CUTE-Reflection (17)",
  "Cy-Bird (17)",
  "Dark Matter (17)",
  "Decoy (17)",
  "Destruction & Qreation (17)",
  "Dharma (17)",
  "Dreaming feat.nomico (17)",
  "Drizzly Venom (17)",
  "EDEN of TRUTH (17)",
  "Empathetic (17)",
  "Fáfnir (17)",
  "Far Away (17)",
  "Finale (17)",
  "Fly far bounce (17)",
  "Four Leaves (17)",
  "Game Over (17)",
  "Heavenly Adventure (17)",
  "HEAVENLY SMILE (17)",
  "If (17)",
  "ILL-STARRED Diver (17)",
  "infinite:youniverse (17)",
  "Inscape (17)",
  "Invisible Bullets (17)",
  "Iridescent Clouds (17)",
  "JUGGLE (17)",
  "JULIAN (17)",
  "Junk Mania (17)",
  "Justitia Gladius (17)",
  "Knights Assault (17)",
  "Libera me (17)",
  "Liévre -blanche- (17)",
  "Life is beautiful (17)",
  "Line 4 Ruin -kohumix- (17)",
  "Lost Wing at.0 (17)",
  "Made In Love (17)",
  "MAXIVCORD (17)",
  "Melty Sweets (17)",
  "Musha Vibration (17)",
  "NEON LOVE♥POTION!!! (17)",
  "No way (17)",
  "Oriens (17)",
  "Phlox (17)",
  "PIERROT KNIfE (17)",
  "planetarium (17)",
  "Poison AND÷OR Affection (17)",
  "Poppin’Cats!! (17)",
  "QUAKE (17)",
  "Rebuilding of Paradise Lost (17)",
  "Rejoin (17)",
  "rhythmology study (17)",
  "Royal Action (17)",
  "Royal Judgement (17)",
  "Sadistic Stabbing (17)",
  "Sakura Mirage -Drum'n World- (17)",
  "Secret Traveler -MeniRemix- (17)",
  "sink into the dream (17)",
  "Sleepless days (17)",
  "Smoked Turkey Rag (17)",
  "SPACE VILLAGE (17)",
  "Sulk (17)",
  "SUPER BUBBLE JOURNEY (17)",
  "Synergy For Angels (17)",
  "Technical Master (17)",
  "Tic Exe (17)",
  "Twilight ∞ nighT (17)",
  "Vigor (17)",
  "Voltage Higher (17)",
  "VOLTEXES IV (17)",
  "WONDER_WOBBLER (17)",
  "Xibercannon (17)",
  "Zelophilia (17)",
  "アワデコノヨヲ (17)",
  "アンハッピーリフレイン (17)",
  "インビジブル (17)",
  "おにいちゃんハイテック (17)",
  "オンディーヌの泪 (17)",
  "ケムマキ underground (17)",
  "ゴーストルール (17)",
  "コメット⇒スケイター (17)",
  "すろぉもぉしょん (17)",
  "セイシュンライナー (17)",
  "それは花火のような恋 (17)",
  "ツキアカリ (17)",
  "デュアルメモリ (17)",
  "ブチ上げ候！現代忍者三姉妹 (17)",
  "プラネタジャーニー (17)",
  "プレインエイジア(MRM REMIX) (17)",
  "ペタ靴と憂夜リムーバー (17)",
  "ボーイミーツ・ブルー (17)",
  "メルヘン風紀委員会 (17)",
  "ラキラキ (17)",
  "ロプノールの商隊 (17)",
  "炎夏の音 (17)",
  "煙 (17)",
  "獅子奮迅 (17)",
  "失敗作少女 (17)",
  "銃弾は解を撃ち抜いて (17)",
  "少女綺想曲 -G.X.N. Remix- (17)",
  "水槽のクジラ (17)",
  "星座が恋した瞬間を。 (17)",
  "零の位相 (17)",
  "創世ノート (17)",
  "廃獄ドリームランド (17)",
  "片翼のディザイア (17)",
  "蓬莱フェスティボー (17)",
  "僕らの時間 (17)",
  "焔 -MAGMA- (17)",
  "見世物ライフ (17)",
  "蟲の棲む処 (17)",
  "物凄いスペースシャトルでこいしが物凄いうた (17)",
  "幽玄の桜 (17)",
  "闇夜に舞うは紅の華 (17)",
  "羅生門 (17)",
  "黎明スケッチブック (17)",
  "分けるな危険！モモモモモモーイズム (17)",
  "A Lasting Promise (17)",
  "Absolute Domination (17)",
  "Awakening (17)",
  "BELOBOG (17)",
  "Chrono Diver -PENDULUMs- (17)",
  "Cross Fire (17)",
  "Deadly force (17)",
  "Dyscontrolled Galaxy (17)",
  "Elemental Creation (17)",
  "Failnaught (17)",
  "FLOOR INFECTION Medley　from SOUND VOLTEX×jubeat (17)",
  "Fly Like You (17)",
  "FREEDOM DiVE (17)",
  "GERBERA -For Finalists- (17)",
  "GODHEART (17)",
  "HE4VEN ～天国へようこそ～ (17)",
  "iLLness LiLin (17)",
  "Last Resort (17)",
  "Rebellio (17)",
  "Sailing Force (17)",
  "Staring at star (17)",
  "TWO-TORIAL (17)",
  "Xéroa (17)",
  "セイレーン ～悲壮の竪琴～ (17)",
  "逆月 (17)",
  "超☆超☆光☆速☆出☆前☆最☆速!!!　スピード★スター★かなで (17)",
  "Din Don Dan (Fusion Remix) (17)",
  "バイナリスター (17)",
  "ヒミツダイヤル (17)",
  "Destroy (17)",
  "Get back here (17)",
  "Grand Chariot (17)",
  "INDEPENDENT SKY (17)",
  "Inixia (17)",
  "Sephirot (17)",
  "StrayedCatz (17)",
  "ZEPHYRANTHES (17)",
  "ウエンレラの氷華 (17)",
  "キモチコネクト (17)",
  "ポメグラネイト (17)",
  "ロンロンへ　ライライライ！ (17)",
  "０=Xerostrumental= (17)",
  "2 MINUTES FIGHTERS (17)",
  "akasha-assembly (17)",
  "{albus} (17)",
  "Aliquam (17)",
  "ANTI THE∞HOLiC (17)",
  "Apex of the World (17)",
  "AYAKASHI (17)",
  "B.B.K.K.B.K.K. (17)",
  "Backflow (17)",
  "BEAT-NEW-WORLD (17)",
  "Borealis (17)",
  "Candy Colored Hearts (17)",
  "CENSORED!! (17)",
  "Chant du Cygne (17)",
  "Clash of swords (17)",
  "conflict (17)",
  "continew (17)",
  "CRITICAL LINE (17)",
  "cross the future (17)",
  "CUTIE☆EX-DREAM (17)",
  "Deadly Dolly Dance (17)",
  "DIABLOSIS::Nāga (17)",
  "Discloze (17)",
  "Dualive (17)",
  "EBONY & IVORY (17)",
  "ΕΛΠΙΣ (17)",
  "Emperor's Divide (17)",
  "Enigma (17)",
  "Everlasting Message (17)",
  "F.K.S. (17)",
  "False Cross (17)",
  "FIRE FIRE(Kazmasa Remix) (17)",
  "Follow Up (17)",
  "Garakuta Doll Play (17)",
  "gigadelic(m3rkAb4# R3m!x) (17)",
  "Got more raves？ (17)",
  "Halcyon (17)",
  "Happy Sensation (17)",
  "Help me, ERINNNNNN!! -Cranky remix- (17)",
  "Innocent Floor (17)",
  "JOMANDA (17)",
  "KAC 2012 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- (17)",
  "Lord=Crossight (17)",
  "Lucky*Clover (17)",
  "Mayohiga Spurt (17)",
  "Metamorphobia (17)",
  "NEON WORLD (17)",
  "Never Fails (17)",
  "Nofram (17)",
  "Opium and Purple haze (17)",
  "Paradission (17)",
  "Parousia (17)",
  "Pet Peeve (17)",
  "Pieces of a Dream (17)",
  "Pure Evil (Kobaryo FTN-Remix) (17)",
  "REGALIA (17)",
  "Rubeus (17)",
  "S1CK_F41RY (17)",
  "Shanghai Wu Long ～上海舞龍～ (17)",
  "Stleq (17)",
  "The End of War (17)",
  "The Sampling Paradise (P*Light Remix) (17)",
  "The setting sun (17)",
  "The star in eclipse (17)",
  "THUNDERCRACK (17)",
  "TIEFSEE (17)",
  "Time to Air -Fly High Remix- (17)",
  "TOXIC VIBRATION (17)",
  "Triple Counter (17)",
  "Twin Rocket (17)",
  "UROBØROS (17)",
  "Vampire's Territory (17)",
  "Virtual Bit (17)",
  "Voynich:Manuscript (17)",
  "Witch in Sweetsland (17)",
  "Zero-Day Exploit (17)",
  "アキネイション (17)",
  "あれこれそれどれ (17)",
  "イグジスタンス (17)",
  "きらきらタイム☆ (17)",
  "ゲキツイムラサ (17)",
  "じゅーじゅー♥焼肉の火からフェニックス！？　～再誕の†炭火焼き～ (17)",
  "そして紫の幻想曲は全てを受け入れる (17)",
  "チルノとまりおのパーフェクトさんすう教室 (17)",
  "ネメシス SDVX Edit (17)",
  "パ→ピ→プ→Yeah! (17)",
  "ほおずき程度には赤い頭髪 (17)",
  "ホーンテッド★メイドランチ (17)",
  "ぼくらしかしらない (17)",
  "鬼天 (17)",
  "感情の魔天楼 ～ Arr.Demetori (17)",
  "雲の彼方 (17)",
  "紅の剣舞 (17)",
  "黒髪乱れし修羅となりて～凛 edition～ (17)",
  "漆黒のスペシャルプリンセスサンデー (17)",
  "雪月花 -さわわRemix- (17)",
  "断罪は遍く人間の元に (17)",
  "常夏！！クリスタライズ・シャーベット (17)",
  "夏色DIARY -Summer Dazzlin' Vacation miX- (17)",
  "人形裁判 -THIRD IMPACT- (17)",
  "暴走 (17)",
  "無気力クーデター (17)",
  "無双 (17)",
  "物凄い狂っとるフランちゃんが物凄いうた (17)",
  "量子の海のリントヴルム (17)",
  "ネトゲ廃人シュプレヒコール (17)",
  "マネマネサイコトロピック (17)",
  "Hoshizora Illumination (17)",
  "take a step forward (17)",
  "幻想系世界修復少女 (17)",
  "竹取飛翔 (17)",
  "放課後ストライド (17)",
  "Appliqué (17)",
  "choux à la crème (17)",
  "Double Universe (17)",
  "Erlung (17)",
  "INFINITY OVERDRIVE (17)",
  "Last Battalion (17)",
  "LittleGameStar (17)",
  "odds and ends (17)",
  "ウバワレ (17)",
  "少年は空を辿る Prog Piano Remix (17)",
  "雪女 (17)",
  "御千手メディテーション (17)",
  "患部で止まってすぐ溶ける ～ 狂気の優曇華院 (17)",
  "打打打打打打打打打打 (17)",
  "BabeL ～Next Story～ (17)",
  "Booths of Fighters (17)",
  "CODE -CRiMSON- (17)",
  "DEADLOCK XXX (17)",
  "Decretum (17)",
  "#FairyJoke #SDVX_Edit (17)",
  "Fiat Lux (17)",
  "FIRE FIRE -DARK BLAZE REMIX- (17)",
  "FLYING OUT TO THE SKY (17)",
  "gigadelic -stance xxxx- (17)",
  "HAELEQUIN (17)",
  "Harpuia (17)",
  "Hellfire (17)",
  "HYENA (17)",
  "Idola (17)",
  "Innocent Tempest (17)",
  "IX (17)",
  "Joyeuse (17)",
  "KiLLeR MeRMaiD (17)",
  "Last Concerto (17)",
  "Little princess has no identity. (17)",
  "Mist In Hell (17)",
  "Our Faith (Faithful MTL Remix) (17)",
  "Pure Evil (17)",
  "Pure Evil-Aya2g Drm'n Tech Rmx- (17)",
  "Quietus Ray (17)",
  "Sakura Mirage (17)",
  "snow storm -euphoria- (17)",
  "True Blue (17)",
  "U.N.オーエンは彼女なのか？haru_naba Remix (17)",
  "Verse IV (17)",
  "Wish upon Twin Stars (17)",
  "XROSS INFECTION (17)",
  "イゴモヨス＝オムルのテーマによる　ブヨブヨ・スケッチの試み (17)",
  "バンブーソード・ガール (17)",
  "ボルテ体操第一 (17)",
  "ムーニャポヨポヨスッポコニャーゴ (17)",
  "朱と碧のランページ (17)",
  "悪性ロリィタマキャヴェリズム (17)",
  "音楽 -resolve- (17)",
  "音楽 -壊音楽 mix- (17)",
  "少女暴動 (17)",
  "信仰は儚き人間の為に ～ Arr.Demetori (17)",
  "超越してしまった彼女と其を生み落した理由 (17)",
  "轟け！恋のビーンボール！！ (17)",
  "柳の下のデュラハン hard chaos mix (17)",
  "Grip & Break down !! - SDVX Edit. - (17)",
  "Hello world! (17)",
  "smooooch・∀・ KN mix (17)",
  "SOUL EXPLOSION (17)",
  "色は匂へど散りぬるを (17)",
  "地球最後の告白を (17)",
  "十面相 (17)",
  "人生リセットボタン (17)",
  ".59 -BOOTH BOOST REMIX- (17)",
  "cloud (17)",
  "Fire Strike (17)",
  "Space Diver Tama (17)",
  "Wheel (17)",
  "イカサマライフゲイム (17)",
  "ケロ⑨destiny (17)",
  "サヨナラ・ヘヴン　(かめりあ's NEKOMATAelectroRMX) (17)",
  "セツナトリップ (17)",
  "éclair au chocolat (17)",
  "EGG (17)",
  "freaky freak (17)",
  "カミサマネジマキ (17)",
  "香港功夫大旋風 (17)",
  "AA BlackY mix (17)",
  "ALBIDA Powerless Mix (17)",
  "Distorted Floor (17)",
  "Dynasty (17)",
  "good high school (17)",
  "Gott (17)",
  "TYCOON (17)",
  "ナイト・オブ・ナイツ (17)",
  "天ノ弱 (17)",
  "過食性:アイドル症候群 (17)",
  "Ganymede kamome mix (17)",
  "Max Burning!! (17)",
  "The world of sound (17)",
  "V.I.P. (17)",
  "金縛りの逢を (17)",
  "大宇宙ステージ (17)"
];

xi = songlists17.length; // 곡 갯수
xxi.innerHTML = "전체 곡 "+ xi +"곡";

function input() {
  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlists17[Math.floor(Math.random()*(xi-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};
