var songlists18 = [

  "Aerial Fortress [ MXM 18 ]",
  "ARROW RAIN [ MXM 18 ]",
  "Atropa bella-donna [ MXM 18 ]",
  "Aurolla [ MXM 18 ]",
  "Barbatos [ MXM 18 ]",
  "Barbless Ego [ GRV 18 ]",
  "Believe In Yourself [ GRV 18 ]",
  "Black Lotus [ MXM 18 ]",
  "Butterfly Twist [ MXM 18 ]",
  "Call of the World [ MXM 18 ]",
  "Cloud Crasher [ GRV 18 ]",
  "Cynical Joker [ MXM 18 ]",
  "Dogeza Stairs [ MXM 18 ]",
  "eighth-slave [ MXM 18 ]",
  "Elemental Creation (kamome sano Remix) [ MXM 18 ]",
  "Enchante [ MXM 18 ]",
  "FIRST：DREAMS [ MXM 18 ]",
  "GALAXY BURST [ MXM 18 ]",
  "GaLaXyEggPlanT [ MXM 18 ]",
  "Glorious Journey [ MXM 18 ]",
  "Jack-the-Ripper◆ [ MXM 18 ]",
  "Jacob’s Elevator [ MXM 18 ]",
  "JǛPITΨR ♃ GЯÃVITÝ [ MXM 18 ]",
  "Katharsis [ MXM 18 ]",
  "LECTORIA [ MXM 18 ]",
  "lEyl [ MXM 18 ]",
  "Liar rain [ GRV 18 ]",
  "mqlo [ MXM 18 ]",
  "Nhelv [ MXM 18 ]",
  "On take SUN [ MXM 18 ]",
  "Over The Top [ VVD 18 ]",
  "ΩVERFLOW [ MXM 18 ]",
  "OZONE [ GRV 18 ]",
  "PARTY TIME! [ MXM 18 ]",
  "petits fours [ MXM 18 ]",
  "pique [ MXM 18 ]",
  "Pulsar [ MXM 18 ]",
  "rE:Voltagers [ GRV 18 ]",
  "SAMURAI TIGER [ MXM 18 ]",
  "SociuS [ MXM 18 ]",
  "Sudden Visitor [ MXM 18 ]",
  "Teufel [ MXM 18 ]",
  "To:BrandNewDeadline [ MXM 18 ]",
  "Turn the story [ MXM 18 ]",
  "Typhoon Craaash!! [ GRV 18 ]",
  "Übertreffen [ MXM 18 ]",
  "V Sen5eS [ MXM 18 ]",
  "Valanga(polysha Remix) [ MXM 18 ]",
  "Vividly Impromptu [ MXM 18 ]",
  "World of Iris [ VVD 18 ]",
  "Xicholauncher [ MXM 18 ]",
  "ZEИITH [ MXM 18 ]",
  "アオアラシ [ MXM 18 ]",
  "タイムトラベル [ GRV 18 ]",
  "ツマミ戦隊 タテレンジャー [ MXM 18 ]",
  "トマヨイ [ VVD 18 ]",
  "ねこみみ(=ФωФ=)ぱんでみみっく [ GRV 18 ]",
  "び [ MXM 18 ]",
  "ミッドナイト☆WAR [ MXM 18 ]",
  "ランカーキラーガール [ MXM 18 ]",
  "怪盗Fの台本～消えたダイヤの謎～ [ MXM 18 ]",
  "蛇神 [ MXM 18 ]",
  "最小三倍完全数 [ MXM 18 ]",
  "消失(Hommarju Remix) [ MXM 18 ]",
  "翠雨の祷 [ MXM 18 ]",
  "諏訪大信仰 [ MXM 18 ]",
  "星の透る夏空に願う [ MXM 18 ]",
  "無魎大数 [ MXM 18 ]",

  "666 [ EXH 18 ]",
  "ΣgO [ EXH 18 ]",
  "Erm, could it be a Spatiotemporal ShockWAVE Syndrome...? [ EXH 18 ]",

  "Akzeriyyuth [ MXM 18 ]",
  "ALTONA [ GRV 18 ]",
  "Be a Hero! [ MXM 18 ]",
  "BEAST BASS BOMB [ MXM 18 ]",
  "Beyond the BLUE [ MXM 18 ]",
  "Black night [ MXM 18 ]",
  "BLAZING_LAZER [ MXM 18 ]",
  "BlueMoon Princess [ MXM 18 ]",
  "Boss Rush [ MXM 18 ]",
  "Breakin' Asia [ MXM 18 ]",
  "Catch Our Fire! [ MXM 18 ]",
  "Cepheus [ MXM 18 ]",
  "CHERNOBOG [ MXM 18 ]",
  "Cloud 9 [ MXM 18 ]",
  "Concertino in Blue [ MXM 18 ]",
  "crossing blue [ MXM 18 ]",
  "Destiny [ MXM 18 ]",
  "Divine's:Bugscript [ MXM 18 ]",
  "Divine's or Deal [ MXM 18 ]",
  "Doppelganger [ MXM 18 ]",
  "Dreadnought [ MXM 18 ]",
  "DropZ-Line- [ MXM 18 ]",
  "ECHIDNA [ MXM 18 ]",
  "Evans [ MXM 18 ]",
  "FIRE IN MY HEART [ MXM 18 ]",
  "FLOOR INFECTION Medley from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "GAIA [ MXM 18 ]",
  "Gamerz FestivaL [ MXM 18 ]",
  "Gate of Atlantis [ MXM 18 ]",
  "GERBERA [ MXM 18 ]",
  "Ghost Trigger [ MXM 18 ]",
  "Glitter Flatter Scatter [ MXM 18 ]",
  "Goddess Bless you [ MXM 18 ]",
  "Gorgetech [ MXM 18 ]",
  "Grand-Guignol [ MXM 18 ]",
  "HP:1 [ MXM 18 ]",
  "Hug!! Vs. Hug!! [ MXM 18 ]",
  "НУМЛ [ MXM 18 ]",
  "Juggler's Maddness [ MXM 18 ]",
  "JUNKIE FLAVOR [ MXM 18 ]",
  "Khionos TiARA [ MXM 18 ]",
  "KIMIDORI Streak!! [ MXM 18 ]",
  "LastΩmegA [ MXM 18 ]",
  "Legendary Road [ MXM 18 ]",
  "Levier'n NābYss [ MXM 18 ]",
  "Lowermost revolt [ MXM 18 ]",
  "Lunatic Sprinter [ MXM 18 ]",
  "Make Magic [ MXM 18 ]",
  "MeteorGlow Aftermath [ MXM 18 ]",
  "Midnight City Warfare [ MXM 18 ]",
  "Mirrorwall [ MXM 18 ]",
  "MODEL FT4 [ MXM 18 ]",
  "MONOLITH [ MXM 18 ]",
  "New Leaf [ MXM 18 ]",
  "Nexta [ GRV 18 ]",
  "Night Rockin' Bird [ MXM 18 ]",
  "Noisy Minority [ MXM 18 ]",
  "Nostalgic Blood of the Strife [ MXM 18 ]",
  "OPEN MY GATE [ MXM 18 ]",
  "ouroboros -twin stroke of the end- [ MXM 18 ]",
  "ΩVERSOUL [ MXM 18 ]",
  "POLICY BREAK Medley from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "Prey [ MXM 18 ]",
  "PROVOES*PROPOSE <<el fine>> [ GRV 18 ]",
  "Puberty Dysthymia [ MXM 18 ]",
  "PUPA [ MXM 18 ]",
  "Re:End of a Dream [ MXM 18 ]",
  "Яe's NoVE [ MXM 18 ]",
  "Rebellio [ MXM 18 ]",
  "Reb∞t [ GRV 18 ]",
  "REDO the NIGHT [ GRV 18 ]",
  "Redshift [ MXM 18 ]",
  "RHYZING BEAT [ MXM 18 ]",
  "Sacrifice and Faith [ MXM 18 ]",
  "SACRIFICE feat.ayame [ MXM 18 ]",
  "SAtAN [ MXM 18 ]",
  "Scarlet Lance [ MXM 18 ]",
  "She Turns Me On [ GRV 18 ]",
  "Sky High [ MXM 18 ]",
  "#SpeedyCats [ MXM 18 ]",
  "Spirit of the Beast [ MXM 18 ]",
  "STULTI [ MXM 18 ]",
  "SUPER SUMMER SALE [ MXM 18 ]",
  "Sweet Requiem [ MXM 18 ]",
  "Taiko Drum Monster [ MXM 18 ]",
  "The Formula [ MXM 18 ]",
  "The Golden Era [ MXM 18 ]",
  "THE HEAVEN [ MXM 18 ]",
  "Theme of Ricerca [ MXM 18 ]",
  "Touch My Body [ MXM 18 ]",
  "TRICKL4SH 220 [ MXM 18 ]",
  "ULTiMATE INFLATiON [ MXM 18 ]",
  "ULTRAVELOCITY [ MXM 18 ]",
  "V [ MXM 18 ]",
  "Venomous Firefly [ MXM 18 ]",
  "Victim of Nights [ MXM 18 ]",
  "We Go Down [ MXM 18 ]",
  "Wings of Glory [ MXM 18 ]",
  "Xevel [ MXM 18 ]",
  "Yum Yum Sweetie [ MXM 18 ]",
  "お米の美味しい炊き方、そしてお米を食べることによるその効果。 [ MXM 18 ]",
  "オニユリ [ MXM 18 ]",
  "キュリオシティ [ MXM 18 ]",
  "サイコパスラビット [ MXM 18 ]",
  "スラッシュシスターズ [ MXM 18 ]",
  "セイクリッド ルイン [ MXM 18 ]",
  "そして黄金郷へ [ MXM 18 ]",
  "ドリームエンド・サバイバー [ MXM 18 ]",
  "のぼれ八坂坂！ [ MXM 18 ]",
  "びいすと！ [ MXM 18 ]",
  "ファイナルレター [ MXM 18 ]",
  "ホワイトパレード [ MXM 18 ]",
  "まじかる生主＠りすなちゃん [ GRV 18 ]",
  "メイビ～初恋！？ビスケット☆大作戦 [ MXM 18 ]",
  "ワールズエンド・ダンスホール [ MXM 18 ]",
  "怒槌 [ MXM 18 ]",
  "永遠に幸せになる方法、見つけました。 [ MXM 18 ]",
  "壊Rave*it!! 壊Rave*it!! [ MXM 18 ]",
  "神獄烙桜 [ MXM 18 ]",
  "恋歌疾風！かるたクイーンいろは [ MXM 18 ]",
  "業焔繚乱 [ GRV 18 ]",
  "極彩天奏 [ MXM 18 ]",
  "祝福の色彩は想い結ぶ君たち迄 [ MXM 18 ]",
  "準備運動 [ MXM 18 ]",
  "神話に芽吹く [ MXM 18 ]",
  "水簾ノ調 [ MXM 18 ]",
  "誰が為に兎は舞う＝狂速狂騒曲＝ [ MXM 18 ]",
  "超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで [ MXM 18 ]",
  "†渚の小悪魔ラヴリィ～レイディオ† [ MXM 18 ]",
  "光射す澪のユズリハ [ MXM 18 ]",
  "真っ白な靴 [ GRV 18 ]",
  "雷鼓サンダービート [ MXM 18 ]",

  "ΣmbryO [ EXH 18 ]",
  "Feels Seasickness...* [ EXH 18 ]",
  "FIN4LE ～終止線の彼方へ～ [ EXH 18 ]",
  "Fin.ArcDeaR [ EXH 18 ]",
  "I [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Empress Side [ EXH 18 ]",
  "WHITEOUT [ EXH 18 ]",
  "Xronier [ EXH 18 ]",

  "Garakuta Doll Play [ HVN 18 ]",
  "Angelic Jelly [ GRV 18 ]",
  "Celestial stinger [ GRV 18 ]",
  "Completeness Under Incompleteness [ GRV 18 ]",
  "HAELE III ~Angel Worlds~ [ GRV 18 ]",
  "KAC 2012 ULTIMATE MEDLEY [ GRV 18 ]",
  "NEO TREASON [ GRV 18 ]",
  "Ok!! Hug Me [ GRV 18 ]",
  "Opium and Purple haze [ GRV 18 ]",
  "Renegade Fruits [ GRV 18 ]",
  "Triple Counter [ GRV 18 ]",
  "XROSS THE XOUL [ GRV 18 ]",
  "↓↓↓ [ EXH 18 ]",
  "ΑΩ [ EXH 18 ]",
  "Angels And Demons [ EXH 18 ]",
  "Blastix Riotz [ EXH 18 ]",
  "Demise Quartet [ EXH 18 ]",
  "EMPIRE OF FLAME [ EXH 18 ]",
  "#Endroll [ EXH 18 ]",
  "End to end [ EXH 18 ]",
  "Endless GRAVITY [ EXH 18 ]",
  "FLügeL《Λrp:ΣggyØ》 [ EXH 18 ]",
  "Firestorm [ EXH 18 ]",
  "FLOWER [ EXH 18 ]",
  "Fox4-Raize- [ EXH 18 ]",
  "GEOMETRIA [ EXH 18 ]",
  "gigadelic (かめりあ's The TERA RMX) [ EXH 18 ]",
  "HAVOX [ EXH 18 ]",
  "IKAROS DYNAMITE!!!! [ EXH 18 ]",
  "INF-B《L-aste-R》 [ EXH 18 ]",
  "Invitation from Mr.C [ EXH 18 ]",
  "JEHANNEDARC [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX- Emperor Side [ EXH 18 ]",
  "Lachryma《Re:Queen'M》 [ EXH 18 ]",
  "LegenD. [ EXH 18 ]",
  "MG277 [ EXH 18 ]",
  "NEO GRAVITY [ EXH 18 ]",
  "Ops:Code-Rapture- [ EXH 18 ]",
  "Pon-Pon-Pompoko Dai-Sen-Saw! [ EXH 18 ]",
  "Prayer [ EXH 18 ]",
  "Preserved Valkyria [ EXH 18 ]",
  "Quaint Echo [ EXH 18 ]",
  "REVOLVER [ EXH 18 ]",
  "Sayonara Planet Wars [ EXH 18 ]",
  "Seraphim [ EXH 18 ]",
  "Solar Storm [ EXH 18 ]",
  "tricky trick [ EXH 18 ]",
  "Ultimate Ascension [ EXH 18 ]",
  "UnivEarth [ EXH 18 ]",
  "veRtrageS [ EXH 18 ]",
  "Warriors Aboot [ EXH 18 ]",
  "World's end [ EXH 18 ]",
  "XHAOS JUDGE [ EXH 18 ]",
  "XyHATTE [ EXH 18 ]",
  "アルティメットトゥルース -Phantasm- [ EXH 18 ]",
  "きたさいたま2000 [ EXH 18 ]",
  "ドーパミン [ EXH 18 ]",
  "マサカリブレイド [ EXH 18 ]",
  "ムラサキグルマ [ EXH 18 ]",
  "極圏 [ EXH 18 ]",
  "月光乱舞 [ EXH 18 ]",
  "混乱少女♥そふらんちゃん!! [ EXH 18 ]",
  "侍 Annihilate!! [ EXH 18 ]",
  "灼熱Beach Side Bunny [ EXH 18 ]",
  "消失 [ EXH 18 ]",
  "絶対零度 [ EXH 18 ]",
  "到達してしまった僕らと夢と希望の最之果 [ EXH 18 ]",
  "東方妖々夢 ULTIMATE MEDLEY [ EXH 18 ]",
  "伐折羅-vajra- [ EXH 18 ]",
  "冥天・ヘメカリス [ EXH 18 ]",

  "#Fairy_dancing_in_lake [ VVD 18 ]",
  "Joyeuse [ VVD 18 ]",
  "Sakura Reflection (P*Light Slayer Remix) [ VVD 18 ]",
  "She is my wife すーぱーアイドル [ VVD 18 ]",
  "Unicorn tail Dustboxxxx RMX [ VVD 18 ]",
  "おお われら喜び讃うべし、主よ [ VVD 18 ]",
  "こちら、幸福安心委員会です。 [ VVD 18 ]",
  "ムーニャポヨポヨスッポコニャーゴ [ VVD 18 ]",
  "上海紅茶館～ Chinese Tea Orchid Remix [ VVD 18 ]",
  "C18H27NO3 [ HVN 18 ]",
  "Harpuia [ HVN 18 ]",
  "Idola [ HVN 18 ]",
  "Qubism [ HVN 18 ]",
  "超越してしまった彼女と其を生み落した理由 [ HVN 18 ]",
  "魔境堕天録サリエル [ HVN 18 ]",
  "CODE -CRiMSON- [ GRV 18 ]",
  "Crack Traxxxx [ GRV 18 ]",
  "Hellfire [ GRV 18 ]",
  "Last Concerto [ GRV 18 ]",
  "Wish upon Twin Stars [ GRV 18 ]",
  "最終鬼畜妹フランドール・S [ GRV 18 ]",
  "Bangin' Burst [ EXH 18 ]",
  "Black Emperor [ EXH 18 ]",
  "BLACK or WHITE? [ EXH 18 ]",
  "For UltraPlayers [ EXH 18 ]",
  "Growth Memories [ EXH 18 ]",
  "INSECTICIDE [ EXH 18 ]",
  "VALLIS-NERIA [ EXH 18 ]",
  "VILE CAT [ EXH 18 ]",
  "werewolf howls. [ EXH 18 ]",

  "Broken 8cmix [ HVN 18 ]",
  "Evans VolteX Pf arrange [ HVN 18 ]",
  "Onigo [ HVN 18 ]",
  "The world of sound [ HVN 18 ]",
  "V.I.P. [ HVN 18 ]",
  "金縛りの逢を [ HVN 18 ]",
  "腐れ外道とチョコレゐト [ HVN 18 ]",
  "幻想のサテライト [ HVN 18 ]",
  "孤独の番人 [ HVN 18 ]",
  "Absurd Gaff [ GRV 18 ]",
  "PANIC HOLIC [ GRV 18 ]",
  "Xepher Light and Darkness Dragon Remix [ GRV 18 ]",
  "魔理沙は大変なものを盗んでいきました [ GRV 18 ]",
  "croiX [ INF 18 ]",
  "FLOWER REDALiCE Remix [ INF 18 ]",
  "Max Burning!! [ INF 18 ]",
  "冥 Rockin' SWING REMIX [ INF 18 ]"

];

xi = songlists18.length; // 곡 갯수
xxi.innerHTML = "전체 곡 "+ xi +"곡";

function input() {
  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlists18[Math.floor(Math.random()*(xi-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};
