var songlists18 = [
  "Across the Starlight [ MXM 18 ]",
  "AIM HIGHER [ MXM 18 ]",
  "Air [ MXM 18 ]",
  "All for One [ MXM 18 ]",
  "Archangelio [ MXM 18 ]",
  "Battle Against a True Hero\n/ 本物のヒーローとの戦い [ MXM 18 ]",
  "Bigbang Faker [ MXM 18 ]",
  "c2Theater [ MXM 18 ]",
  "Cappuccino Hearts [ MXM 18 ]",
  "Chat perché [ MXM 18 ]",
  "€omet popcorn [ VVD 18 ]",
  "Corrupting Wonderland [ MXM 18 ]",
  "Crystalia [ MXM 18 ]",
  "DATAERR0R [ MXM 18 ]",
  "Decadence Mission [ MXM 18 ]",
  "Destined Marionette [ MXM 18 ]",
  "Destr0yer [ MXM 18 ]",
  "EGOISM 440 (Ange;art remix) [ MXM 18 ]",
  "Elemental Creation -xiRemix- [ MXM 18 ]",
  "EMERALDAS (Yuta Imai Remix) [ MXM 18 ]",
  "#EmoCloche [ MXM 18 ]",
  "End of Guilty [ MXM 18 ]",
  "ENDGAME [ MXM 18 ]",
  "FAR GONE [ MXM 18 ]",
  "FEEL THE FORCE [ MXM 18 ]",
  "Fegrix [ MXM 18 ]",
  "Finale / フィナーレ [ MXM 18 ]",
  "G4ME OVEЯ [ MXM 18 ]",
  "Going My Future! [ MXM 18 ]",
  "GOODTEK [ MXM 18 ]",
  "graduation [ MXM 18 ]",
  "Grandeur [ MXM 18 ]",
  "Halloween Is Chaos [ MXM 18 ]",
  "Hurt me plenty [ VVD 18 ]",
  "Hydroblast [ MXM 18 ]",
  "Ice Fortress [ MXM 18 ]",
  "Imperator [ MXM 18 ]",
  "Initiating League [ MXM 18 ]",
  "Innocent Azure [ MXM 18 ]",
  "Kontrol Line [ MXM 18 ]",
  "Lost Parliament [ MXM 18 ]",
  "Macuilxochitl (Latin Jazz Mix) [ MXM 18 ]",
  "MEGALOVANIA [ MXM 18 ]",
  "Memory Flow [ MXM 18 ]",
  "Metagame Matador [ MXM 18 ]",
  "MURASAME [ MXM 18 ]",
  "ИADIR [ MXM 18 ]",
  "#Namescapes [ MXM 18 ]",
  "Never Ending Future [ MXM 18 ]",
  "nostos -ark remix- [ MXM 18 ]",
  "NOT YOUR IDOL [ MXM 18 ]",
  "ØƵ [ MXM 18 ]",
  "party:stage [ MXM 18 ]",
  "Perfect Ultimate Celebration!! [ MXM 18 ]",
  "PHOTON BLAXT [ MXM 18 ]",
  "POSSESSION (Aoi Q.E.D. RMX) [ MXM 18 ]",
  "PSYCHO+HEROES [ VVD 18 ]",
  "Puni Puni Parade [ MXM 18 ]",
  "Pure Ruby [ MXM 18 ]",
  "R.I.P.ゴシップの海 [ MXM 18 ]",
  "Red＋White＝Kawaii [ MXM 18 ]",
  "refluxio [ MXM 18 ]",
  "Refrain [ MXM 18 ]",
  "Restless Waitress [ MXM 18 ]",
  "Revvable Engine [ MXM 18 ]",
  "ROZELCIA [ MXM 18 ]",
  "SAVE the World [ MXM 18 ]",
  "Scars of FAUNA(ろひ Remix) [ MXM 18 ]",
  "Scat Jazz Dance [ MXM 18 ]",
  "SHARK ATTACK [ MXM 18 ]",
  "SHOCKER BREAKER [ MXM 18 ]",
  "Snowmelt [ MXM 18 ]",
  "Souhait bleu [ MXM 18 ]",
  "SPECIAL SUMMER CAMPAIGN! [ MXM 18 ]",
  "Stairway to the sun [ MXM 18 ]",
  "Star☆Beat [ MXM 18 ]",
  "STEEL NEEDLE [ MXM 18 ]",
  "STIGMA [ MXM 18 ]",
  "SuperMiracleEnsemble [ MXM 18 ]",
  "Test Flight [ MXM 18 ]",
  "The King Of Red [ MXM 18 ]",
  "THE WORLD REVOLVING [ MXM 18 ]",
  "Triple Cross [ MXM 18 ]",
  "Twinkle Rookie [ MXM 18 ]",
  "Unleashed Redness [ MXM 18 ]",
  "Vallasotiena [ MXM 18 ]",
  "Vanishing Eidos [ MXM 18 ]",
  "Verflucht [ MXM 18 ]",
  "WARNING×WARNING×WARNING [ MXM 18 ]",
  "White Stream [ MXM 18 ]",
  "Wings to fly high [ MXM 18 ]",
  "WINNING ROAD [ MXM 18 ]",
  "XXanadu#climaXX [ MXM 18 ]",
  "Your SOUL Is Mine [ VVD 18 ]",
  "あいあむなんばーわんパトラちゃん様 [ MXM 18 ]",
  "ゔぉるみっくす!!!! [ MXM 18 ]",
  "カジノファイヤーことみちゃん [ MXM 18 ]",
  "スカーレット警察のゲットーパトロール24時 [ MXM 18 ]",
  "ナミカレ [ MXM 18 ]",
  "ばらんが!!!! [ MXM 18 ]",
  "プナイプナイたいそう [ MXM 18 ]",
  "フリコドウル [ MXM 18 ]",
  "ホイホイ☆幻想ホロイズム [ MXM 18 ]",
  "まみむめ🍄まるっと🍄まっしゅるーむ🍄🍄 [ MXM 18 ]",
  "ユメブキ [ MXM 18 ]",
  "ラヴ♡チャンス!! [ MXM 18 ]",
  "りむむむむむむ [ MXM 18 ]",
  "藍の華 [ MXM 18 ]",
  "過去に囚われている [ MXM 18 ]",
  "光風霽月 [ MXM 18 ]",
  "極夜、暁を望んで [ MXM 18 ]",
  "限界突破リザレクション [ MXM 18 ]",
  "～仔羊のナヴァラン・クリシェを添えて～ [ MXM 18 ]",
  "最果ての勇者にラブソングを [ MXM 18 ]",
  "灼ナル刃、破カヰ譜 [ MXM 18 ]",
  "蝕 [ MXM 18 ]",
  "神罰 [ MXM 18 ]",
  "天弓天華オトハナビ [ MXM 18 ]",
  "涙の女神と無形のエトワル [ MXM 18 ]",
  "二分間の世界 [ MXM 18 ]",
  "緋色月下、狂咲ノ絶 (nayuta 2017 ver) [ MXM 18 ]",
  "爆烈歓迎♪エクストリーム飲茶旋風脚ッ!! [ MXM 18 ]",
  "火狐之舞 [ MXM 18 ]",
  "夢幻泡影 [ MXM 18 ]",
  "恋愛♡悪戯！？まじかる☆ぱふゅ～む！！ [ MXM 18 ]",
  "Bl∞min' [ EXH 18 ]",
  "MixxioN [ EXH 18 ]",
  "《Re:miniscence》 [ EXH 18 ]",
  "XHRONOXAPSULΞ [ EXH 18 ]",
  "You Are My Best RivaL!! [ EXH 18 ]",
  "いまきみに [ EXH 18 ]",
  "Φnd:you [ MXM 18 ]",
  "Aerial Fortress [ MXM 18 ]",
  "apo:llioth [ MXM 18 ]",
  "ARROW RAIN [ MXM 18 ]",
  "Atropa bella-donna [ MXM 18 ]",
  "Aurolla [ MXM 18 ]",
  "Barbatos [ MXM 18 ]",
  "Barbless Ego [ GRV 18 ]",
  "Believe In Yourself [ GRV 18 ]",
  "Black Lotus [ MXM 18 ]",
  "Blessing Bouquet [ MXM 18 ]",
  "Bolérrot [ MXM 18 ]",
  "Butterfly Twist [ MXM 18 ]",
  "Call of the World [ MXM 18 ]",
  "Cloud Crasher [ GRV 18 ]",
  "Cynical Joker [ MXM 18 ]",
  "Defining Future [ MXM 18 ]",
  "Dogeza Stairs [ MXM 18 ]",
  "eighth-slave [ MXM 18 ]",
  "Electric Injury [ VVD 18 ]",
  "Elemental Creation (kamome sano Remix) [ MXM 18 ]",
  "Enchanté [ MXM 18 ]",
  "eternite [ MXM 18 ]",
  "Ethereal Lotus [ MXM 18 ]",
  "FIRST：DREAMS [ MXM 18 ]",
  "GALAXY BURST [ MXM 18 ]",
  "GaLaXyEggPlanT [ MXM 18 ]",
  "GEMINI LA2ER [ MXM 18 ]",
  "Glorious Journey [ MXM 18 ]",
  "Ichi-Go! DX Pancake! [ VVD 18 ]",
  "Innocent [ MXM 18 ]",
  "Jack-the-Ripper◆ [ MXM 18 ]",
  "Jacob’s Elevator [ MXM 18 ]",
  "JǛPITΨR ♃ GЯÃVITÝ [ MXM 18 ]",
  "Katharsis [ MXM 18 ]",
  "L9 [ MXM 18 ]",
  "Lazurite [ MXM 18 ]",
  "LECTORIA [ MXM 18 ]",
  "Leviathan [ MXM 18 ]",
  "lEyl [ MXM 18 ]",
  "Liar rain [ GRV 18 ]",
  "m1dy Deluxe [ MXM 18 ]",
  "memento mori -intro- [ MXM 18 ]",
  "METATRON [ MXM 18 ]",
  "MeteorA [ MXM 18 ]",
  "mqlo [ MXM 18 ]",
  "Mynarco(Nagomu 2Step Remix) [ MXM 18 ]",
  "Nebulas [ MXM 18 ]",
  "New Decade [ MXM 18 ]",
  "Nhelv [ MXM 18 ]",
  "On take SUN [ MXM 18 ]",
  "Our Love [ MXM 18 ]",
  "Over The Top [ VVD 18 ]",
  "ΩVERFLOW [ MXM 18 ]",
  "OZONE [ GRV 18 ]",
  "PARTY TIME! [ MXM 18 ]",
  "petits fours [ MXM 18 ]",
  "pique [ MXM 18 ]",
  "Pulsar [ MXM 18 ]",
  "Re：Elemental Creation [ MXM 18 ]",
  "Яe:son D'être [ MXM 18 ]",
  "rE:Voltagers [ GRV 18 ]",
  "Ring!Run!Nyan!! [ VVD 18 ]",
  "SAMURAI TIGER [ MXM 18 ]",
  "SLEEPWALKER [ VVD 18 ]",
  "SociuS [ MXM 18 ]",
  "Sudden Visitor [ MXM 18 ]",
  "Symphonic Tear [ MXM 18 ]",
  "Teufel [ MXM 18 ]",
  "Thank you for your playing music [ MXM 18 ]",
  "To:BrandNewDeadline [ MXM 18 ]",
  "Turn the story [ MXM 18 ]",
  "Typhoon Craaash!! [ GRV 18 ]",
  "Übertreffen [ MXM 18 ]",
  "V Sen5eS [ MXM 18 ]",
  "Valanga(polysha Remix) [ MXM 18 ]",
  "Valkyrja ~Aldrlag~ [ MXM 18 ]",
  "Vividly Impromptu [ MXM 18 ]",
  "With It This Heaven? [ MXM 18 ]",
  "World of Iris [ VVD 18 ]",
  "Xicholauncher [ MXM 18 ]",
  "ZEИITH [ MXM 18 ]",
  "αρχη [ MXM 18 ]",
  "アオアラシ [ MXM 18 ]",
  "おはようからおやすみまでかまってポメポメ [ VVD 18 ]",
  "タイムトラベル [ GRV 18 ]",
  "ツマミ戦隊 タテレンジャー [ MXM 18 ]",
  "トマヨイ [ VVD 18 ]",
  "ねこみみ(=ФωФ=)ぱんでみみっく [ GRV 18 ]",
  "び [ MXM 18 ]",
  "プログレなぞなぞクイズのテーマ [ MXM 18 ]",
  "ミッドナイト☆WAR [ MXM 18 ]",
  "ミュージックプレイヤー [ MXM 18 ]",
  "ランカーキラーガール [ MXM 18 ]",
  "怪盗Ｆの台本～消えたダイヤの謎～ [ MXM 18 ]",
  "蛇神 [ MXM 18 ]",
  "月々紅花 [ VVD 18 ]",
  "狂水一華 [ MXM 18 ]",
  "最小三倍完全数 [ MXM 18 ]",
  "消失(Hommarju Remix) [ MXM 18 ]",
  "翠雨の祷 [ MXM 18 ]",
  "諏訪大信仰 [ MXM 18 ]",
  "世界の果てに約束の凱歌を -VOLTEX Mix- [ MXM 18 ]",
  "春告胡蝶 [ MXM 18 ]",
  "星の透る夏空に願う [ MXM 18 ]",
  "無魎大数 [ MXM 18 ]",
  "666 [ EXH 18 ]",
  "ΣgØ [ EXH 18 ]",
  "* Erm, could it be a Spatiotemporal\n　ShockWAVE Syndrome...? [ EXH 18 ]",
  "MAYHEM [ EXH 18 ]",
  "VVelcome!! [ EXH 18 ]",
  "Akzeriyyuth [ MXM 18 ]",
  "ALTONA [ GRV 18 ]",
  "Be a Hero! [ MXM 18 ]",
  "BEAST BASS BOMB [ MXM 18 ]",
  "Beyond the BLUE [ MXM 18 ]",
  "Black night [ MXM 18 ]",
  "BLAZING_LAZER [ MXM 18 ]",
  "BlueMoon Princess [ MXM 18 ]",
  "Boss Rush [ MXM 18 ]",
  "Breakin' Asia [ MXM 18 ]",
  "Catch Our Fire! [ MXM 18 ]",
  "Cepheus [ MXM 18 ]",
  "CHERNOBOG [ MXM 18 ]",
  "Cloud 9 [ MXM 18 ]",
  "Concertino in Blue [ MXM 18 ]",
  "crossing blue [ MXM 18 ]",
  "Destiny [ MXM 18 ]",
  "Divine's:Bugscript [ MXM 18 ]",
  "Divine's or Deal [ MXM 18 ]",
  "Doppelganger [ MXM 18 ]",
  "Dreadnought [ MXM 18 ]",
  "DropZ-Line- [ MXM 18 ]",
  "ECHIDNA [ MXM 18 ]",
  "Evans [ MXM 18 ]",
  "FIRE IN MY HEART [ MXM 18 ]",
  "FLOOR INFECTION Medley\n　from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "GAIA [ MXM 18 ]",
  "Gamerz FestivaL [ MXM 18 ]",
  "Gate of Atlantis [ MXM 18 ]",
  "GERBERA [ MXM 18 ]",
  "Ghost Trigger [ MXM 18 ]",
  "Glitter Flatter Scatter [ MXM 18 ]",
  "Goddess Bless you [ MXM 18 ]",
  "Gorgetech [ MXM 18 ]",
  "Grand-Guignol [ MXM 18 ]",
  "HP:1 [ MXM 18 ]",
  "Hug!! Vs. Hug!! [ MXM 18 ]",
  "ΗУМЛ [ MXM 18 ]",
  "Juggler's Maddness [ MXM 18 ]",
  "JUNKIE FLAVOR [ MXM 18 ]",
  "Khionos TiARA [ MXM 18 ]",
  "KIMIDORI Streak!! [ MXM 18 ]",
  "LastΩmegA [ MXM 18 ]",
  "Legendary Road [ MXM 18 ]",
  "Levier'n NābYss [ MXM 18 ]",
  "Lowermost revolt [ MXM 18 ]",
  "Lunatic Sprinter [ MXM 18 ]",
  "Make Magic [ MXM 18 ]",
  "MeteorGlow Aftermath [ MXM 18 ]",
  "Midnight City Warfare [ MXM 18 ]",
  "Mirrorwall [ MXM 18 ]",
  "MODEL FT4 [ MXM 18 ]",
  "MONOLITH [ MXM 18 ]",
  "New Leaf [ MXM 18 ]",
  "Nexta [ GRV 18 ]",
  "Night Rockin' Bird [ MXM 18 ]",
  "Noisy Minority [ MXM 18 ]",
  "Nostalgic Blood of the Strife [ MXM 18 ]",
  "OPEN MY GATE [ MXM 18 ]",
  "ouroboros -twin stroke of the end- [ MXM 18 ]",
  "ΩVERSOUL [ MXM 18 ]",
  "POLICY BREAK Medley\n　from SOUND VOLTEX×jubeat [ MXM 18 ]",
  "Prey [ MXM 18 ]",
  "PROVOES*PROPOSE <<êl fine>> [ GRV 18 ]",
  "Puberty Dysthymia [ MXM 18 ]",
  "PUPA [ MXM 18 ]",
  "Re:End of a Dream [ MXM 18 ]",
  "Яe's NoVǢ [ MXM 18 ]",
  "Rebellio [ MXM 18 ]",
  "Reb∞t [ GRV 18 ]",
  "REDO the NIGHT [ GRV 18 ]",
  "Redshift [ MXM 18 ]",
  "RHYZING BEAT [ MXM 18 ]",
  "Sacrifice and Faith [ MXM 18 ]",
  "SACRIFICE feat.ayame [ MXM 18 ]",
  "SAtAN [ MXM 18 ]",
  "Scarlet Lance [ MXM 18 ]",
  "She Turns Me On [ GRV 18 ]",
  "Sky High [ MXM 18 ]",
  "#SpeedyCats [ MXM 18 ]",
  "Spirit of the Beast [ MXM 18 ]",
  "STULTI [ MXM 18 ]",
  "SUPER SUMMER SALE [ MXM 18 ]",
  "Sweet Requiem [ MXM 18 ]",
  "Taiko Drum Monster [ MXM 18 ]",
  "The Formula [ MXM 18 ]",
  "The Golden Era [ MXM 18 ]",
  "THE HEAVEN [ MXM 18 ]",
  "Theme of Ricerca [ MXM 18 ]",
  "Touch My Body [ MXM 18 ]",
  "TRICKL4SH 220 [ MXM 18 ]",
  "ULTiMATE INFLATiON [ MXM 18 ]",
  "ULTRAVELOCITY [ MXM 18 ]",
  "V [ MXM 18 ]",
  "Venomous Firefly [ MXM 18 ]",
  "Victim of Nights [ MXM 18 ]",
  "We Go Down [ MXM 18 ]",
  "Wings of Glory [ MXM 18 ]",
  "Xevel [ MXM 18 ]",
  "Yum Yum Sweetie [ MXM 18 ]",
  "お米の美味しい炊き方、\n　そしてお米を食べることによるその効果。 [ MXM 18 ]",
  "オニユリ [ MXM 18 ]",
  "キュリオシティ [ MXM 18 ]",
  "サイコパスラビット [ MXM 18 ]",
  "スラッシュ//シスターズ [ MXM 18 ]",
  "セイクリッド ルイン [ MXM 18 ]",
  "そして黄金郷へ [ MXM 18 ]",
  "ドリームエンド・サバイバー [ MXM 18 ]",
  "のぼれ八坂坂！ [ MXM 18 ]",
  "びいすと！ [ MXM 18 ]",
  "ファイナルレター [ MXM 18 ]",
  "ホワイトパレード [ MXM 18 ]",
  "まじかる生主＠りすなちゃん [ GRV 18 ]",
  "メイビ～初恋！？ビスケット☆大作戦 [ MXM 18 ]",
  "ワールズエンド・ダンスホール [ MXM 18 ]",
  "怒槌 [ MXM 18 ]",
  "永遠に幸せになる方法、見つけました。 [ MXM 18 ]",
  "壊Rave*it!! 壊Rave*it!! [ MXM 18 ]",
  "神獄烙桜 [ MXM 18 ]",
  "恋歌疾風！かるたクイーンいろは [ MXM 18 ]",
  "業焔繚乱 [ GRV 18 ]",
  "極彩天奏 [ MXM 18 ]",
  "祝福の色彩は想い結ぶ君たち迄 [ MXM 18 ]",
  "準備運動 [ MXM 18 ]",
  "神話に芽吹く [ MXM 18 ]",
  "水簾ノ調 [ MXM 18 ]",
  "誰が為に兎は舞う＝狂速狂騒曲＝ [ MXM 18 ]",
  "超☆超☆光☆速☆出☆前☆最☆速!!!\n　スピード★スター★かなで [ MXM 18 ]",
  "†渚の小悪魔ラヴリィ～レイディオ† [ MXM 18 ]",
  "光射す澪のユズリハ [ MXM 18 ]",
  "真っ白な靴 [ GRV 18 ]",
  "雷鼓サンダービート [ MXM 18 ]",
  "ΣmbryØ [ EXH 18 ]",
  "*Feels Seasickness...* [ EXH 18 ]",
  "FIN4LE ～終止線の彼方へ～ [ EXH 18 ]",
  "Fin.ArcDeaR [ EXH 18 ]",
  "I [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY\n　-HISTORIA SOUND VOLTEX- Empress Side [ EXH 18 ]",
  "WHITEOUT [ EXH 18 ]",
  "Xronièr [ EXH 18 ]",
  "Le Fruit Défendu [ XCD 18 ]",
  "The star in eclipse [ XCD 18 ]",
  "ちくわパフェだよ☆ＣＫＰ [ XCD 18 ]",
  "Garakuta Doll Play [ HVN 18 ]",
  "Angelic Jelly [ GRV 18 ]",
  "Celestial stinger [ GRV 18 ]",
  "Completeness Under Incompleteness [ GRV 18 ]",
  "HAELE III ~Angel Worlds~ [ GRV 18 ]",
  "KAC 2012 ULTIMATE MEDLEY\n　-HISTORIA SOUND VOLTEX- [ GRV 18 ]",
  "NEO TREASON [ GRV 18 ]",
  "Ok!! Hug Me [ GRV 18 ]",
  "Opium and Purple haze [ GRV 18 ]",
  "Renegade Fruits [ GRV 18 ]",
  "Triple Counter [ GRV 18 ]",
  "XROSS THE XOUL [ GRV 18 ]",
  "↓↓↓ [ EXH 18 ]",
  "ΑΩ [ EXH 18 ]",
  "Angels And Demons [ EXH 18 ]",
  "Blastix Riotz [ EXH 18 ]",
  "Demise Quartet [ EXH 18 ]",
  "EMPIRE OF FLAME [ EXH 18 ]",
  "#Endroll [ EXH 18 ]",
  "End to end [ EXH 18 ]",
  "Endless GRAVITY [ EXH 18 ]",
  "Firestorm [ EXH 18 ]",
  "FLOWER [ EXH 18 ]",
  "FLügeL《Λrp:ΣggyØ》 [ EXH 18 ]",
  "Fox4-Raize- [ EXH 18 ]",
  "GEOMETRIA [ EXH 18 ]",
  "gigadelic(かめりあ's ''The TERA'' RMX) [ EXH 18 ]",
  "HAVOX [ EXH 18 ]",
  "IKAROS DYNAMITE!!!! [ EXH 18 ]",
  "INF-B《L-aste-R》 [ EXH 18 ]",
  "Invitation from Mr.C [ EXH 18 ]",
  "JEHANNEDARC [ EXH 18 ]",
  "KAC 2013 ULTIMATE MEDLEY\n　-HISTORIA SOUND VOLTEX- Emperor Side [ EXH 18 ]",
  "Lachryma《Re:Queen'M》 [ EXH 18 ]",
  "LegenD. [ EXH 18 ]",
  "MG277 [ EXH 18 ]",
  "NEO GRAVITY [ EXH 18 ]",
  "Ops:Code-Rapture- [ EXH 18 ]",
  "Pon-Pon-Pompoko Dai-Sen-Saw! [ EXH 18 ]",
  "Prayer [ EXH 18 ]",
  "Preserved Valkyria [ EXH 18 ]",
  "Quaint Echo [ EXH 18 ]",
  "REVOLVER [ EXH 18 ]",
  "Sayonara Planet Wars [ EXH 18 ]",
  "Seraphim [ EXH 18 ]",
  "Solar Storm [ EXH 18 ]",
  "tricky trick [ EXH 18 ]",
  "Ultimate Ascension [ EXH 18 ]",
  "UnivEarth [ EXH 18 ]",
  "veRtrageS [ EXH 18 ]",
  "Warriors Aboot [ EXH 18 ]",
  "World's end [ EXH 18 ]",
  "XHAOS JUDGE [ EXH 18 ]",
  "XyHATTE [ EXH 18 ]",
  "アルティメットトゥルース -Phantasm- [ EXH 18 ]",
  "きたさいたま2000 [ EXH 18 ]",
  "ドーパミン [ EXH 18 ]",
  "マサカリブレイド [ EXH 18 ]",
  "ムラサキグルマ [ EXH 18 ]",
  "極圏 [ EXH 18 ]",
  "月光乱舞 [ EXH 18 ]",
  "混乱少女♥そふらんちゃん!! [ EXH 18 ]",
  "侍Annihilate!! [ EXH 18 ]",
  "灼熱Beach Side Bunny [ EXH 18 ]",
  "消失 [ EXH 18 ]",
  "絶対零度 [ EXH 18 ]",
  "到達してしまった僕らと夢と希望の最之果 [ EXH 18 ]",
  "東方妖々夢 ULTIMATE MEDLEY [ EXH 18 ]",
  "伐折羅-vajra- [ EXH 18 ]",
  "冥天・ヘメロカリス [ EXH 18 ]",
  "crazy cinema story [ XCD 18 ]",
  "Foolish Hero [ XCD 18 ]",
  "#Fairy_dancing_in_lake [ VVD 18 ]",
  "Joyeuse [ VVD 18 ]",
  "Sakura Reflection (P*Light Slayer Remix) [ VVD 18 ]",
  "She is my wife\n　すーぱーアイドル☆ミツル子Remixちゃん [ VVD 18 ]",
  "Unicorn tail Dustboxxxx RMX [ VVD 18 ]",
  "おお われら喜び讃うべし、主よ [ VVD 18 ]",
  "こちら、幸福安心委員会です。 [ VVD 18 ]",
  "ムーニャポヨポヨスッポコニャーゴ [ VVD 18 ]",
  "上海紅茶館～ Chinese Tea Orchid Remix [ VVD 18 ]",
  "C18H27NO3 [ HVN 18 ]",
  "Harpuia [ HVN 18 ]",
  "Idola [ HVN 18 ]",
  "Qubism [ HVN 18 ]",
  "超越してしまった彼女と其を生み落した理由 [ HVN 18 ]",
  "魔境堕天録サリエル [ HVN 18 ]",
  "CODE -CRiMSON- [ GRV 18 ]",
  "Crack Traxxxx [ GRV 18 ]",
  "Hellfire [ GRV 18 ]",
  "Last Concerto [ GRV 18 ]",
  "Wish upon Twin Stars [ GRV 18 ]",
  "最終鬼畜妹フランドール・S [ GRV 18 ]",
  "Bangin' Burst [ EXH 18 ]",
  "Black Emperor [ EXH 18 ]",
  "BLACK or WHITE? [ EXH 18 ]",
  "For UltraPlayers [ EXH 18 ]",
  "Growth Memories [ EXH 18 ]",
  "INSECTICIDE [ EXH 18 ]",
  "VALLIS-NERIA [ EXH 18 ]",
  "VILE CAT [ EXH 18 ]",
  "werewolf howls. [ EXH 18 ]",
  "neu BSP style [ XCD 18 ]",
  "物凄い勢いでけーねが物凄いうた [ XCD 18 ]",
  "Broken 8cmix [ HVN 18 ]",
  "Evans VolteX Pf arrange [ HVN 18 ]",
  "Onigo [ HVN 18 ]",
  "The world of sound [ HVN 18 ]",
  "V.I.P. [ HVN 18 ]",
  "金縛りの逢を [ HVN 18 ]",
  "腐れ外道とチョコレゐト [ HVN 18 ]",
  "幻想のサテライト [ HVN 18 ]",
  "孤独の番人 [ HVN 18 ]",
  "Absurd Gaff [ GRV 18 ]",
  "PANIC HOLIC [ GRV 18 ]",
  "Xepher Light and Darkness Dragon REMIX [ GRV 18 ]",
  "魔理沙は大変なものを盗んでいきました [ GRV 18 ]",
  "croiX [ INF 18 ]",
  "FLOWER REDALiCE Remix [ INF 18 ]",
  "Max Burning!! [ INF 18 ]",
  "冥 Rockin' SWING REMIX [ INF 18 ]"
];

var songlists19 = [
  "2 Beasts Unchained [ MXM 19 ]",
  "777 [ MXM 19 ]",
  "AμreoLe ~for Triumph~ [ MXM 19 ]",
  "Avalanx [ MXM 19 ]",
  "αzalea [ MXM 19 ]",
  "Bad Elixir [ MXM 19 ]",
  "BAYONEX [ MXM 19 ]",
  "Chronomia [ MXM 19 ]",
  "CLAMARE [ MXM 19 ]",
  "EncorE & cALL [ MXM 19 ]",
  "Fαtα∠ Ent∠mEnt [ MXM 19 ]",
  "Holy Trail [ MXM 19 ]",
  "[ ]DENTITY [ MXM 19 ]",
  "LaμreLs ~the Angelus~ [ MXM 19 ]",
  "onslaught -Retaliation of Bahamūt- [ MXM 19 ]",
  "perditus†paradisus [ MXM 19 ]",
  "Rapsodia d'amore [ MXM 19 ]",
  "Reverenced Flower [ MXM 19 ]",
  "Rhapsody ⚙f Triumph [ MXM 19 ]",
  "The Clown of 24stairs [ MXM 19 ]",
  "VALKYRIE ASSAULT [ MXM 19 ]",
  "VΛZiLiSQ [ MXM 19 ]",
  "VOLAQUAS [ MXM 19 ]",
  "Xb10r [ MXM 19 ]",
  "ZEUS [ MXM 19 ]",
  "すべてが幻になった後で [ MXM 19 ]",
  "ディスコルディア [ MXM 19 ]",
  "ドゥサンコオデッセイ!! [ MXM 19 ]",
  "ピアノ協奏曲第１番”蠍火” [ MXM 19 ]",
  "ピアノ独奏無言歌 ”灰燼” [ MXM 19 ]",
  "赫焉 [ MXM 19 ]",
  "紫焔双穿 [ MXM 19 ]",
  "十の試煉 [ MXM 19 ]",
  "竹 [ MXM 19 ]",
  "9TH5IN [ MXM 19 ]",
  "ANGER of the GOD [ MXM 19 ]",
  "Calamity Tempest [ MXM 19 ]",
  "Daisycutter [ MXM 19 ]",
  "ENDYMION [ MXM 19 ]",
  "Ghost Family Living In Graveyard [ MXM 19 ]",
  "Lancelot ～Flame of the Rebellion～ [ MXM 19 ]",
  "Lisa-RICCIA [ MXM 19 ]",
  "LubedeR [ MXM 19 ]",
  "ΛΛemoria [ MXM 19 ]",
  "†:OLPHEUX:† [ MXM 19 ]",
  "OUTERHEΛVEN [ MXM 19 ]",
  "Redshift 2nd Ignition [ MXM 19 ]",
  "ЯeviveR [ MXM 19 ]",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY [ MXM 19 ]",
  "THE凸GENERATOR [ MXM 19 ]",
  "Trill auf G [ MXM 19 ]",
  "voltississimo [ MXM 19 ]",
  "Xroniàl Xéro [ MXM 19 ]",
  "θコトノハθカプセルθ [ MXM 19 ]",
  "色を喪った街 [ MXM 19 ]",
  "卑弥呼 [ MXM 19 ]",
  "飄える翼追い掛けて [ MXM 19 ]",
  "A Lasting Promise [ MXM 19 ]",
  "Absolute Domination [ MXM 19 ]",
  "Awakening [ MXM 19 ]",
  "BELOBOG [ MXM 19 ]",
  "Chrono Diver -PENDULUMs- [ MXM 19 ]",
  "Cross Fire [ MXM 19 ]",
  "Deadly force [ MXM 19 ]",
  "Dyscontrolled Galaxy [ MXM 19 ]",
  "Elemental Creation [ MXM 19 ]",
  "Failnaught [ MXM 19 ]",
  "Fin.ArcDeaR [ MXM 19 ]",
  "Fly Like You [ MXM 19 ]",
  "FREEDOM DiVE [ MXM 19 ]",
  "GERBERA -For Finalists- [ MXM 19 ]",
  "GODHEART [ MXM 19 ]",
  "Immortal saga [ MXM 19 ]",
  "KAC 2013 ULTIMATE MEDLEY\n　-HISTORIA SOUND VOLTEX- Empress Side [ MXM 19 ]",
  "Last Resort [ MXM 19 ]",
  "Sailing Force [ MXM 19 ]",
  "Staring at star [ MXM 19 ]",
  "TWO-TORIAL [ MXM 19 ]",
  "Xéroa [ MXM 19 ]",
  "セイレーン ～悲壮の竪琴～ [ MXM 19 ]",
  "逆月 [ MXM 19 ]",
  "2 MINUTES FIGHTERS [ XCD 19 ]",
  "Invitation from Mr.C [ XCD 19 ]",
  "INF-B《L-aste-R》 [ VVD 19 ]",
  "FLOWER [ HVN 19 ]",
  "Got more raves？ [ HVN 19 ]",
  "きたさいたま2000 [ HVN 19 ]",
  "極圏 [ HVN 19 ]",
  "ΑΩ [ GRV 19 ]",
  "Blastix Riotz [ GRV 19 ]",
  "DIABLOSIS::Nāga [ GRV 19 ]",
  "Everlasting Message [ GRV 19 ]",
  "FLügeL《Λrp:ΣggyØ》 [ GRV 19 ]",
  "KAC 2013 ULTIMATE MEDLEY\n　-HISTORIA SOUND VOLTEX- Emperor Side [ GRV 19 ]",
  "Lord=Crossight [ GRV 19 ]",
  "Preserved Valkyria [ GRV 19 ]",
  "XyHATTE [ GRV 19 ]",
  "月光乱舞 [ GRV 19 ]",
  "Fiat Lux [ XCD 19 ]",
  "HYENA [ XCD 19 ]",
  "Innocent Tempest [ VVD 19 ]",
  "IX [ VVD 19 ]",
  "ラクガキスト [ VVD 19 ]",
  "音楽 -resolve- [ VVD 19 ]",
  "Booths of Fighters [ HVN 19 ]",
  "For UltraPlayers [ HVN 19 ]",
  "INSECTICIDE [ HVN 19 ]",
  "Quietus Ray [ HVN 19 ]",
  "Verse IV [ HVN 19 ]",
  "バンブーソード・ガール [ HVN 19 ]",
  "Bangin' Burst [ GRV 19 ]",
  "Black Emperor [ GRV 19 ]",
  "BLACK or WHITE? [ GRV 19 ]",
  "Growth Memories [ GRV 19 ]",
  "snow storm -euphoria- [ GRV 19 ]",
  "XROSS INFECTION [ GRV 19 ]",
  "大宇宙ステージ [ GRV 19 ]",
  "Ganymede kamome mix [ INF 19 ]"
];

var songlists1819 = new Array;
songlists1819 = songlists18.concat(songlists19);
xi = songlists1819.length; // 곡 갯수
xxi.innerHTML = "전체 곡 "+ xi +"곡";

function input() {
  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlists1819[Math.floor(Math.random()*(xi-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};
