var songlists18 = [
  "Across the Starlight (18)",
  "AIM HIGHER (18)",
  "Air (18)",
  "All for One (18)",
  "Amazing Mirage (18)",
  "Archangelio (18)",
  "Battle Against a True Hero / 本物のヒーローとの戦い (18)",
  "Bigbang Faker (18)",
  "birth (18)",
  "BLISS (18)",
  "Blossom (18)",
  "Brave Power Leader 《 = Voltage = 》 (18)",
  "c2Theater (18)",
  "CadenzaMaiden (18)",
  "Cappuccino Hearts (18)",
  "Chat perché (18)",
  "Corrupting Wonderland (18)",
  "Crystalia (18)",
  "D.I.X. (18)",
  "DATAERR0R (18)",
  "Decadence Mission (18)",
  "Destined Marionette (18)",
  "Destr0yer (18)",
  "Distorted Floor -Boosted- (18)",
  "EGOISM 440 (Ange;art remix) (18)",
  "Elemental Creation -xiRemix- (18)",
  "EMERALDAS (Yuta Imai Remix) (18)",
  "ΣMERGENCY CODΣ (18)",
  "#EmoCloche (18)",
  "End of Guilty (18)",
  "ENDGAME (18)",
  "ENERGY SYNERGY MATRIX (18)",
  "Enter The Rave (18)",
  "FAR GONE (18)",
  "FEEL THE FORCE (18)",
  "Fegrix (18)",
  "Finale / フィナーレ (18)",
  "Fl0ating: (18)",
  "G4ME OVEЯ (18)",
  "Garland (18)",
  "Going My Future! (18)",
  "GOODTEK (18)",
  "graduation (18)",
  "Grandeur (18)",
  "Halloween Is Chaos (18)",
  "Hello, Hologram (18)",
  "Hydroblast (18)",
  "Ice Fortress (18)",
  "Imperator (18)",
  "Initiating League (18)",
  "Innocent Azure (18)",
  "Juωpscare!! (18)",
  "KAMAITACHI (18)",
  "Kontrol Line (18)",
  "Lost Parliament (18)",
  "Macuilxochitl (Latin Jazz Mix) (18)",
  "Marielle (18)",
  "MEGALOVANIA (18)",
  "Memory Flow (18)",
  "Metagame Matador (18)",
  "MURASAME (18)",
  "ИADIR (18)",
  "#Namescapes (18)",
  "Never Ending Future (18)",
  "nostos -ark remix- (18)",
  "NOT YOUR IDOL (18)",
  "ØƵ (18)",
  "Paradigm Shift (18)",
  "party:stage (18)",
  "Perfect Ultimate Celebration!! (18)",
  "Petit espoir (18)",
  "PHOTON BLAXT (18)",
  "Please Welcome Mr.C (18)",
  "POSSESSION (Aoi Q.E.D. RMX) (18)",
  "Prayer (18)",
  "Puni Puni Parade (18)",
  "Pure Ruby (18)",
  "quaver♪ (18)",
  "R.I.P.ゴシップの海 (18)",
  "Red＋White＝Kawaii (18)",
  "refluxio (18)",
  "Refrain (18)",
  "Restless Waitress (18)",
  "Revvable Engine (18)",
  "ROZELCIA (18)",
  "SAVE the World (18)",
  "Scars of FAUNA(ろひ Remix) (18)",
  "Scat Jazz Dance (18)",
  "SHARK ATTACK (18)",
  "SHARK IMPACT (18)",
  "Shera (18)",
  "SHOCKER BREAKER (18)",
  "Snowmelt (18)",
  "Souhait bleu (18)",
  "SPECIAL SUMMER CAMPAIGN! (18)",
  "Stairway to the sun (18)",
  "Star☆Beat (18)",
  "S(TAR)²☆pistol (18)",
  "STEEL NEEDLE (18)",
  "stellar rain (18)",
  "STIGMA (18)",
  "Stylus (18)",
  "SuperMiracleEnsemble (18)",
  "suspicions (18)",
  "Test Flight (18)",
  "The EXworld of sound (18)",
  "The King Of Red (18)",
  "THE PEERLESS UNDER HEAVEN (18)",
  "THE WORLD REVOLVING (18)",
  "Thousand Triggers (18)",
  "Tickled Pink (18)",
  "trea→journey (18)",
  "Triple Cross (18)",
  "Twinkle Rookie (18)",
  "Unleashed Redness (18)",
  "Vallasotiena (18)",
  "Vanishing Eidos (18)",
  "Verflucht (18)",
  "Voice 7 Voice!!!!!!! (18)",
  "WARNING×WARNING×WARNING (18)",
  "Welcome to the Mosh Pit (18)",
  "White Stream (18)",
  "Wings to fly high (18)",
  "WINNING ROAD (18)",
  "XXanadu#climaXX (18)",
  "Zero-Day Exploit(One-Day Fusion Mix) (18)",
  "あいあむなんばーわんパトラちゃん様 (18)",
  "アガット (18)",
  "イグノアザーズ (18)",
  "うぇるかむ -||祭みっくす||- (18)",
  "ゔぉるみっくす!!!! (18)",
  "カジノファイヤーことみちゃん (18)",
  "スカーレット警察のゲットーパトロール24時 (18)",
  "ナミカレ (18)",
  "パーフェクトイーター (18)",
  "ハッピーエンド (18)",
  "ばらんが!!!! (18)",
  "プナイプナイたいそう (18)",
  "フリコドウル (18)",
  "ホイホイ☆幻想ホロイズム (18)",
  "ませまてぃっく♡ま＋ま＝まじっく！～徹夜の追込みエナジーまっくす！～ (18)",
  "マツヨイナイトバグ (18)",
  "まみむめ🍄まるっと🍄まっしゅるーむ🍄🍄 (18)",
  "ユメブキ (18)",
  "ラヴ♡チャンス!! (18)",
  "りむむむむむむ (18)",
  "リュミレイラ (18)",
  "リリーゼと炎龍レーヴァテイン (18)",
  "藍の華 (18)",
  "過去に囚われている (18)",
  "過去を喰らう (18)",
  "光風霽月 (18)",
  "極夜、暁を望んで (18)",
  "劇場版ムーニャポヨポヨスッポコニャーゴ~侵略だいず帝国！ドラマティック宇宙大戦争~ (18)",
  "限界突破リザレクション (18)",
  "～仔羊のナヴァラン・クリシェを添えて～ (18)",
  "最果ての勇者にラブソングを (18)",
  "十三不塔 (18)",
  "灼ナル刃、破カヰ譜 (18)",
  "少年リップルズ (18)",
  "蝕 (18)",
  "神罰 (18)",
  "天弓天華オトハナビ (18)",
  "天穹のアルカナビット (18)",
  "涙の女神と無形のエトワル (18)",
  "二分間の世界 (18)",
  "儚キ戀ノ幻想譚 (18)",
  "爆烈歓迎♪エクストリーム飲茶旋風脚ッ!! (18)",
  "緋色月下、狂咲ノ絶 (nayuta 2017 ver) (18)",
  "火狐之舞 (18)",
  "禊 (18)",
  "夢幻泡影 (18)",
  "累乗のカルマ (18)",
  "零天視 (18)",
  "恋愛♡悪戯！？まじかる☆ぱふゅ～む！！ (18)",
  "忘れないように、失くさないように (18)",
  "APØCALYPSE RAY (18)",
  "Bl∞min' (18)",
  "HeaveИ's Rain (18)",
  "MixxioN (18)",
  "《Re:miniscence》 (18)",
  "SuddeИDeath (18)",
  "XHRONOXAPSULΞ (18)",
  "You Are My Best RivaL!! (18)",
  "いまきみに (18)",
  "Φnd:you (18)",
  "Aerial Fortress (18)",
  "apo:llioth (18)",
  "ARROW RAIN (18)",
  "Atropa bella-donna (18)",
  "Aurolla (18)",
  "Barbatos (18)",
  "Black Lotus (18)",
  "Blessing Bouquet (18)",
  "Bolérrot (18)",
  "Butterfly Twist (18)",
  "Call of the World (18)",
  "Cynical Joker (18)",
  "Defining Future (18)",
  "Dogeza Stairs (18)",
  "eighth-slave (18)",
  "Elemental Creation (kamome sano Remix) (18)",
  "Enchanté (18)",
  "eternite (18)",
  "Ethereal Lotus (18)",
  "FIRST：DREAMS (18)",
  "GALAXY BURST (18)",
  "GaLaXyEggPlanT (18)",
  "GEMINI LA2ER (18)",
  "Glorious Journey (18)",
  "Innocent (18)",
  "Jack-the-Ripper◆ (18)",
  "Jacob’s Elevator (18)",
  "JǛPITΨR ♃ GЯÃVITÝ (18)",
  "Katharsis (18)",
  "L9 (18)",
  "Lazurite (18)",
  "LECTORIA (18)",
  "Leviathan (18)",
  "lEyl (18)",
  "m1dy Deluxe (18)",
  "memento mori -intro- (18)",
  "METATRON (18)",
  "MeteorA (18)",
  "mqlo (18)",
  "Mynarco(Nagomu 2Step Remix) (18)",
  "Nebulas (18)",
  "New Decade (18)",
  "Nhelv (18)",
  "On take SUN (18)",
  "Our Love (18)",
  "ΩVERFLOW (18)",
  "PARTY TIME! (18)",
  "petits fours (18)",
  "pique (18)",
  "Pulsar (18)",
  "Re：Elemental Creation (18)",
  "Яe:son D'être (18)",
  "SAMURAI TIGER (18)",
  "SociuS (18)",
  "Sudden Visitor (18)",
  "Symphonic Tear (18)",
  "Teufel (18)",
  "Thank you for your playing music (18)",
  "To:BrandNewDeadline (18)",
  "Turn the story (18)",
  "Übertreffen (18)",
  "V Sen5eS (18)",
  "Valanga(polysha Remix) (18)",
  "Valkyrja ~Aldrlag~ (18)",
  "Vividly Impromptu (18)",
  "With It This Heaven? (18)",
  "Xicholauncher (18)",
  "ZEИITH (18)",
  "αρχη (18)",
  "アオアラシ (18)",
  "ツマミ戦隊 タテレンジャー (18)",
  "び (18)",
  "プログレなぞなぞクイズのテーマ (18)",
  "ミッドナイト☆WAR (18)",
  "ミュージックプレイヤー (18)",
  "ランカーキラーガール (18)",
  "怪盗Ｆの台本～消えたダイヤの謎～ (18)",
  "蛇神 (18)",
  "狂水一華 (18)",
  "最小三倍完全数 (18)",
  "消失(Hommarju Remix) (18)",
  "翠雨の祷 (18)",
  "諏訪大信仰 (18)",
  "世界の果てに約束の凱歌を -VOLTEX Mix- (18)",
  "春告胡蝶 (18)",
  "星の透る夏空に願う (18)",
  "無魎大数 (18)",
  "666 (18)",
  "ΣgØ (18)",
  "* Erm, could it be a Spatiotemporal　ShockWAVE Syndrome...? (18)",
  "MAYHEM (18)",
  "VVelcome!! (18)",
  "Akzeriyyuth (18)",
  "ALTONA (18)",
  "Be a Hero! (18)",
  "BEAST BASS BOMB (18)",
  "Beyond the BLUE (18)",
  "Black night (18)",
  "BLAZING_LAZER (18)",
  "BlueMoon Princess (18)",
  "Boss Rush (18)",
  "Breakin' Asia (18)",
  "Catch Our Fire! (18)",
  "Cepheus (18)",
  "CHERNOBOG (18)",
  "Cloud 9 (18)",
  "Concertino in Blue (18)",
  "crossing blue (18)",
  "Destiny (18)",
  "Divine's:Bugscript (18)",
  "Divine's or Deal (18)",
  "Doppelganger (18)",
  "Dreadnought (18)",
  "DropZ-Line- (18)",
  "ECHIDNA (18)",
  "Evans (18)",
  "FIRE IN MY HEART (18)",
  "FLOOR INFECTION Medley　from SOUND VOLTEX×jubeat (18)",
  "GAIA (18)",
  "Gamerz FestivaL (18)",
  "Gate of Atlantis (18)",
  "GERBERA (18)",
  "Ghost Trigger (18)",
  "Glitter Flatter Scatter (18)",
  "Goddess Bless you (18)",
  "Gorgetech (18)",
  "Grand-Guignol (18)",
  "HP:1 (18)",
  "Hug!! Vs. Hug!! (18)",
  "ΗУМЛ (18)",
  "Juggler's Maddness (18)",
  "JUNKIE FLAVOR (18)",
  "Khionos TiARA (18)",
  "KIMIDORI Streak!! (18)",
  "LastΩmegA (18)",
  "Legendary Road (18)",
  "Levier'n NābYss (18)",
  "Lowermost revolt (18)",
  "Lunatic Sprinter (18)",
  "Make Magic (18)",
  "MeteorGlow Aftermath (18)",
  "Midnight City Warfare (18)",
  "Mirrorwall (18)",
  "MODEL FT4 (18)",
  "MONOLITH (18)",
  "New Leaf (18)",
  "Nexta (18)",
  "Night Rockin' Bird (18)",
  "Noisy Minority (18)",
  "Nostalgic Blood of the Strife (18)",
  "OPEN MY GATE (18)",
  "ouroboros -twin stroke of the end- (18)",
  "ΩVERSOUL (18)",
  "POLICY BREAK Medley　from SOUND VOLTEX×jubeat (18)",
  "Prey (18)",
  "PROVOES*PROPOSE <<êl fine>> (18)",
  "Puberty Dysthymia (18)",
  "PUPA (18)",
  "Re:End of a Dream (18)",
  "Яe's NoVǢ (18)",
  "Rebellio (18)",
  "Reb∞t (18)",
  "REDO the NIGHT (18)",
  "Redshift (18)",
  "RHYZING BEAT (18)",
  "Sacrifice and Faith (18)",
  "SACRIFICE feat.ayame (18)",
  "SAtAN (18)",
  "Scarlet Lance (18)",
  "She Turns Me On (18)",
  "Sky High (18)",
  "#SpeedyCats (18)",
  "Spirit of the Beast (18)",
  "STULTI (18)",
  "SUPER SUMMER SALE (18)",
  "Sweet Requiem (18)",
  "Taiko Drum Monster (18)",
  "The Formula (18)",
  "The Golden Era (18)",
  "THE HEAVEN (18)",
  "Theme of Ricerca (18)",
  "Touch My Body (18)",
  "TRICKL4SH 220 (18)",
  "ULTiMATE INFLATiON (18)",
  "ULTRAVELOCITY (18)",
  "V (18)",
  "Venomous Firefly (18)",
  "Victim of Nights (18)",
  "We Go Down (18)",
  "Wings of Glory (18)",
  "Xevel (18)",
  "Yum Yum Sweetie (18)",
  "お米の美味しい炊き方、　そしてお米を食べることによるその効果。 (18)",
  "オニユリ (18)",
  "キュリオシティ (18)",
  "サイコパスラビット (18)",
  "スラッシュ//シスターズ (18)",
  "セイクリッド ルイン (18)",
  "そして黄金郷へ (18)",
  "ドリームエンド・サバイバー (18)",
  "のぼれ八坂坂！ (18)",
  "びいすと！ (18)",
  "ファイナルレター (18)",
  "ホワイトパレード (18)",
  "まじかる生主＠りすなちゃん (18)",
  "メイビ～初恋！？ビスケット☆大作戦 (18)",
  "ワールズエンド・ダンスホール (18)",
  "怒槌 (18)",
  "永遠に幸せになる方法、見つけました。 (18)",
  "壊Rave*it!! 壊Rave*it!! (18)",
  "神獄烙桜 (18)",
  "恋歌疾風！かるたクイーンいろは (18)",
  "業焔繚乱 (18)",
  "極彩天奏 (18)",
  "祝福の色彩は想い結ぶ君たち迄 (18)",
  "準備運動 (18)",
  "神話に芽吹く (18)",
  "水簾ノ調 (18)",
  "誰が為に兎は舞う＝狂速狂騒曲＝ (18)",
  "超☆超☆光☆速☆出☆前☆最☆速!!!　スピード★スター★かなで (18)",
  "†渚の小悪魔ラヴリィ～レイディオ† (18)",
  "光射す澪のユズリハ (18)",
  "真っ白な靴 (18)",
  "雷鼓サンダービート (18)",
  "ΣmbryØ (18)",
  "*Feels Seasickness...* (18)",
  "FIN4LE ～終止線の彼方へ～ (18)",
  "Fin.ArcDeaR (18)",
  "I (18)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Empress Side (18)",
  "WHITEOUT (18)",
  "Xronièr (18)",
  "B.B.K.K.B.K.K. (18)",
  "Candy Colored Hearts (18)",
  "Le Fruit Défendu (18)",
  "NEO GRAVITY (18)",
  "The Sampling Paradise (P*Light Remix) (18)",
  "The star in eclipse (18)",
  "ちくわパフェだよ☆ＣＫＰ (18)",
  "雲の彼方 (18)",
  "Garakuta Doll Play (18)",
  "Angelic Jelly (18)",
  "Celestial stinger (18)",
  "Completeness Under Incompleteness (18)",
  "HAELE III ~Angel Worlds~ (18)",
  "KAC 2012 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- (18)",
  "NEO TREASON (18)",
  "Ok!! Hug Me (18)",
  "Opium and Purple haze (18)",
  "Renegade Fruits (18)",
  "Triple Counter (18)",
  "XROSS THE XOUL (18)",
  "↓↓↓ (18)",
  "ΑΩ (18)",
  "Angels And Demons (18)",
  "Blastix Riotz (18)",
  "Demise Quartet (18)",
  "EMPIRE OF FLAME (18)",
  "#Endroll (18)",
  "End to end (18)",
  "Endless GRAVITY (18)",
  "Firestorm (18)",
  "FLOWER (18)",
  "FLügeL《Λrp:ΣggyØ》 (18)",
  "Fox4-Raize- (18)",
  "GEOMETRIA (18)",
  "gigadelic (かめりあ's ''The TERA'' RMX) (18)",
  "HAVOX (18)",
  "IKAROS DYNAMITE!!!! (18)",
  "INF-B《L-aste-R》 (18)",
  "Invitation from Mr.C (18)",
  "JEHANNEDARC (18)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side (18)",
  "Lachryma《Re:Queen'M》 (18)",
  "LegenD. (18)",
  "MG277 (18)",
  "NEO GRAVITY (18)",
  "Ops:Code-Rapture- (18)",
  "Pon-Pon-Pompoko Dai-Sen-Saw! (18)",
  "Prayer (18)",
  "Preserved Valkyria (18)",
  "Quaint Echo (18)",
  "REVOLVER (18)",
  "Sayonara Planet Wars (18)",
  "Seraphim (18)",
  "Solar Storm (18)",
  "tricky trick (18)",
  "Ultimate Ascension (18)",
  "UnivEarth (18)",
  "veRtrageS (18)",
  "Warriors Aboot (18)",
  "World's end (18)",
  "XHAOS JUDGE (18)",
  "XyHATTE (18)",
  "アルティメットトゥルース -Phantasm- (18)",
  "きたさいたま2000 (18)",
  "ドーパミン (18)",
  "マサカリブレイド (18)",
  "ムラサキグルマ (18)",
  "極圏 (18)",
  "月光乱舞 (18)",
  "混乱少女♥そふらんちゃん!! (18)",
  "侍Annihilate!! (18)",
  "灼熱Beach Side Bunny (18)",
  "消失 (18)",
  "絶対零度 (18)",
  "到達してしまった僕らと夢と希望の最之果 (18)",
  "東方妖々夢 ULTIMATE MEDLEY (18)",
  "伐折羅-vajra- (18)",
  "冥天・ヘメロカリス (18)",
  "crazy cinema story (18)",
  "Foolish Hero (18)",
  "ボルテ体操第一 (18)",
  "#Fairy_dancing_in_lake (18)",
  "Joyeuse (18)",
  "Sakura Reflection (P*Light Slayer Remix) (18)",
  "She is my wife　すーぱーアイドル☆ミツル子Remixちゃん (18)",
  "Unicorn tail Dustboxxxx RMX (18)",
  "おお われら喜び讃うべし、主よ (18)",
  "こちら、幸福安心委員会です。 (18)",
  "ムーニャポヨポヨスッポコニャーゴ (18)",
  "上海紅茶館～ Chinese Tea Orchid Remix (18)",
  "C18H27NO3 (18)",
  "Harpuia (18)",
  "Idola (18)",
  "Qubism (18)",
  "超越してしまった彼女と其を生み落した理由 (18)",
  "魔境堕天録サリエル (18)",
  "CODE -CRiMSON- (18)",
  "Crack Traxxxx (18)",
  "Hellfire (18)",
  "Last Concerto (18)",
  "Wish upon Twin Stars (18)",
  "最終鬼畜妹フランドール・S (18)",
  "Bangin' Burst (18)",
  "Black Emperor (18)",
  "BLACK or WHITE? (18)",
  "For UltraPlayers (18)",
  "Growth Memories (18)",
  "INSECTICIDE (18)",
  "VALLIS-NERIA (18)",
  "VILE CAT (18)",
  "werewolf howls. (18)",
  "neu BSP style (18)",
  "物凄い勢いでけーねが物凄いうた (18)",
  "Broken 8cmix (18)",
  "Evans VolteX Pf arrange (18)",
  "Onigo (18)",
  "The world of sound (18)",
  "V.I.P. (18)",
  "金縛りの逢を (18)",
  "腐れ外道とチョコレゐト (18)",
  "幻想のサテライト (18)",
  "孤独の番人 (18)",
  "Absurd Gaff (18)",
  "PANIC HOLIC (18)",
  "Xepher Light and Darkness Dragon REMIX (18)",
  "魔理沙は大変なものを盗んでいきました (18)",
  "croiX (18)",
  "FLOWER REDALiCE Remix (18)",
  "Max Burning!! (18)",
  "冥 Rockin' SWING REMIX (18)"
];

var songlists19 = [
  "2 Beasts Unchained (19)",
  "777 (19)",
  "Absurd Gaff (Metallize Remix) (19)",
  "All We Need is HAPPY END!!! (19)",
  "AμreoLe ~for Triumph~ (19)",
  "and After the Merry BADEND (19)",
  "Avalanx (19)",
  "αzalea (19)",
  "Bad Elixir (19)",
  "BAYONEX (19)",
  "Breakneck Pursuit (19)",
  "Chronomia (19)",
  "CLAMARE (19)",
  "DEUX EX MĀXHINĀ (19)",
  "EncorE & cALL (19)",
  "Fαtα∠ Ent∠mEnt (19)",
  "Glory of Fighters (19)",
  "HALO (19)",
  "Holy Trail (19)",
  "[ ]DENTITY (19)",
  "LaμreLs ~the Angelus~ (19)",
  "MILITARY R04D (19)",
  "One More Lovely (19)",
  "onslaught -Retaliation of Bahamūt- (19)",
  "perditus†paradisus (19)",
  "QQ (19)",
  "Rapsodia d'amore (19)",
  "Reverenced Flower (19)",
  "Rhapsody ⚙f Triumph (19)",
  "Spectacular“V”Adventure! (19)",
  "The Clown of 24stairs (19)",
  "Undead Raving Scare (19)",
  "VALKYRIE ASSAULT (19)",
  "VΛZiLiSQ (19)",
  "VOLAQUAS (19)",
  "Xb10r (19)",
  "ZEUS (19)",
  "すべてが幻になった後で (19)",
  "ディスコルディア (19)",
  "ドゥサンコオデッセイ!! (19)",
  "ピアノ協奏曲第１番”蠍火” (19)",
  "ピアノ独奏無言歌 ”灰燼” (19)",
  "赫焉 (19)",
  "赫焉のヴァルキュリア -Ragnarok- (19)",
  "紫焔双穿 (19)",
  "十の試煉 (19)",
  "竹 (19)",
  "無意識レクイエム (cosmobsp rmx) (19)",
  "恋愛＝精度×認識力 (19)",
  "9TH5IN (19)",
  "ANGER of the GOD (19)",
  "Calamity Tempest (19)",
  "Daisycutter (19)",
  "ENDYMION (19)",
  "Ghost Family Living In Graveyard (19)",
  "Lancelot ～Flame of the Rebellion～ (19)",
  "Lisa-RICCIA (19)",
  "LubedeR (19)",
  "ΛΛemoria (19)",
  "†:OLPHEUX:† (19)",
  "OUTERHEΛVEN (19)",
  "Redshift 2nd Ignition (19)",
  "ЯeviveR (19)",
  "TENKAICHI ULTIMATE BOSSRUSH MEDLEY (19)",
  "THE凸GENERATOR (19)",
  "Trill auf G (19)",
  "voltississimo (19)",
  "Xroniàl Xéro (19)",
  "θコトノハθカプセルθ (19)",
  "色を喪った街 (19)",
  "卑弥呼 (19)",
  "飄える翼追い掛けて (19)",
  "A Lasting Promise (19)",
  "Absolute Domination (19)",
  "Awakening (19)",
  "BELOBOG (19)",
  "Chrono Diver -PENDULUMs- (19)",
  "Cross Fire (19)",
  "Deadly force (19)",
  "Dyscontrolled Galaxy (19)",
  "Elemental Creation (19)",
  "Failnaught (19)",
  "Fin.ArcDeaR (19)",
  "Fly Like You (19)",
  "FREEDOM DiVE (19)",
  "GERBERA -For Finalists- (19)",
  "GODHEART (19)",
  "Immortal saga (19)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Empress Side (19)",
  "Last Resort (19)",
  "Sailing Force (19)",
  "Staring at star (19)",
  "TWO-TORIAL (19)",
  "Xéroa (19)",
  "セイレーン ～悲壮の竪琴～ (19)",
  "逆月 (19)",
  "2 MINUTES FIGHTERS (19)",
  "EMPIRE OF FLAME (19)",
  "End to end (19)",
  "Invitation from Mr.C (19)",
  "LegenD. (19)",
  "veRtrageS (19)",
  "INF-B《L-aste-R》 (19)",
  "FLOWER (19)",
  "Got more raves？ (19)",
  "きたさいたま2000 (19)",
  "極圏 (19)",
  "ΑΩ (19)",
  "Blastix Riotz (19)",
  "DIABLOSIS::Nāga (19)",
  "Everlasting Message (19)",
  "FLügeL《Λrp:ΣggyØ》 (19)",
  "KAC 2013 ULTIMATE MEDLEY　-HISTORIA SOUND VOLTEX- Emperor Side (19)",
  "Lord=Crossight (19)",
  "Preserved Valkyria (19)",
  "XyHATTE (19)",
  "月光乱舞 (19)",
  "Fiat Lux (19)",
  "HYENA (19)",
  "Innocent Tempest (19)",
  "IX (19)",
  "ラクガキスト (19)",
  "音楽 -resolve- (19)",
  "Booths of Fighters (19)",
  "For UltraPlayers (19)",
  "INSECTICIDE (19)",
  "Quietus Ray (19)",
  "Verse IV (19)",
  "バンブーソード・ガール (19)",
  "Bangin' Burst (19)",
  "Black Emperor (19)",
  "BLACK or WHITE? (19)",
  "Growth Memories (19)",
  "snow storm -euphoria- (19)",
  "XROSS INFECTION (19)",
  "大宇宙ステージ (19)",
  "Ganymede kamome mix (19)"
];

var songlists1819 = new Array;
songlists1819 = songlists18.concat(songlists19);
xi = songlists1819.length; // 곡 갯수
xxi.innerHTML = "전체 곡 "+ xi +"곡";

function input() {
  $("ul").empty();
  var howmany = document.getElementById("select1").value;
    for(i=0;i<howmany;i++){
      var newDiv = document.createElement('div');
      newDiv.id = "result"+i
      var newContent = document.createTextNode(songlists1819[Math.floor(Math.random()*(xi-1))]);
      newDiv.appendChild(newContent);
      document.getElementById("ul").appendChild(newDiv);
    }
  message2.innerHTML = "마음에 들지 않는다면 재추첨 버튼을 눌러주세요"
  cc.innerHTML = "재추첨"

};
